### ISSUE TITLE
Suggestion: Better installer file naming

### ISSUE THREAD

**Issue by TrapinchO** [DraqueT/PolyGlot#1011]
Different versions of installer should have a different name for easier recognition if multiple version installers are on the device, including beta releases.
Names could be e.g. `PolyGlot-3.3.0-Ins-Win.exe` and `PolyGlot-3.4.0-BETA-Ins-Win.exe`

**Comment by TrapinchO** [comment]
For beta a date could be used, e.g. `PolyGlot-Ins-Win-BETA-2021-11-21-01-47.exe`.

**Comment by TrapinchO** [comment]
This could be easily done here:
https://github.com/DraqueT/PolyGlot/blob/master/build_image.py#L593

Simply add after the if
```
else:
    insFile += "_BETA_" + datetime.datetime.now.strftime("<enter your format here>")
```
I can make a pr if needed.

**Comment by synthfi** [comment]
adding the name "_BETA_" is useful for tracking. Unsure about attaching dates to the installer files as  I think the version number is more important. It doesn't take long to rebuild the application

**Comment by TrapinchO** [comment]
This has been a problem where I used to periodically download and test the program. Though the builds were different, the version number remained the same and created confusion.

Proper versioning would fix it.

**Comment by synthfi** [comment]
Completed in https://github.com/DraqueT/PolyGlot/pull/1375
