### ISSUE TITLE
Replace Alphabet field

### ISSUE THREAD

**Issue by finchbeast** [DraqueT/PolyGlot#1013]
The alphabet field is absolutely terrible, and needs desperately to be replaced. To do so, do the following:

- Write a custom class, implementing a custom visual list (I should have done this ages ago)
- must have +, - buttons below it - togglable visible/invisible - each button can be enabled/disabled independently
- must have up/down arrows - togglable visibile/invisible - each button can be enabled/disabled independently
- Allow abstract way of building rows based on type.
- If initialized with given node type, node must implement class which defines how many columns it has, and returns a list of strings with that length, which each representing a column value for its row
- If initialized with <Object>, presume single column and all objects passed simply return their string value
- able to return complex object of selected row

Once this is implemented, I'll be able to replace all the MANY implementations of this exact functionality in PolyGlot. But in particular, I'll be able to do it for the terrible Alphabet interface.

ADDITIONALLY - remove the naked alphabet string from the language properties class. Simply use the array from now on.

**ORIGINAL TEXT**
Ubuntu 20.04, Polyglot version [3.3]

Even after populating an alphabet in Phonology & Text, checking to make sure I don't have lookalike characters, and checking to ensure no extra spaces, Language Check constantly fails. Here's an example error:

Word contains characters undefined in alphabet settings.
Suspect characters:"v"

I have "v" defined. As a test, I created a new language and left all settings and configuration blank. I attempted to enter a two character word: ve. I gave it a translation and used the Check Language feature and got the exact same error. If I delete the letter "v", leaving a word that only contains "e", I get this error:

Word contains characters undefined in alphabet settings.
Suspect characters:"???"

I've checked my font settings to ensure I don't have a font selected that doesn't exist on the system. I've also read through the help file multiple times. The only relevant part I can find is this:
WORD OF WARNING: Please be sure to type in the "Character(s)" field in the exact same way as you are going to be entering your words. I have encountered users that have accidentally entered lookalike characters into the left-hand column. 

In all test cases, the letters in question have been typed from my keyboard directly into PolyGlot.
![PolyGlot_error1](https://user-images.githubusercontent.com/67406175/138396376-63dd3a2d-ef5d-4a2a-af0d-5fc0555b13fc.png)
![PolyGlot_error2](https://user-images.githubusercontent.com/67406175/138396377-09a8471c-8d99-4c79-84f9-da41498acfe1.png)
![PolyGlot_error3](https://user-images.githubusercontent.com/67406175/138396378-fe991049-8098-4b03-96b4-63377d0fc193.png)

**Comment by MarinaGryphon** [comment]
This is for alphabetical order, I believe, not pronunciation. Can you post what your alphabetical order settings are under lang properties?

**Comment by DraqueT** [comment]
Thank you for the excellent documentation here! The problem you’re describing absolutely sounds frustrating. Could you please send me a copy of the language file so I can see the bug in action? I have not been able to recreate it, so it’s probably some scenario that has not thought of yet. 

You can email the file to draquemail@gmail.com

I’m going to be out of town until part way through next week, but will take a closer look when I get back!
