### ISSUE TITLE
can't launch PolyGlot-ins-Win.exe by normal means

### ISSUE THREAD

**Issue by WolframRele** [DraqueT/PolyGlot#1019]
hi i was trying to install polyglot but the installer wouldn't launch(file explorer). I was thinking it might be a problem with my web browser (firefox), so I tried explorer and through the lanche prompt from the finicht download it was able to lanche. thinking that this might just be a good download, i cancelled the install and tried to launch it from the explorer but this did not work. tried launching it from firefox as well and that did not work

**Comment by DraqueT** [comment]
Heyo, sorry to take so long to get back to you here. I think that ultimately Firefox was interfering with running the executable from the download folder. The solution here is to download the installer to the desktop or something and run from there.

**Comment by WolframRele** [comment]
can't roun from desktop as i can't run from windows built in fill explorer as noted. have also tried directly from desktop and that does not work.

this is why it's weird that internet explorer can do it
