### ISSUE TITLE
Arabic (س) & Hebrew (ה) Character Display Bug

### ISSUE THREAD

**Issue by cyNickalCyn** [DraqueT/PolyGlot#1032]
Greetings,

Loving the software, it's making creating sets of blended languages that much easier!

I have noticed a bug, however, for the Arabic (س) & Hebrew (ה) characters; they don't display correctly in the software! Whenever I try to insert a character from either of the two languages I get this instead: "▯"
I've tried making another project and tested the character sets to see if they'll work there but it's the same issue. It's strange that I could get Cyrillic (и) to work just fine for another project!

Any help or advise to get these to work would be greatly appreciated!

Kind Regards,
Nick

**Comment by TrapinchO** [comment]
I think this might apply to any scripts going right-to-left

**Comment by DraqueT** [comment]
Heyo! Thank for your interest in PolyGlot, and I'm glad that you're enjoying it!

So what you're seeing there is just the default font for PolyGlot not being able to render Hebrew. You'll need to snag a font that supports it then import it into your language from the menu. You can find a bunch of good choices here: https://www.myfonts.com/tags/hebrew

Let me know if this clears things up for you!

**Comment by cyNickalCyn** [comment]
Greetings!

Your advice works but it only supports one font import at a time. I'll have to look into merging hebrew and arabic into a single font file when I get the time :)

Thanks all the same, though!

**Comment by DraqueT** [comment]
To do that, I highly recommend the free tool FontForge. Directions to do so are here: 
https://superuser.com/questions/490922/merging-two-fonts

Happy conlanging! :3
