### ISSUE TITLE
[BETA] Lexical classes behave weirdly - "Associative" option unchecks itself yet retains its properties

### ISSUE THREAD

**Issue by TrapinchO** [DraqueT/PolyGlot#1038]
Polyglot version: Windows BETA from 19th November 2021 (latest as of writing this)

How to reproduce:
1) create a new language
2) create a new word, say `word1`
3) create a new lexical class, say `class1` and make it `Associative`
4) check `word1` -> works as intended
5) check `class1` -> `Associative` check mark is unchecked
6) check `word1` -> still behaves as if `class1` was associative

**Comment by TrapinchO** [comment]
also seems to appear that when the file is saved with both options unchecked (so that a value is chosen), it sets to associative (while both options being unchecked) upon closing and reopeing it.
Not 100% sure on that one though

**Comment by DraqueT** [comment]
Thank you for the great bug writeups and for taking the time to make them for the beta! This new version of PolyGlot has a LOT of under the hood changes (core functions compatible with Android now...) on top of all the new features that I'm dropping in, so bug testing/reports are hugely appreciated!

**Comment by TrapinchO** [comment]
Polyglot version: Windows BETA from 22th November 2021 (latest as of writing this)
Bug still appears, just in different way.

Steps to reproduce:
1) create a lexical class, say `class1`
2) give it 2 values, say `val1`, `val2`
3) create a new word `word1` and give it value `val1`
4) save the language, say as `test`
5) open the file
6) check the `class1`
6a) `Free Text Value` is now checked
7) unmark the `Free Text Value` option
8) check `word1`
8a) it should be now `Associative`, if not, repeat step `7`
9) check `class1`
9a) none of the options are now checked
