### ISSUE TITLE
Unable to edit the project file outside PolyGlot

### ISSUE THREAD

**Issue by TrapinchO** [DraqueT/PolyGlot#1040]
Polyglot version: Windows BETA from 19th November 2021

Possible cause: `DictSaveDate` part might mess with it, as saving it creates a disparity in save times

This also prevents users from correcting the results of bugs, such as #1038 

Steps to reproduce:
1) create a new lexical class, say `class1`
2) give it a value say `val1`
3) save the language, say as `test.pgd`
4) close the language
5) find the file in your pc
6) rename it a zip file and decompress it
7) open `PGDictionary.xml`
8) rename `class1` to `class2` (or presumably edit *anything*, even whitespace)
9) save it
10) compress the file again
11) rename it to `.pgd`
12) double-click it (to open it)
![bug3](https://user-images.githubusercontent.com/67415128/142757688-2138f82e-af00-4d52-b729-8a4cc1853af9.png)

**Comment by DraqueT** [comment]
Could you please send me a copy of the manually edited pgd file you've created and let me know what zip utility you're using? I am not able to reproduce, and I'm wondering whether there is some idiosyncrasy or slight difference between utilities that PolyGlot doesn't account for.

I also might build something into PolyGlot that ultimately handles packing and unpacking pgd files to save folks the trouble of dealing with this altogether. As always, thanks for all the reporting here!

**Comment by DraqueT** [comment]
Opened up this feature ticket. I'll probably work on this one next and it'll make your life easier. #1042

**Comment by TrapinchO** [comment]
I am using default zip utility (right-click -> send to -> "Compressed (zipped) folder").

Might be the process of zipping/unzipping, haven't tested that yet.

I will send the file later, if it is still needed.

**Comment by TrapinchO** [comment]
Here is a test file, I have literally just decompressed the file zipped it back.
(the file is in `.zip` so github would accept it, I hope you don't mind it this way)
[test.zip](https://github.com/DraqueT/PolyGlot/files/7583443/test.zip)

**Comment by DraqueT** [comment]
As a heads up, this should now be a built in feature for PolyGlot in the newest betas available. Just go to Tools->Advanced and you'll see the options. It'll also automatically do an integrity check when building the PGD file from a directory for you.
