### ISSUE TITLE
[BETA] Grammar chapters disappear when more than 1 nameless chapters are created

### ISSUE THREAD

**Issue by TrapinchO** [DraqueT/PolyGlot#1053]
Polyglot version: Windows BETA from 24th November 2021

Steps to reproduce:
1) create a new chapter (without a name)
2) create a second chapter
2a) the previous one will disappear
3) delete the only rendered one
3a) the first one will appear

**Comment by DraqueT** [comment]
All of this bug testing you've been doing is absolutely invaluable. When I make a release, would you like me to credit you for all the assistance? If so, just let me know what name/pronouns to use. :3

**Comment by TrapinchO** [comment]
I definitely wouldn't mind that! Please use my username and he/him pronouns, thanks :)

**Comment by DraqueT** [comment]
Will do! Hoping to release in the next month or two, depending on how many more goodies I decide to try and pack in. ^^
