### ISSUE TITLE
[BETA] Phrasebook: newlines are replaced by spaces upon selecting something else

### ISSUE THREAD

**Issue by TrapinchO** [DraqueT/PolyGlot#1064]
Polyglot version: Windows BETA from 29th November 2021 (latest as of writing this)

Steps to reproduce:
1) create  a new phrasebook entry
2) poplate all fields with text separated by newlines
3) select anything else, e.g. Logographs
4) select phrasebook again

**Comment by DraqueT** [comment]
Yeesh, this one had existed elsewhere in functionality as well! Nice to wrap it up.
