### ISSUE TITLE
Language statistics: bugs preventing the display of charts

### ISSUE THREAD

**Issue by TrapinchO** [DraqueT/PolyGlot#1067]
Polyglot version: Windows BETA from 29th November 2021 (almost surely happens on stable version as well)

### Missing alphabet order
Cause: `Uncaught SyntaxError: Unexpected token ']'` - line 35

Steps to reproduce:
1) create few words, say `aaa` and `bbb`
2) generate language statistics
3) inspect the main html file line 35
(proof of cause)
4) add letters `a` and `b` to alphabet fields
5) generate language statistics again
6) see the page

### `'` in alphabet field
Cause: `Uncaught SyntaxError: Unexpected string` - line 37

Steps to reproduce:
1) keep the previous language
2) add `'` to alphabet field
3) regenerate the alphabet field
4) see the page

Solution:
Sanitise the inputs. Theoretical entryway for xss (my attempt for injecting `' + console.log('hello') + '` failed however).

**Comment by TrapinchO** [comment]
Found cause of the first error:
https://github.com/DraqueT/PolyGlot/blob/249ca27fb2e0dda8f298895106a6e1a18547890e/src/main/java/org/darisadesigns/polyglotlina/PGoogleBarChart.java#L106-L120

The for loop is skipped and line `120` removes the `[\n` (from line `106`), which creates a syntax error. Maybe use `joinToString` (or whatever it is Java) or something similar instead?

**Comment by DraqueT** [comment]
Good eye, thanks for checking this one out! Added to the 3.5 roadmap. :3

**Comment by DraqueT** [comment]
So this one is mostly fixed. There's a minor known bug where character entities will display ("&nbsp;" for double space, etc) in the Google graphs. To correct that one, the entire stats system would have to be rewritten. That *is* on my genda eventually but that's down the road a bit.
