### ISSUE TITLE
[BETA] switching from Lang Properties with invalid alphabet freezes the application

### ISSUE THREAD

**Issue by TrapinchO** [DraqueT/PolyGlot#1068]
Polyglot version: Windows BETA from 29th November 2021 (almost surely happens on stable version as well)

Steps to reproduce:
1) put one of the "broken" words into a single alphabet field
2) switch to another tab

broken words:
- `fffh`
- `ffhh`

possible causes:
- when there are 3 of the same letters **and** something after (`dfff` changes it to `d` and `f`)
- when there are multiple duplicate letters

**Comment by DraqueT** [comment]
Good catch! This applies particularly when someone is just starting a language and they only have a single alphabetic entry.
