### ISSUE TITLE
[BETA] Doubled dropdown texture

### ISSUE THREAD

**Issue by TrapinchO** [DraqueT/PolyGlot#1072]
Polyglot version: Windows BETA from 11th December 2021 (latest as of writing this)
The another button texture appears upon clicking a dropdown.
![bug](https://user-images.githubusercontent.com/67415128/145723279-7c6efeb9-5b32-4a89-85b6-16dbef30b717.png)

**Comment by DraqueT** [comment]
Cleaned this up a bit and added a selected color, which should have been there in the first place.
