### ISSUE TITLE
[BETA] Print to PDF: cannot render some characters

### ISSUE THREAD

**Issue by TrapinchO** [DraqueT/PolyGlot#1074]
Polyglot version: Windows BETA from 14th December 2021 (latest as of writing this)

Steps to reproduce:
1) set "local (or conlang) language" to `ě ů č ď ň ř ť`
2) open "print to pdf" menu"

Probably related to #1037, which has been successfully fixed and closed.

**Comment by DraqueT** [comment]
Ahhh, ok. I was only looking in the actual printed PDF itself rather than the menu, thanks for the attention to detail here. :3
