### ISSUE TITLE
[BETA] Create language Check warning for ambiguous alphabets

### ISSUE THREAD

**Issue by TrapinchO** [DraqueT/PolyGlot#1075]
Add  an additional check to the language check feature which looks for ambiguity in the alphabet. This should only be a warning, as sometimes it is unavoidable when working with existing languages and character sets.

ORIGINAL TICKET TEXT:
Polyglot version: Windows BETA from 14th December 2021 (latest as of writing this)

Steps to reproduce:
1) create alphabet letters `a` and `au` (**in that order**)
2) create words `au` and `a`
3) print language statistics
4) `a` will have 2 words and `au` none
5) create alphabet letter `u` ´below `au`
6) reprint the statistics
7) `u` will have 1 word (though by pronunciation it shouldn't have

I realised it might be kind of false alarm since this is just "standard" regex stuff, but I think at least a warning in the docs would be nice.

**Comment by DraqueT** [comment]
Hrm. A language that includes letters constructed in ambiguous ways from characters is something I can only do so much about. I think I'm just going to add a warning to the Language Check feature that makes certain that no individual letters in their entirety are prefixes or suffixes for others.
