### ISSUE TITLE
RC1 For PolyGlot 3.5

### ISSUE THREAD

**Issue by DraqueT** [DraqueT/PolyGlot#1084]
@TrapinchO 

Heyo! As a heads up, the RC1 for PolyGlot 3.5 is up as  beta now! I'm mostly just hunting for bugs/updating documentation atm and have completed all features that I was planning on including in 3.5. Let me know if you run into anything in it, and thank you again for all the help with this release! You found a BUNCH of bugs that I had overlooked in the past, many of which I think had been present for years.

**Comment by DraqueT** [comment]
@TrapinchO 

Second time around, but I do think this might be the final candidate. The decision to put the Zompist guide in took some time, and I ended up chasing down some loose code that has been a problem for quite some time... but at this point I' just plugging away at documentation. Take a final look over it and let me know if you've got any other thoughts.

And thank you for the time you've spent helping! PolyGlot is going to be so much better for all the polish quality checking you helped put into it! : )

**Comment by TrapinchO** [comment]
The worst bugs seem to be fixed (and of course, as soon as I wrote this I found two new ones :D), so I think it is ready for release.

And as always, I was glad to help!

**Comment by DraqueT** [comment]
Alright! I am closing this out and I think I'm going to do the release tomorrow!

Thank you for helping me make this what (fingers crossed) is going to be the tightest/most bug free release of PolyGlot yet!
