### ISSUE TITLE
Syllable composition

### ISSUE THREAD

**Issue by DraqueT** [DraqueT/PolyGlot#1106]
Using the Zompist engine to create all possible syllables, create a feature which composes syllable breaks.

1) using the same algorithm that checks for pronunciation, check for the points where a word can be broken into syllables
2) run the pronunciation generator
    in the generator, pay attention to how many characters have been consumed at any given point, and if there is a mark for a break at the end of a valid pronunciation point, add the syllable break character (if option enabled)

**Comment by TrapinchO** [comment]
Also somehow adress illegal consonant clusters

**Comment by DraqueT** [comment]
Huh... this might actually be something that I want to add into the zompist engine itself. The author gave me permission to use his algorithm, but if there was an additional text field for illegal combinations, that would be a big improvement.

**Comment by DraqueT** [comment]
Goddamn, that is a fantastic idea, and now that I'm looking at implementing it, it will be super easy. Once again, I appreciate your efforts here! : D
