### ISSUE TITLE
Cannot Save Files

### ISSUE THREAD

**Issue by DestinySilver** [DraqueT/PolyGlot#1108]
PolyGlot's in window functionality is functioning fully. The issue I have is that when I attempt to save a file using "Save" or "Save As", the file prompt appears as normal, and even appears to be successful, until the folder where it is trying to save files to is checked again and remains empty save for the .ini file and the error log file. I have already attempted running the program as an administrator to give it a higher permission level, and the issue persists. The following error has appeared repeatedly in my error log, and I presume it is caused by the failed file save:

2022/01/10 10:42:19-Open quote is expected for attribute "href" associated with an  element type  "link".-org.xml.sax.SAXParseException
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 155; Open quote is expected for attribute "href" associated with an  element type  "link".
	at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:261)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at org.darisadesigns.polyglotlina.polyglot@3.3/org.darisadesigns.polyglotlina.WebInterface.checkForUpdates(WebInterface.java:87)
	at org.darisadesigns.polyglotlina.polyglot@3.3/org.darisadesigns.polyglotlina.Screens.ScrUpdateAlert.<init>(ScrUpdateAlert.java:75)
	at org.darisadesigns.polyglotlina.polyglot@3.3/org.darisadesigns.polyglotlina.Screens.ScrUpdateAlert.run(ScrUpdateAlert.java:405)
	at org.darisadesigns.polyglotlina.polyglot@3.3/org.darisadesigns.polyglotlina.Screens.ScrMainMenu$2.run(ScrMainMenu.java:681)

**Comment by DraqueT** [comment]
Thank you for the details there! A few points and questions.

I do not believe that the error you found in the log is responsible for this behavior. That is the portion of PolyGlot that fires off to check for updates, and thanks to Google changing its file presentation structure, it is broken for literally all users at the moment.

Questions for you:
- Are you using the current release of PolyGlot or the current beta? 
- What version of Windows are you running?

 It sounds like you are trying to save into your ~/PolyGlot folder (based on only seeing the log and ini file in there): have you tried saving to your desktop and seeing whether the file appears there? It's possible that your user folder has some kind of permissions going on that is confusing the program, and this would help test that theory.

**Comment by DestinySilver** [comment]
I hadn't when I made the initial post, but I have now attempted to save to the base directories on both my C: and D: drives (while running as administrator) as well as to my default downloads folder with no success. I just downloaded the program yesterday after a friend recommended it to me, and I downloaded the current release. I am running Windows 10 Home Version 20H2 (the 2nd most recent update of windows 10.) I would rather not restart my PC to update to the most recent version, as I currently have several hours of work loaded in the program which, per the nature of the issue, I am unable to save.

**Comment by DraqueT** [comment]
What's strangest is that when I think about it, I *know* that PolyGlot has write access in your ~/PolyGlot folder, because it created both the folder and the ini file there. Two things that I can think of:

1) Please try to save, then immediately after this, snag the error log and email that over to me at draquemail@gmail.com. I can't analyze that and see if there's anything in there at all that might be logging this.

2) Dud you happen to install PolyGlot on a different Windows account than that one that you're currently using? It's an odd scenario, but I'm scratching my head here.

**Comment by DestinySilver** [comment]
My windows account is the same one as the install. I'll send the error log to you in a moment. If there's not a fix from there I think I'm going to have to bite the bullet and lose my work to update windows and, failing that, reinstall the program.

**Comment by DraqueT** [comment]
At this point I am at an absolute loss. BUT! There is still one way that you can potentially save a lot of your data.

Click Tools->Export to Excel, and when prompted, choose not to export declensions. This will allow you to export your lexicon as an excel file that you can later re-import.

Also, when you reinstall, I _highly_ recommend that you use the beta. It is only a few weeks away from release, and is much more stable, with much more safety features, etc. You can find it on the normal download page here: https://draquet.github.io/PolyGlot/

If you wait to reinstall until tomorrow, you'll have the version which includes the integrated Zompist generator.

Let me know how it goes!

**Comment by DraqueT** [comment]
And the new beta installer is up.

**Comment by DestinySilver** [comment]
Thanks - the new beta is working fine, and the excel trick allowed me to save a good chunk of my work.
