### ISSUE TITLE
[BETA] word generator values are not saved when selecting different polyglot menu

### ISSUE THREAD

**Issue by TrapinchO** [DraqueT/PolyGlot#1111]
Polyglot version: Windows BETA from 10th January 2022 (latest as of writing this)

Steps to reproduce:
1) go to `Word Generator`
2) change some stuff (e,g, delete some categories)
3) click on `Lexicon`

**Comment by DraqueT** [comment]
Ultimately a dupe of 1116, as they're the same underlying issue (in that I never thought to implement this).

**Comment by DraqueT** [comment]
Got my wires crossed, reopening...
