### ISSUE TITLE
[BETA] Word generator: non-existent categories are ignored

### ISSUE THREAD

**Issue by TrapinchO** [DraqueT/PolyGlot#1112]
Polyglot version: Windows BETA from 10th January 2022 (latest as of writing this)

Steps to reproduce:
1) go to `Word Generator`
2) delete categories `V` and `R`
3) generate values
3a) capital `V` and `R` appear in the words

**Comment by DraqueT** [comment]
This one is actually a feature (I swear XD). Characters which do not correspond to categories are treated as constant values. This allows users to have specific inter syllable character rules if they desire. This'll be covered in the documentation once I get to the point where I'm adding it.
