### ISSUE TITLE
[BETA] ToDo: text disappears upon saving and quitting

### ISSUE THREAD

**Issue by TrapinchO** [DraqueT/PolyGlot#1116]
Polyglot version: Windows BETA from 10th January 2022 (latest as of writing this) (might work on stable as well)

Steps to reproduce:
1) create new ToDo label, say `test`
2) save the file, say as `test.pgd`
3) close the file
4) reopen it
4a) the label is now invisible except the checkbox
5) create a new label, say `test2`
5a) both labels are now visible

notes:
- checkboxes remain check (or unchecked) as they were left

**Comment by DraqueT** [comment]
Huh! I hadn't considered that users might want this to be saved since the original zompist generator is a web app. Definitely a feature to include.
