### ISSUE TITLE
[BETA] Sound recording: moving the slider doesn't actually change from where the audio plays

### ISSUE THREAD

**Issue by TrapinchO** [DraqueT/PolyGlot#1124]
Polyglot version: Windows BETA from 17th January 2022 (latest as of writing this)

Steps to reproduce:
1) create a grammar page, say "test"
2) record any audio
3) play a part of it, then pause it
4) move the slider to the start
5) unpause the audio
6) it starts from where it stopped

**Comment by DraqueT** [comment]
Good catch. Users aren't actually supposed to be able to slide this around. It's mostly just there to show how much longer a recording goes for.
