### ISSUE TITLE
[BETA] Word Generator: rewrite rules do not work

### ISSUE THREAD

**Issue by TrapinchO** [DraqueT/PolyGlot#1126]
Polyglot version: Windows BETA from 17th January 2022 (latest as of writing this)

Steps to reproduce:
1) delete all categories, etc.
2) create category `C = p`, rule `p|a`, syllable type `C`
3) click on `Generate All Possible Syllables`
4) generate values
4a) the only syllable is `|`

| rule | result |
|:----:|:------:|
| p \|a | space |
| pa | p |
| ap | p |
| a\|p | p |

**Comment by DraqueT** [comment]
Just want to make sure I'm understanding what you're reporting here. I think this is coming mostly from spaces being unexpected. In step 2, you're putting spaces between the = sign on either side, which confused the generator. I've modified it to that spaces are just discarded before processing.

rule | result | new result
-- | -- | --
p \|a | space | a
pa | p | p (without | symbol, it looks for "pa" which does not appear)
ap | p | p (searching for "ap" which does not appear)
a\|p | p | (searches for "a" which does not apper)

From my perspective there, only the first entry in the table was malfunctioning, but let me know if I'm misunderstanding something there in our process.

**Comment by DraqueT** [comment]
This was a head desk moment when I found it. XD
