### ISSUE TITLE
Tooltips not appearing on Windows

### ISSUE THREAD

**Issue by awbooze** [DraqueT/PolyGlot#1128]
First, I do want to say thanks for all your work on this and the excellent release. I conlang off and on in my spare time and this has helped make it much easier to do.

However, running on either Windows 10 or Windows 11, I am not seeing tooltips show up in any dictionaries or language files in version 3.5, even the example ones. As an example, here's a screenshot of my mouse hovering over a word in the agglutinative example language. Based on behavior in previous versions, I would expect a tooltip to appear including the part of speech of the word and any definition text. If I had to guess, this absence would be related to #1002 or #1045, but I don't really know. I hope I'm not missing something obvious, either.

![An image of a mouse pointer hovering over a PolyGlot word without a tooltip appearing](https://user-images.githubusercontent.com/42682253/150661763-0117c052-f22f-49e1-a5fb-d55445dfc59e.png)

### Steps to Reproduce
- Open any language file with PolyGlot version 3.5
- Hover over any word with a part of speech or an expanded definition (or an IPA symbol on the IPA Chart)
- Notice that no tooltip appears

**Comment by DraqueT** [comment]
Thanks for the heads up! Going to be checking this out shortly! I'll probably come out with a 3.5.01 within a few weeks, but I am waiting to see whether any other bugs shake out first.
