### ISSUE TITLE
"Language Statistics" generates but does not open the HTML window

### ISSUE THREAD

**Issue by chricker05** [DraqueT/PolyGlot#1129]
I click on the Language Statistics, and it generates the statistics but then closes the progress bar and nothing happens. It's supposed to open an html file, correct?

Not sure what the issue is.

PolyGlot 3.5/Windows 10

**Comment by TrapinchO** [comment]
Seems to be working for me in a test file. Could you please try opening exaple "Lodenkur" and try to open statistics from there?

Did you get any warnings, such as "complete alphabetic order"?

**Comment by DraqueT** [comment]
Thanks for reporting this! Trapinch0 has good advice there, try that first. If the statistics load for Lodenkur, could you send me a copy of your language file? There might be something you're using in the language which I hadn't thought of, and which is causing it to choke somehow, which I could check for.

**Comment by chricker05** [comment]
Hello. I'm attempting to use the Lodenkur file, but it's giving me grief about the font not being installed on my computer (I installed it and it still won't work).

Here is my language file.
https://www.dropbox.com/s/14tcd2g7utvdcje/Tobonese.pgd?dl=0

**Comment by TrapinchO** [comment]
When I first opened the file I got this error: (didn't get it after reopening and redownloading the file though)
![their_bug_1](https://user-images.githubusercontent.com/67415128/151246055-0c484aeb-f3fe-4dc2-a887-730b140b92f9.png)

The language statistics report shows to me completely fine.

**Comment by chricker05** [comment]
Ok. That's bizarre. Let me go over everything I do.
I just installed the latest release so this is a completely fresh version of the software.

1. I open the language file.
2. I click the "language statistics" in the "tools" dropdown.
3. The error happens.

It is my suspicion that PolyGlot is being prevented from opening the HTML for some reason, probably something to do with permissions. I attempted to run it in administrator mode but it didn't even boot up when I did that.

**Comment by TrapinchO** [comment]
> It is my suspicion that PolyGlot is being prevented from opening the HTML for some reason, probably something to do with permissions.
Try temporarily shut down your antivirus. This happens to me a lot with pdf export.

**Comment by chricker05** [comment]
Hm, I don't have any third-party antivirus, but I do have Windows' built in antivirus. I disabled real-time protection temporarily and even added PolyGlot's directory to the exclusions. That didn't do anything sadly.

**Comment by TrapinchO** [comment]
Could you please try this:
1) make a new language
2) add a word "test" (no pronunciation etc., just conlang word)
3) click "Language Statistics"

**Comment by chricker05** [comment]
I had to add the alphabetic order, but I did everything you said. Same issue.

**Comment by TrapinchO** [comment]
Try this:
1) navigate to `C:/Users/<username>/AppData/Local/Temp/`
2) delete everything that starts with `polyglot`
3) create a report
4) see if a new html file was created
4a) if yes, open it

**Comment by DraqueT** [comment]
@TrapinchO
> When I first opened the file I got this error: (didn't get it after reopening and redownloading the file though) ![their_bug_1](https://user-images.githubusercontent.com/67415128/151246055-0c484aeb-f3fe-4dc2-a887-730b140b92f9.png)
> 
> The language statistics report shows to me completely fine.

Could you toss me your error log? I think you might have run into an unrelated bug that I have been trying to track down, but which happens super inconsistently.

**Comment by chricker05** [comment]
It worked! There is indeed an HTML file and my  oh-so-beautiful report. It seems PolyGlot cannot open it for some reason. Strange.

I suppose this will do. Thank you!

**Comment by DraqueT** [comment]
Closing due to resolution of issue.
