### ISSUE TITLE
[suggestion] Word generator: allow separators between letters

### ISSUE THREAD

**Issue by TrapinchO** [DraqueT/PolyGlot#1131]
Grammatical categories get fairly unreadable as more letters are added, since there may not be anything between the letters.

I propose to allow multiple separators, such as space or comma. This would also allow for multiple-character entries, such as long vowels using ipa (`eː`)

**Comment by DraqueT** [comment]
This is definitely a good idea, and something that I think I'm going to implement in the next version. I considered something like it initially, but didn't want to change things up from the original Zompist generator too much, since so many folks are intimately familiar with it.
