### ISSUE TITLE
[BUG] Import from file: instructions are not read-only

### ISSUE THREAD

**Issue by TrapinchO** [DraqueT/PolyGlot#1137]
Polyglot version: Windows BETA 27th January 2022 (latest as of writing this)

Steps to reproduce:
1) click on `Import lexicon from File`
2) click on the instructions field
3) write something

**Comment by DraqueT** [comment]
But how are users supposed to customize functionality without the ability to change the instructions! 

I have no idea how I missed this one for so long, good catch!
