### ISSUE TITLE
Wrong GUI scaling for UHD screens

### ISSUE THREAD

**Issue by selewirre** [DraqueT/PolyGlot#1141]
I just downloaded the Linux .deb file and installed the program with no issue. When I open the program, the GUI is tiny (2-4 times smaller than a regular window would be).

For reference, I am using Ubuntu 20.04.

Here is an image of what I see, compared to my home folder:

![image](https://user-images.githubusercontent.com/93356235/153111440-53910dd5-a706-41e4-a432-a4ff52e3997d.png)

**Comment by DraqueT** [comment]
This is a known bug with newer versions of Java/Ubuntu, but thank you for making an actual ticket for me to keep track with. I am currently looking for solutions. Hopefully the 3.5.1 release (within a week or so) will be able to address this.

**Comment by DraqueT** [comment]
@selewirre Heyo! As a heads up, if you download the newest beta, there is now UI scaling in the options of PolyGlot! It will default to 2 (which is normal sized for most high res Linux rnvironments), but can be scaled up to 4x if necessary. It can be downloaded here:
https://draquet.github.io/PolyGlot/

**Comment by selewirre** [comment]
Hello! Thank you so much for your quick response and actions! I will check
it out as soon as I find some free time :D FYI, I found out about polyglot
from your post on r/conlang about the android version, and I am very
impressed by how far you are taking this. Keep up the good work!
