### ISSUE TITLE
No IPA overlay in the Conjugation table

### ISSUE THREAD

**Issue by TyrrIsNear** [DraqueT/PolyGlot#1142]
I'm not sure if this is a bug, or if the feature was removed, but I remember that I used to be able to view pronunciation of a word form in a conjugation table if I hovered my mouse over it, and in 3.5 I can't.

It would also be nice if you could overwrite pronunciation rules of individual wordforms in a conjugation table, or if superscript/ subscript characters got support in the Phonology & Text tab.

**Comment by DraqueT** [comment]
Thank you for taking the time to make this bug report! 

What you're seeing is absolutely a bug. If you download the latest beta version (lik below), it is corrected. If you want to wait for the next official release of PolyGlot, that should be within a week or so.

https://draquet.github.io/PolyGlot/
