### ISSUE TITLE
[bug] [minor] some sections allow adding new entries even when current one is invalid

### ISSUE THREAD

**Issue by pe1uca** [DraqueT/PolyGlot#1147]
Lexicon section properly disables the add button when the word being edited is invalid.  

Other sections don't disable it.  
This allows to keep inserting empty/invalid elements that are almost invisible in the list.  

- Parts of speech
- Lexical classes
- Logographs
- Phonology (phonemic orthography and romanization)
- Phrasebook (I'm not sure if there's an invalid state for an entry in here)
- Lang properties (alphabetic order)  

For Phonology and alphabetic order, maybe in there are useful to quickly set up and the fill up, since they are in a single scroll, unlike other sections that have a form.  
Also, in these you can easily see the empty entries.

**Comment by DraqueT** [comment]
Fixed this for everything except phonology and alphabetic order. Those should get automatically cleaned up later, regardless.
