### ISSUE TITLE
Imported logographs are not saved

### ISSUE THREAD

**Issue by Kandosii** [DraqueT/PolyGlot#1150]
I've attempted to import PNG and JPG image files through both the Load Image and Clipboard options. The imported files remain in PolyGlot for the remainder of a session, but disappear when PolyGlot is closed and reopened. I've tried this with color images, monochrome images, 100x100 px and 1000x1000 px images, in the PolyGlot directory and elsewhere, testing each with a pair of identical PNG and JPG files. Each time the dictionary file successfully saves. Changes to information on radicals, stroke count, and related words all save correctly, but not the logograph itself.

This error was found on Windows 10, ver. 3.5.1, and has been a persistent problem since before that. Major props on all the hard work you've done on the latest updates though, the program has been far more stable lately.

**Comment by DraqueT** [comment]
Thank you for the heads up here and for all the details! I Just recreated the bug and can track it down now.

Also thank you for the kind words! It always makes me happy when folks are able to get good use out of PolyGlot. :3

**Comment by DraqueT** [comment]
@Kandosii As a heads up, this should be corrected in the latest beta! You can snag it here:
https://draquet.github.io/PolyGlot/
