### ISSUE TITLE
Conjugation Dimension Bug

### ISSUE THREAD

**Issue by cade86love** [DraqueT/PolyGlot#1151]
When I try to add a conjugation, it works fine. When I go to the auto-setup, both conjugations are on the same line. For example, I have a conjugation called "Adverb" and one called "Opposite", but in the auto-setup, it shows "Adverb Opposite"

**Comment by TrapinchO** [comment]
do you mean two conjugations of the same type (e.g. two tenses) or different types (e.g. tense and person)?

**Comment by cade86love** [comment]
different types

**Comment by TrapinchO** [comment]
Are you sure this is not a standard feature of the program? If not, could you please write down the exact steps to reproduce the bug?

http://draquet.github.io/PolyGlot/readme.html#-_Autogeneration_of

**Comment by DraqueT** [comment]
Thanks for fielding this one, @TrapinchO !

I think that is correct. What you're describing is the dimensional feature of PolyGlot. If those two conjugations are mutually exclusive, you might want to either define them as dimensions of a single conjugation form or make them each a non dimensional conjugation.

**Comment by DraqueT** [comment]
Closing this one now, please reply to reopen if you still need additional hel here, @cade86love
