### ISSUE TITLE
Word generator uses only conlang font (bug)

### ISSUE THREAD

**Issue by wanderwitch** [DraqueT/PolyGlot#1157]
DEVELOPER TEXT
In the word generator, the Categories text box and Syllable Types text box should use local lang fonts rather than conlang fonts.

ORIGINAL TEXT
Word generator uses only the conlang where it should use the local lang
![image](https://user-images.githubusercontent.com/40308373/158042486-b8797d7e-1042-49bf-971e-7257f83fc1e2.png)

**Comment by DraqueT** [comment]
After thinking about this hard, I realized this was not a bug, but a missing feature. Closing this, but opening the following ticket:

https://github.com/DraqueT/PolyGlot/issues/1312
