### ISSUE TITLE
Image loading error: zip END header not found. can't access my work at all

### ISSUE THREAD

**Issue by justfilingabugreport** [DraqueT/PolyGlot#1159]
![Screenshot 2022-03-17 142419](https://user-images.githubusercontent.com/101782284/158731321-26467689-029d-4254-90d2-e6c6ad72f494.png)

Hi, tried to open my language file to get some work done on it and got this error message. I can't access my language at all. The pgd file is still in the Polyglot folder.

I haven't opened this file for a few weeks but it was always fine. Today when I opened it, I got that error message, then a message saying something like an unsaved version of the language could be recovered. I thought maybe I'd forgotten to save the file last time I used it, so I clicked OK. Then it opened a completely blank file as if a brand new document. Now every time I try to open the language file, I get the same error message and blank document opening.

I am using the latest update of Windows 10 (updated last night). I'm not sure if you need my computer specs or not.

**Comment by DraqueT** [comment]
Could you please send a copy of the pgd file to me so I can take a look at it? I'll see whether I can't extract something from it and try to get you back where you need to be there. My email is draquemail@gmail.com

Also, when you started PolyGlot up, did you get any kind of file recovery message? I've tried to make PolyGlot as safe as possible in terms of backing things up before saving, creating redundant archives if there are problems etc.

**Comment by RockOfStone** [comment]
Hi, I just started using Polyglot, I had the same error occur.
I was able to recover the file by extracting the archive using 7-zip and, in the PGDictionary.xml file removing some corrupted XML at the end of the file that looked like this:
`<ord>damGuidToDdeProGude>iGuide><proGuide><proGuide><proGuideBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBasaBa`
And replacing it with (using an uncorrupted save as a guide):
`<phraseBookCollection/><thesNode/></dictionary>`

**Comment by DraqueT** [comment]
Thank you for reporting this, I want to find this bug and correct it asap. Could you please send me the corrupted file? Also, do you happen to have an u corrupted backup of your file?

Sorry that this bug is hitting you, I'll definitely do everything I can to help recover.

**Comment by DraqueT** [comment]
(My email is draquemail@gmail.com btw)

**Comment by DraqueT** [comment]
The only thing I can figure that happened is that after the file was written and tested, something interrupted copying it from its temp location to the final destination. For reference here are the steps I have changed:

ORIGINAL STEPS:
1) save to temp location
2) load and make sure that file does not cause errors when read
3) copy temp file over original file (this is where the problem ,ust have occurred)

NEW STEPS:
1) Save file to temp location
2) Copy temp file to save directory
3) load and make sure that file does not cause errors when read
4) Compare contents of file to contents of memory to make certain they are identical
5) delete original file
6) rename temp file with name of original file

Again, I am really sorry that data was lost here, and I hope that the new set of steps prevent it from happening in the future. I'm building a new beta version now and will post here again once it's available (very shortly).

**Comment by DraqueT** [comment]
Build should be up over at https://draquet.github.io/PolyGlot/

**Comment by DraqueT** [comment]
@RockOfStone @justfilingabugreport 
Build is up at https://draquet.github.io/PolyGlot/

**Comment by justfilingabugreport** [comment]
Thank you!




Monday, 4 April 2022, 10:35 am +1000 from ***@***.***  ***@***.***>:
***@***.*** @justfilingabugreport
