### ISSUE TITLE
[Bug] Evolve Language replacement field

### ISSUE THREAD

**Issue by Tony2987** [DraqueT/PolyGlot#1161]
Evolve Language replacement field is not interpretating regex, instead outputs regex commands as characters.

Example: 
Target pattern: [aeiou]t[aeiou]
Replacement: .d.

Expected result:
ato -> ado
atro -> atro

Actual result:
ato -> .d.
atro -> atro

PolyGlot ver. 3.5.1 Build Date: 2022-02-19 23:34 Windows version.

**Comment by DraqueT** [comment]
Thank you for reporting this! I'll give it a look as soon as I'm able and link you to a beta where it's corrected as soon as it exists.

**Comment by Tony2987** [comment]
Just as a heads up, the main issue in my example was an improper regex for detection. However, I still couldn't make regex work on the replacement. I suppose this could still be my incompetence, but I think it's worth taking a look.

**Comment by DraqueT** [comment]
Heyo! I found the issue! What you're looking to do here requires a tricky regex pattern. Here's what the pattern and replacement should look like:

Pattern: (?<=[aeiou])t(?=[aeiou])
Replacement: d

The pattern uses lookahead and lookbehind to match text based on what comes before and after, but does not match those before and after values themselves (so they are not replaced). Hope this helps! I'm closing the ticket, but feel free to open again if you have more trouble. :3
