### ISSUE TITLE
[Bug]Revert language not working, mangles file instead

### ISSUE THREAD

**Issue by Tony2987** [DraqueT/PolyGlot#1163]
Revert language functionality not only does not work, but it creates copies of multiple things within the file. I've noticed multiple copies of contents in word generation, the name of the language (in Lang Properties), and grammar section, this one generating phantom sections of previous content.

PolyGlot ver. 3.5.1 Build Date: 2022-02-19 23:34 windows version

**Comment by DraqueT** [comment]
Thank you for reporting this and sorry for the long response here. I think I have reproduced the bug, and once it is fixed, I will link you to a beta version that works prioperly.

**Comment by DraqueT** [comment]
As a heads up, the ;latest betas should have this problem corrected, @Tony2987! Please check it out and let me know if the problem persists. (Also, if you download the mac version, you will need to have an M1 mac. This is temporary, and there will soon be builds for both M1 and Intel macs).

https://draquet.github.io/PolyGlot/
