### ISSUE TITLE
[bug] can't resize

### ISSUE THREAD

**Issue by defsiarte** [DraqueT/PolyGlot#1180]
just downloaded the newest update last night, I previously had 3.3.1(?) and now I'm unable to properly resize windows or scroll down to see the full body of a page. this means that for some sections, like word generation and alphabetical order, I can't edit anything.

**Comment by DraqueT** [comment]
Thanks for taking the time to write up a bug report! Sorry to hear that you're having some problems, but I'll try to help out!

Is it specifically the main window that will not allow you to resize? If so, that is a new bug. The first thing I would suggest there is installing the latest beta. The current builds are nice and stable, and they do address some resizing issues that a number of windows had. You can find that at the link below. If it still gives you trouble, just toss another mesage over here and we'll continue from there. :3

**Comment by DraqueT** [comment]
Heyo! Since I haven't heard back from you in two weeks I'm going to presume that installing the beta corrected your problems and close this. If you're still experiencing the issue just reply and we can reopen the ticket.
