### ISSUE TITLE
[suggestion] (& maybe [bug]) resizing 

### ISSUE THREAD

**Issue by SpartanCreeper** [DraqueT/PolyGlot#1181]
if i dont have polyglot full screen, i cant access for example quiz generator, itd be nice if i could scroll down, itd resize automatically, or that i can resize it myself (with ctrl+scroll) and scrolling down & up
![image](https://user-images.githubusercontent.com/65303062/170876303-11a93a32-cfdb-4f19-a632-ee1c47a78c45.png)

**Comment by TrapinchO** [comment]
try this:
tools -> options ->ui scaling -> set to 1

**Comment by DraqueT** [comment]
Closing ticket for housekeeping. Feel free to reopen if it's still an issue.
