### ISSUE TITLE
Bug Report: Word Generator

### ISSUE THREAD

**Issue by kreese8** [DraqueT/PolyGlot#1182]
The word generator clearly has a lower part of the page associated with it but I can't scroll down and no attempts can make it visible. This is on the Windows version of the app.

**Comment by TrapinchO** [comment]
have you tried resizing the window or chaning the scale? the latter should be in the settings.

**Comment by kreese8** [comment]
Changing the scale of the window worked. I do think it would be more convenient to scroll though, since decreasing the size makes everything much more difficult to read (I have to put the UI Scaling to 1 and due to poor vision have a hard time seeing everything). Of course if this is a lot of effort I understand not implementing the feature, it's just a nice-to-have.
![UI Scaling 1](https://user-images.githubusercontent.com/78920355/172908159-b8a40207-2b09-42f4-a305-c988f5dca1bf.png)
![UI scaling 2](https://user-images.githubusercontent.com/78920355/172908164-d4c5cd92-a913-4e61-bdc9-2ad92bcfda03.png)
)

**Comment by SpartanCreeper** [comment]
yeah i also had this problem, but now i can resize it, still, being able to scroll would be amazing

**Comment by DraqueT** [comment]
I'm closing this, as another ticket addressed the issue. The window is now scrollable in the newest beta and will be in future releases as well.
