### ISSUE TITLE
Window unmaximizing when entering lexicon (Windows only, not Mac or Linux)

### ISSUE THREAD

**Issue by duck1808** [DraqueT/PolyGlot#1184]
Whenever I go into the lexicon while the window is maximized, it gets turned into a floating window, and the same happens when clicking any options inside of the lexicon area. This does not happen with any of the other tabs.

**Comment by DraqueT** [comment]
Thanks for making a ticket of this! I knew exactly why this is happening and can absolutely get this behavior corrected.
