### ISSUE TITLE
Bug report: Phrasebook

### ISSUE THREAD

**Issue by Davidemonaco** [DraqueT/PolyGlot#1189]
DEV NOTES:
Something is causing the CSS parser to explode whenever the font from this file is loaded... it seems to register that there is a missing ' character somewhere very far downstream in the guts of Swing stuff.

ORIGINAL TEXT
The phrasebook will open on an empty project, but whenever i try to open it on my conlang project i've been working on, it won't open up, even when i try to pop the window out.
![Polyglot](https://user-images.githubusercontent.com/91208307/178103970-853386f6-054a-42ab-a1b9-a930ea4f8616.gif)

**Comment by Davidemonaco** [comment]
Emailed it

**Comment by DraqueT** [comment]
Just letting you know I haven't forgotten about this one. It's a doozy, though. For some reason, it is freaking out over the font you are using. Java is notoriously picky with Fonts, but I am looking into it now. What did you create your font with?

**Comment by DraqueT** [comment]
Your font unfortunately has some issues that are choking PolyGlot. I downloaded FontForge (which is free!) to analyze it, and it found some issues, including mismatched single quote characters (this is what PolyGlot choked on). I would suggest snagging the tool and going over your font to resolve the issues. 

I hope this helps! :)
