### ISSUE TITLE
Not Removing Transparent Text

### ISSUE THREAD

**Issue by chaver1** [DraqueT/PolyGlot#1200]
![image](https://user-images.githubusercontent.com/24521246/181772005-b858ffa8-3199-48ca-8e5d-a5207b754030.png)
 
This is a rather small issue since its mostly aesthetic, but I figured I would mention it. It seems that for me, the field text does not disappear when I put in my own entry.

**Comment by DraqueT** [comment]
This is one of those actual situations where the reported bug was legitimately intended as a feature. Notice that the transparent text never overlaps with the user text, no matter the width. 

Ultimately I made it this way so as to avoid having to place labels next to fields. If it's confusing users though, it might be something I end up changing. You have any thoughts there?

**Comment by DraqueT** [comment]
Closing this for now, but please feel free to reply here if you would like to discuss.
