### ISSUE TITLE
[BETA] "Cannot invoke HTML$Tag.toString" on startup

### ISSUE THREAD

**Issue by TrapinchO** [DraqueT/PolyGlot#1204]
Polyglot version: Windows BETA from 7th August 2022 (latest as of writing this)

Steps to reproduce:
Unknown, got it while trying to fix a polyglot file broken due to #1195.

![img3](https://user-images.githubusercontent.com/67415128/184604505-034f6476-5833-4114-8fd7-13a38c7f990b.png)

Error log:
None, searched the error log and found nothing.

**Comment by DraqueT** [comment]
Experimented extensively to reproduce.I am 90% sure this was addressed with #, so I am closing unless this pops up again.
