### ISSUE TITLE
"Download for Linux" is misleading

### ISSUE THREAD

**Issue by KSPAtlas** [DraqueT/PolyGlot#1207]
On the page, it says "Download for Linux", yet it downloads a .deb file, which is specifically for Debian Linux and derivatives (Ubuntu, etc). This button should either say "Download for Debian" or PolyGlot should be packaged as an AppImage (an actual universal way to install apps on Linux, used by Balena Etcher and others)

**Comment by ikeman32** [comment]
Deb files can be converted to AppImage quite easily. https://appimage.github.io/deb2appimage/

**Comment by DraqueT** [comment]
@ikeman32 Thanks for posting this solution! I'm adding a link to this app in the Linux Install section of documentation for those that it affects.
