### ISSUE TITLE
Logographs' images disappearing when software is closed

### ISSUE THREAD

**Issue by Guidder** [DraqueT/PolyGlot#1208]
Hello! I'm new to the software and have been having what I believe to be an issue. I'm working on a conlang that has a logographic script and have been trying to make a dictionary on PolyGlot, but every time I close it, the images I loaded just disappear. When I open it again, the images are just gone.
I tried to load the images from a directory, paste them from the clipboard, put them at the same folder as the .pgd file, repairing the software via installer... Nothing worked so far.

Am I doing something wrong?

**Comment by DraqueT** [comment]
Thanks for reporting this bug! Could you please send me a copy of the language file that is giving you this trouble? I have not been able to reproduce the bug on my side, and I am wondering whether there is some edge case that I have missed which is making the bug pop for you.

**Comment by DraqueT** [comment]
You can send a copy of the language file to draquemail@gmail.com by the way, I should have said.

**Comment by DraqueT** [comment]
I have not been able to reproduce this error, and am closing it for now. Please feel free to reopen it if you're still experiencing trouble or could provide me some examples of this behavior. Thanks! @Guidder
