### ISSUE TITLE
Allow continuous size scaling in options

### ISSUE THREAD

**Issue by dasukocho** [DraqueT/PolyGlot#1214]
DEV NOTES: Allow scaling based on fractional values rather than just whole numbers.

ORIGINAL TEXT:

At a scale of 1, it's too small, at a scale of 2, it becomes so big that I can't use some of the features because they're all locked in place and there's no way to scroll down when this happens. Using a Samsung laptop.
![Screenshot 2022-09-28 212639](https://user-images.githubusercontent.com/42304368/192938757-335c5e84-8b73-46a4-a4fa-ac80871cfbb8.png)

**Comment by DraqueT** [comment]
Good suggestion here, I am implementing something that lets you scale with more granularity!

**Comment by DraqueT** [comment]
As a heads up, this is integrated into the latest betas if you want to swing over to the homepage to snag it. :3

https://draquet.github.io/PolyGlot/
