### ISSUE TITLE
[BETA] Editing a file and closing it without doing anything else does not show prompt or save

### ISSUE THREAD

**Issue by TrapinchO** [DraqueT/PolyGlot#1216]
Polyglot version: Windows BETA from 30th September 2022 (latest as of writing this)

Steps to reproduce:
1) open a file
2) make a change (e.g. create/change a word)
3) exit the program (the prompt should not appear)

I am unsure what exactly prompts this. Some stuff (like changing a word or adding definition) seems to show the prompt only if something else is done (like switching to another word), while other are time-dependent (adding a word).

**Comment by DraqueT** [comment]
I anticipated this being a bit fiddly. It takes a snapshot of the language on load, then compares what's in memory to that when going to close. In cases like opening and editing a single word then closing, the change hasn't been persisted back to the actual language model yet.

Ih actual use, I feel like this won't come up much... but it's definitely something that I should address.
