### ISSUE TITLE
Some windows are too big for my screen and can't be resized

### ISSUE THREAD

**Issue by BStafanskie** [DraqueT/PolyGlot#1217]
I can't publish to PDF without switching my entire computer screen to portrait mode. The word generator is also too large and can't be shortened or scrolled down.

**Comment by DraqueT** [comment]
Heyo! Please try downloading the newest beta version. In this version, you can set the scaling of PolyGlot to decimal values and all windows are resizable, so this should no longer be an issue. You can find the beta here:

https://draquet.github.io/PolyGlot/
