### ISSUE TITLE
Can't switch keyboard layout within the program

### ISSUE THREAD

**Issue by ableunable** [DraqueT/PolyGlot#1218]
I am working on a conlang which will be written in Cyrillic characters. I thought this program would be very helpful for the development. However, I can't seem to switch the keyboard layout within the program; if I switch it outside the program, the program doesn't recognise it.

I am using PolyGlot 3.5.1 on Arch Linux, and for keyboard layouts, I use fcitx.   
* The fcitx icon in the status tray doesn't change when I try to switch the layout within the program, indicating no layout change has occurred, and indeed, no change has occurred.    
* When I switch it outside the program, it does change, but when I change focus back to the program, the icon changes back, indicating the layout has changed back too, and indeed it does change back.

This results in an inability to directly input any other characters than those in my Latin layout, and I have to resort to copy-pasting from another program.   
I can also circumvent this by putting the Cyrillic layout first in the list in fcitx config, but as I use the i3 window manager, which relies on keyboard shortcuts, I can't use most shortcuts because the keyboard would be inputting Cyrillic characters by default (I have tried this already).

I think I can invent a Latin equivalent for the Cyrillic alphabet of the conlang, for use with the program in its current state; but I would really prefer to be able to directly input the same characters as I input elsewhere.

**Comment by ableunable** [comment]
Update: I used the Character Replacement functionality within Phonology & Text, to map certain Latin characters to Cyrillic ones. This greatly eases the input of the Cyrillic characters to the program. But the issue with layout switching still stands.

**Comment by ableunable** [comment]
There are other programs for the layout, yes, but if it's an issue with Arch specifically, I'm not sure if switching to a different program would be helpful - it's too much work at this moment for one program that doesn't cooperate well with fcitx.

If this is a Java problem rather than a PolyGlot problem, I guess it's safe to close this issue? I'll leave that up to you if you decide so.

**Comment by DraqueT** [comment]
Sorry for the long silence here (real life). It unfortunately seems like this is 100% a Java interaction with OSes. There's not a lot I can do here short of writing something custom. Fingers crossed that Java and Arch get along better in the future, but I think I'm going to have to close the ticket, as a custom solution is just out of scope.
