### ISSUE TITLE
PolyGlot-Ins-Win.exe doesn't finish installing (Windows 10)

### ISSUE THREAD

**Issue by VoloTeX** [DraqueT/PolyGlot#1219]
'PolyGlot Setup Wizard ended prematurely because of an error. Your system has not been modified. To install this program at a later time, run Setup Wizard again. Click the Finish button to exit the Setup Wizard.' 

No matter what I try, this issue occurs every time. The version of PolyGlot doesn't matter.

**Comment by VoloTeX** [comment]
It works now! For some reason, Windows hasn't been updating the .net framework on my system for quite some time. 
Which is odd given how recent the last update was. I will definitely have to look deeper into it if it happens again.

 But, for now, I can finally get back to conlanging! Thanks for the help. I'm excited to see how helpful PolyGlot can be.

**Comment by DraqueT** [comment]
Thank you for the heads up! I have actually getting more reports of this and am thinking that I might upgrade the installation client used with the Windows version. 

-Draque
