### ISSUE TITLE
[bug] polyglot fails to start after error message 'unable to load options file or file corrupted: For input string: "1.0"'

### ISSUE THREAD

**Issue by rcochrane55** [DraqueT/PolyGlot#1220]
After going back to 3.5.1 from the 3.6 beta, the recently installed 3.5.1 build fails to launch after the above error message followed by a "Failed to launch JVM" error message. I am unable to repair the install and can find find no obvious cause after several reinstalls.

**Comment by rcochrane55** [comment]
Update on this: I edited the line "UiScale=1.0" in PolyGlot.ini to "UiScale=1" and that fixed the issue.

**Comment by DraqueT** [comment]
Thank you for the heads up on the workaround, and sorry for the long response time! Things have been a bit nuts on my end here. Fix for this incoming to beta.
