### ISSUE TITLE
Web accessible API interface

### ISSUE THREAD

**Issue by Siynth** [DraqueT/PolyGlot#1223]
**DEVELOPER TEXT**
Create an endpoint which accepts web requests. It must be able to provide the following on request:
- The XML language file
- picture assets by ID
- sound assets by ID
- Font binaries

**ORIGINAL TEXT**
A web app that is run on the local machine, it would be accessed via google chrome, firefox, etc.
Possible port listening?

It would allow for access from local and external networks while all the data is stored on the local machine running the server.

Maybe a docker version?

**Comment by DraqueT** [comment]
Hrm, this is an interesting idea. Ultimately languages are stored in an XML document. It wouldn't be difficult to serve that up on request, and that would get you 99% of everything you need. It could also offer things like the language fonts, images, and sound files without too much work.

Is that along the lines of what you were thinking of?

**Comment by Siynth** [comment]
Yea, sorry for getting back to this so late. That is along the lines of what I am talking about.
