### ISSUE TITLE
New declensions can't be created (bug)

### ISSUE THREAD

**Issue by Mymokol** [DraqueT/PolyGlot#1225]
In my project, I found that I'm unable to create new declensions in the Part of Speech section. I'm unsure as to what lead to this or how to reproduce the bug, sadly.

When I click + button in the Conjugations/Declensions Setup screen in the left column, the window saying it will deprecate all existing declensions appears, and when I click Yes, it doesn't create a new declension, if I'd already set up autogeneration for the existing declensions in that Part of Speech. That is, for example, if I have a verb PoS, and have already set up some autogen rules for them, the Conj./Decl. Setup screen won't let me make any new Declensions. 

What's noteworthy is that this only occurs in one project of mine. I tried copying the project and saving it as a new one, but the error still persisted. When I made a new project just to test out the bug, I couldn't reproduce it.

Here are some screenshots of the actions taken in the problematic project, in order:

![image](https://user-images.githubusercontent.com/62548556/208453349-c601a28d-f75d-4a45-b330-7c7695147ce7.png)
(clicked + in the bottom left)
![image](https://user-images.githubusercontent.com/62548556/208458521-b3d2199a-87ea-4b2a-932e-b49406fd2ca1.png)
(clicked Yes)
![image](https://user-images.githubusercontent.com/62548556/208458604-5016b024-dea8-4c8b-9a85-eb20cc72daec.png)

**Comment by DraqueT** [comment]
Thank you for the detailed writeup! Could you please post the language file here or send me a copy at draquemail@gmail.com?

**Comment by Mymokol** [comment]
Sure! I'm sending it to the email.
