### ISSUE TITLE
Replace CustHandler process for loading language xml

### ISSUE THREAD

**Issue by DraqueT** [DraqueT/PolyGlot#1226]
This is a bad system overall. It should be replaced with one that simply walks the nodes and adds values as is necessary/reasonable. It will increase stability and reliability of PolyGlot (and eliminate the issue with deleting spaces before special characters).

**Comment by pe1uca** [comment]
Just to confirm, this means changing from using `org.xml.sax.helpers.DefaultHandler` reading characters to using the methods of [org.w3c.dom.Node](https://docs.oracle.com/javase/7/docs/api/org/w3c/dom/Node.html) to get child elements and values, correct?

**Comment by DraqueT** [comment]
Sorry to miss this comment for an extended period! But yes, that is correct. Working on it atm.

**Comment by pe1uca** [comment]
No problem!  

> Working on it atm  

Oh, so should we discard the PR #1232 ?  
There's no need to do double work.
