### ISSUE TITLE
Prevent corrupted/unreadable images from stopping language file load

### ISSUE THREAD

**Issue by rcochrane55** [DraqueT/PolyGlot#1228]
DEVELOPER NOTES:
Edit loadImageAssets within DesktopIOHandler. There is an inner try with resources block with no catch. Create a catch here that records warnings of files it is unable to load. Update the code to somehow return these warnings to display to the user, but DO NOT prevent the user from loading the file.

Likewise, inspect other loaders for things like sound files. Make sure that so long as the XML file can be read, the user is able to access their file (with notifications to anything that might be corrupt).

ORIGINAL TEXT:
Hi, wish I wasn't bringing this here, but I can't seem to access my language file anymore. I started up polyglot and it told me it shut down incorrectly in an error message (last thing I remember doing was saving and quitting) and asked if I wanted to recover the latest stable autosave. I did that, and now I cannot open my language file, with it showing me this error message when I try.
![image loading error polyglot](https://user-images.githubusercontent.com/67019264/209444631-95cb5ced-bbc4-44ad-963b-8bb5d0388b70.png)

Please, please tell me there is a way to fix this and access my file again. I've tried restarting my PC and I've tried reinstalling polyglot, neither of which fixed it. Is there an alternate way that I can open and modify the file to fix whatever is preventing it from loading?

**Comment by DraqueT** [comment]
Heyo! Please send me the file at draqueemail@gmail.con and I will take a look. Polyglot shouldn't refuse to open a file even if there is a problem with some of the contents. 

I think your file is probably recoverable, and I will make the error checking less of a blocker moving forward.

**Comment by rcochrane55** [comment]
Unfortunately, I think the corrupted file may have been overwritten. I don't think it's recoverable at this point as it will open now but it's just an empty file. I will still send it to you but I am not hopeful. That being said, I found an older version that I emailed to myself, and I have some excel and PDF backups that should allow me to restore what I lost.

**Comment by DraqueT** [comment]
There's till a good chance that it is recoverable. PolyGlot saves many prior versions of the XML that can be reverted to. 

Can I ask exactly how it was overwritten? I would like to make something which prevents overwrites like that from taking place.

**Comment by rcochrane55** [comment]
Something that could be done to compensate for this problem until it's fixed is to make the import from excel function as powerful and thorough as the export function. If polyglot was able to import everything it can export, then the natural fix for my problem would be to just load everything from my excel file back into polyglot. But as far as I can tell it's not possible to import pronunciations, parts of speech, or conjugations/declensions.
