### ISSUE TITLE
Conjugation/declension manual entry: switching tabs deletes text

### ISSUE THREAD

**Issue by bagoker** [DraqueT/PolyGlot#1230]
Running PolyGlot 3.5.1 on macOS Ventura 13.1.

In a new project I've created a multidimensional conjugation/declension paradigm (picture 1). This includes a two-dimensional table with plenty of tabs to switch through. A bug arises when I enter text manually: if I navigate to any given tab with empty cells and enter text in a new cell (picture 2), when I switch to another tab after entering the text, it forcibly opens the dropdown for table dimensions (picture 3), then on closing the dropdown returns me to the tab which opens by default (as in picture 1). When I navigate back to the tab I entered the new text on, the text I entered disappears, and the dropdown keeps opening without clicking it (picture 4). The only way for this not to happen is by pressing OK in the dialog box to save the manually entered data before switching tabs. I hope you folks can figure out why this is and let me know if there's anything I need to do! 
 
<img width="869" alt="image" src="https://user-images.githubusercontent.com/43776621/209736682-475960e1-5ea6-42a4-9f50-6c094cf4175b.png">
<img width="869" alt="image" src="https://user-images.githubusercontent.com/43776621/209736774-2558801e-87b3-4e6c-b2e6-04076ec61ea5.png">
<img width="857" alt="image" src="https://user-images.githubusercontent.com/43776621/209736825-93a22656-a353-45fe-8456-7f4bf5d1bea0.png">
<img width="864" alt="image" src="https://user-images.githubusercontent.com/43776621/209736886-bb7e7ff6-2a6f-46d9-9a8e-a28113ea29ae.png">

**Comment by DraqueT** [comment]
Thank you for documenting this so well! This is a bug I was unaware of and am looking for a fix atm. When it is corrected, I'll post a link to where you can download the beta which corrects it.
