### ISSUE TITLE
screen size problem

### ISSUE THREAD

**Issue by ourora5** [DraqueT/PolyGlot#1231]
i had UI(i am not sure what it is ...)\screen size problem so i tried to fix it through option in the tools i couldn't figure out how to do it and by mistake i set UI on 4 and closed the program the next day when i oped it the panel became so big that i could only open the tools help and files , i wanted to fix it but i didn't have access to option because the tools bar became so big that couldn't reach the end i even tried re-installing but it was still like that .
how should i fix this screen size ? is there any way to turn the settings back to default ?
![Screenshot (1)](https://user-images.githubusercontent.com/121747972/210165947-116b45c8-246d-484c-8e92-ea8db96e6e62.png)

**Comment by TrapinchO** [comment]
If you are on windows, go to `C:\Users\<name>\Polyglot`, open `Polyglot.ini` and at the bottom set `UiScale` to `1`. Also, use the beta version, it should have this bug fixed.

**Comment by ourora5** [comment]
thank you

**Comment by TrapinchO** [comment]
no problem
