### ISSUE TITLE
Error message appearing everytime I try to open my conlang

### ISSUE THREAD

**Issue by CraftFe** [DraqueT/PolyGlot#1240]
![image](https://user-images.githubusercontent.com/74438649/215266049-3bbdb686-6542-49b1-aeb0-462fa9c494fb.png)
Everytime I try to open my conlang, this error message appears. If I click "OK", it opens a blank language, as when we create a new one.
This started happening about an hour ago, when the power went out for some seconds in my house and my computer turn off, with Polyglot open in my conlang. I can't remember but i think I also had Lodenkur open in Polyglot, since I was trying to remember the main elements I had to put into my grammar.
I was already noticing some error messages every time it tried to auto-save, but I was OK with that since I could normally save it manually.
What should I do?

This document was in the folder with the language I'm trying to open, I don't know if it is related.
[PolyGlot_error.log](https://github.com/DraqueT/PolyGlot/files/10527241/PolyGlot_error.log)

**Comment by DraqueT** [comment]
Heyo! I have two suggestions here.

1) Download the newest beta version of PolyGlot and try opening it with that: https://draquet.github.io/PolyGlot/
2) Send me the language file (draquemail@gmail.com) and I will see what I can do. 

There is an annoying bug in the current version that can sometimes fail to add a closing tag to the end of a word, but the new beta can account for that and read the file regardless.

**Comment by DraqueT** [comment]
I am closing this ticket, as I believe that it has been resolved in the current beta. If you're using the current beta and still experience the problem please feel free to reopen this!
