### ISSUE TITLE
Logograph Errors

### ISSUE THREAD

**Issue by cade86love** [DraqueT/PolyGlot#1242]
Hello, I am having trouble with logographs. 

When I copy from clipboard, I save the file, but when I re-open the project, the logograph data is there, but the photo is gone. 

I am also having trouble when creating a logograph. When I create a logograph and assign it to a word, I go back to the lexicon and click on the word, but there is no associated logograph, and I am unable to add one.

**Comment by DraqueT** [comment]
Thank you for the bug report! When this is corrected I'll link you to the appropriate beta build.

**Comment by DraqueT** [comment]
As a heads up, if you downlod the newest beta, this should be fixed! 

https://draquet.github.io/PolyGlot/
