### ISSUE TITLE
Can't add new conjugations/declensions on Noun. 

### ISSUE THREAD

**Issue by tetraminus** [DraqueT/PolyGlot#1249]
I'm having a very similar problem to #1225 where after going through the dialogue boxes, the new entry will not appear. I was able to get around the issue by copy pasting one from another part of speech, but this is still really annoying to deal with. the other copies of this issue do not seem to have a solution.

**Comment by DraqueT** [comment]
Could you please send a copy of the language file to draquemail@gmail.com? I will take a look and see if there is some edge case that code is missing here.

**Comment by DraqueT** [comment]
If this is still giving you trouble, please let me know. Also, you might try downlioading the newest beta. If this bug is related to the one that you linked, that update might have corrected it.

https://draquet.github.io/PolyGlot/

**Comment by DraqueT** [comment]
I am closing this as I have heard no response. If it is still giving you trouble, please feel free to reopen.
