### ISSUE TITLE
UI issues on Linux

### ISSUE THREAD

**Issue by ashprice** [DraqueT/PolyGlot#1250]
DEV TEXT:
This seems to be a problem specific to DWM. 

ORIGINAL TEXT:
Hello, 
I'm having a few issues with the UI:

- UI cannot be dynamically scaled (with mouse, with ctrl + +/-) - I suppose this is an implemented feature, but maybe I am wrong...?
- All top-bar items do not work properly: Clicking on `file` brings up the menu, it immediately closes, meaning you can't click on anything. All options except Recent are grayed out. Clicking on `Tools` brings up nothing. Clicking on `Help` shows the same behaviour as `File`; all options except Example Languages are grayed out, and you cannot click that one. Keybindings for saving, opening, etc. seem to work fine.

Attached is an error log. 
[PolyGlot_error.log](https://github.com/DraqueT/PolyGlot/files/10728717/PolyGlot_error.log)

Kernel: 6.1.10-arch1-1
Desktop environment/WM: DWM (the issues persist on current xfce4 desktop)
JRE version: 19.0.2.u7-2

Let me know if there's any other info I can provide!

**Comment by DraqueT** [comment]
Thank you for such a complete error report! I am working atm to bring out a pretty large update to PolyGlot, and I absolutely want to hit these bugs in the next release!

Ctrl +/- will unfortunately not be something which implements real time scaling of the program, as that feature relies on the JVM, which needs to restart for them to take effect. When sliding the scaling bar (under the options menu), PolyGlot should give the message that a restart is required before it will take effect.

**Comment by ashprice** [comment]
No problem!

The scaling is less of an issue given the scaling bar! Though, I don't think I got such a popup message. I can't really confirm because I can't access the settings page! (Maybe there is a keybind, will look in the documentation in a while.) It's basically at a zoom level that I'd be happy to use right now; I'm aware I can change it manually by editing a file. 

Actually, one issue I didn't mention, that is possibly related to the scaling, is that if I fullscreen PolyGlot in DWM it only takes up maybe the top left 3/5ths of the monitor. 

![2023-02-20-173019_2560x1440_scrot](https://user-images.githubusercontent.com/48685381/220170218-fa1e4dd8-1c36-49c6-880e-475a400b83d7.png)

This is plausibly weirdness due to me using DWM (which would probably mean it isn't a priority), but there's a chance it is not, so I thought I'd mention it. 

Additionally, no matter whether I am full-screen or not, elements at the bottom of the screen are cut off, and I cannot scroll down. 

![2023-02-20-173246_2560x1440_scrot](https://user-images.githubusercontent.com/48685381/220170831-3acf2c25-fd1f-4911-bdd5-9c1bd9e9d662.png)

**Comment by DraqueT** [comment]
This unfortunately seems to be an issue with DWM specifically. I'm going to leave this ticket open and may eventually get back to it, but it might be a bit, since it's such a specific thing, and I will need to set up a new environment to test for it.

Again, thank you for taking the time to make such detailed writeups!

**Comment by DraqueT** [comment]
Also, are you not able to get to the options menu at all? It's under Tools->Options

**Comment by DraqueT** [comment]
I am closing this issue for bookkeeping, but if you would like to continue the conversation or have more details, please feel free to reopen.
