### ISSUE TITLE
Screen size

### ISSUE THREAD

**Issue by NicolasUrana** [DraqueT/PolyGlot#1251]
Hello,

My polyglot window is very zoomed, impossible for me to scroll up or down or to go left and right (picture attached). Can anyone help me change this setting ? 

Thanks in advance.
![Capture](https://user-images.githubusercontent.com/125467195/219032852-149ffe3a-645b-4635-8aca-b5b7520a57bf.PNG)

**Comment by DraqueT** [comment]
If you go to tools->options, you'll be able to change the scaling. After doing so, you'll need to restart PolyGlot to see the changes. Please let me know if this helps! :3

**Comment by NicolasUrana** [comment]
It worked ! Thank you very much ^o^ !
