### ISSUE TITLE
Unable to scroll in word generator

### ISSUE THREAD

**Issue by kozi05** [DraqueT/PolyGlot#1258]
Hello,

I booted up PolyGlot today and found myself unable to scroll anywhere in the Word Generator tab, although everywhere worked fine. I've fiddled with the size settings, restarted the software, and even restarted and update my computer. Nothing helped. Any ideas for how to troubleshoot? Thanks!

**Comment by DraqueT** [comment]
Please download the newest beta linked below. This is a known bug, and corrected in the beta.

Thank you for taking the time to write an error report! These are great to help me find and correct bugs. ^^

https://draquet.github.io/PolyGlot/

**Comment by DraqueT** [comment]
I am closing this, if the beta did not solve your problem please feel free to reopen.
