### ISSUE TITLE
Opened Polyglot and my save file was set back to last year, deleting all my work

### ISSUE THREAD

**Issue by IgnisElements** [DraqueT/PolyGlot#1261]
I closed my save file for my conlang I was making yesterday. I opened polyglot today to reveal that all my save files had been set back to last year, resulting in all of my conlang's work being lost

**Comment by DraqueT** [comment]
Heyo, I will do my best to help you recover data here! My first question is whether this affected a single file or multiple files all in one go. If it is a single file, then please do not modify/save it, but send a copy to me and I will see if I can figure out what happened with it.

If it was multiple files all at once, then it is likely that there is a culprit other than PolyGlot. While it is possible that something odd happened when saving a single file, there is no feature in PolyGlot which reads and saves multiple files at once. If it is this case, where are the files being stored? Is it possible that some kind of reversion happened to the folder they were in that might have set all of them backward at once?

My email is draquemail@gmail.com, please feel free to send any relevant files there and I can take a look.

**Comment by IgnisElements** [comment]
hi! sorry if I responded late. but for some reason it affected all my conlang files, setting them back to different times in the last year. They were all being stored in the polyglot folder that is created when you first install polyglot.  I'm not sure if it something to do with my computer or polyglot, but I know that prior to saving the conlang before the data disappearing, there was a warning of some sort. Said something along the lines of the file didn't save correctly when trying to autosave, when i saved manually there were no problems so maybe it was that?

**Comment by DraqueT** [comment]
Could you please send me one of the affected files? If nothing else, I will be able to pin down whether it was PolyGlot that did this or if it's another program that was responsible. Part of me wonders if there was some kind of backup/versioning issue with the entire folder. The reason I suspect this is that PolyGlot only reads/writes one file at a time, so I do not understand how it would have affected an entire folder like that. My email is draquemail@gmail.com if you want to toss it over there.

**Comment by DraqueT** [comment]
I am closing this for bookkeeping, but if you would like to continue the conversation or have more details, please feel free to reopen.
