### ISSUE TITLE
I can't see a lower half...

### ISSUE THREAD

**Issue by 7hat3eird0ne** [DraqueT/PolyGlot#1279]
![HowItLooks](https://user-images.githubusercontent.com/131980578/234882240-18dc666d-0cfd-4757-bb15-2b43ee3124dd.png)

I am not sure if this is bug, if this isn't and it is problem on my side, then can you please tell me how to fix it?

**Comment by TrapinchO** [comment]
Are you using the beta version? If not, try it.

**Comment by 7hat3eird0ne** [comment]
Thanks it worked
