### ISSUE TITLE
Implement grammar encoding

### ISSUE THREAD

**Issue by DraqueT** [DraqueT/PolyGlot#128]
This. Just... do this. Maybe use a tree structure to allow users the ability to give examples of grammar structures as they collapse in on one another? Think about this one hard.

**Comment by Xoin** [comment]
Maybe look into https://github.com/TheBerkin/Rant for examples? Might not be exactly related or anything but it uses a understable syntax. One that you can make increasingly complex.

```<name-male> likes to <verb-transitive> <noun.plural> with <pron.poss-male> pet <noun-animal> on <timenoun.plural-dayofweek>.```

It even handles regex like conditions.

**Comment by DraqueT** [comment]
Thanks for the suggestion! I've looked at this kind of thing, and while it handles Chomsky styled languages well, those that don't rely on word order don't really fare very well with it. Right now, I'm playing with the idea of a more visual kind of style. I'm not married to the idea of making everything machine consumable so much as creating an interface that allows a human to communicate to other humans how the language is spoken.

**Comment by DraqueT** [comment]
Completed.
