### ISSUE TITLE
Cant open file anymore

### ISSUE THREAD

**Issue by Jademonas** [DraqueT/PolyGlot#1282]
It was working fine yesterday but today when i tried to open it again it says:

Could not read file: conlang.pgd
Attribute name "fan" associated with an element type "pltn" must be followed by the '=' character.

It then loads up an empty project, and i cant seem to recover what was there before.

Edit: upon attempting to reload the lang again, the file went from 70kb to 1kb, which i think means it deleted everything. The "xxTEMPPGTFILExx" is still with 70kb, and i have now saved a copy of it in case of anything. Is there any way of getting it back?

**Comment by DraqueT** [comment]
Please toss a copy of the file over to me and I will take a look at it. Draquemail@gmail.com

I will help you get this working!

**Comment by DraqueT** [comment]
Closing this issue now. As a heads up, it was this ticket that led me to fully automate the recovery process I went through to restore your language file! In the future, anyone encountering a corrupted file will simply be informed that everything possible to recover has been recovered. ^^
