### ISSUE TITLE
Beta Version - Rules Conjugations/Decenslions Autogeneration

### ISSUE THREAD

**Issue by tomtom1969vlbg** [DraqueT/PolyGlot#1297]
Hey,
we wrote yesterday about the beta version ...
Now I think there is a bug :-O
![grafik](https://github.com/DraqueT/PolyGlot/assets/117582879/71a6c3f3-53bf-4a21-8cec-e33ab2eedede)
The rules "Verg. Kononant" and "Verg. Vokal" are used on the verb in this direction.
And as I know (in the not Beta version it worked like that) the second rule should not apply on the main word, it should do it on the word that is built from the first rule - is that correct?

So whe we look at the test:
![grafik](https://github.com/DraqueT/PolyGlot/assets/117582879/92f4206a-9161-4262-8e4e-aee78f0df5cc)

First rule should make from treb -> trebu (that works)
Second rule should make than from trebu (not from treb) trebul

Or do I see something wrong there?

Thanks again for helping me out.

Best wishes Thomas

**Comment by tomtom1969vlbg** [comment]
Sorry, just didn't think correct ... so this is solved :-)
Just didn't find a possibility to delete it :-)

**Comment by DraqueT** [comment]
Glad you found a resolution there! Also, thank you for taking the time to file a bug, even if it turned out to be a false alarm. That's the only way I can know there's a problem in the wild! : )
