### ISSUE TITLE
Image loading error prevents file read

### ISSUE THREAD

**Issue by rcochrane55** [DraqueT/PolyGlot#1315]
Hi,

Having another problem where some kind of image loading error is preventing the file from reading and opening properly. It's different from last time. The error message is as follows:
![image loading error image equals null](https://github.com/DraqueT/PolyGlot/assets/67019264/cf8ecf41-eea4-46f1-a371-0a3f27d65979)

My language file still shows a size of 4.34 mb, so I think the info hasn't been overwritten but I can't access it. When I try to access the most recent version of the file backed up in my dropbox (which should be up to date with my local file) I get the same error. Not sure what the problem is but if you could tell me how I can restore my file and access again that would be greatly appreciated.

**Comment by DraqueT** [comment]
Absolutely! Could you share the language file with me? I will get it working and tweak Polyglot to make sure the problem doesn't bother anyone in the future.

**Comment by rcochrane55** [comment]
Sure, I'll shoot it over to you by email right away. Thanks.
