### ISSUE TITLE
"must be terminated by the matching end-tag"

### ISSUE THREAD

**Issue by HangryOpossum** [DraqueT/PolyGlot#1336]
I was working on my language but went to take a break and came to my PC in a crashed state (Due to Windows). I then went to open the file once I had rebooted my PC but it gave the error message that it couldn't read the file along with 

"The element type "dictionary" must be terminated by the matching end-tag "< /dictionary>"" 

This has been a reported issue before with someone else but I couldn't work out how I was supposed to add those end-tags, any advice on what I can do? The other language I was working on could open just fine, I don't know if that has any relevance but just thought I would make a note of that. I also did a fresh install of the program but turns out it was the same version 3.5.1.

Also side note, thank you for making this program, has been a big help.

**Comment by TrapinchO** [comment]
Try using the beta version insteadm.

**Comment by TrapinchO** [comment]
Glad to hear that, happy conlanging!
