### ISSUE TITLE
Out of Sight Things

### ISSUE THREAD

**Issue by Imanotheruser** [DraqueT/PolyGlot#1357]
Hi, I downloaded the Polyglot app to make my conlang. It's been great so far, but on some windows (like Lang Properties), there are some parts on the bottom of the window that I'm not able to reach. I've tried scrolling and dragging down but it doesn't work. Is there any way to fix this issue?

**Comment by TrapinchO** [comment]
Are you using the beta version?

Resizing the windows works for me. Otherwise try going to "tools" -> "settings" -> lower "ui scaling".

**Comment by Imanotheruser** [comment]
Oh, it worked! Thank you very much!

**Comment by TrapinchO** [comment]
Glad to have helped!

Please close the issue now that it is resolved, thanks!
