### ISSUE TITLE
[Request] Add a Flatpak build.

### ISSUE THREAD

**Issue by LuluEmc2** [DraqueT/PolyGlot#1367]
Hello, I'm using a distribution derived from Arch linux and I can't install properly PolyGlot. If you have the time to build an Arch linux package or a flatpak package, could you do it please ? Thanks for reading and paying attention to this issue.

**Comment by Sinfaen** [comment]
Unfortunately, as far as I can tell I won't be easily able to create a package for arch Linux as the `jpackage` utility only supports Deb and rpm for Linux.

A plan is in the works for flatpak however.

**Comment by synthfi** [comment]
since this was renamed to be a flatpak build request, closing in favor of https://github.com/DraqueT/PolyGlot/issues/1348. Please continue discussion there

**Comment by synthfi** [comment]
@LuluEmc2 https://flathub.org/apps/io.github.DraqueT.PolyGlot

lmk if that breaks for you
