### ISSUE TITLE
File couldn't be read

### ISSUE THREAD

**Issue by tealpaper** [DraqueT/PolyGlot#1370]
I used to always be able to open it just fine, but suddenly the file couldn't be opened. Any way to get around this?
OS is Windows 10 Pro

![image](https://github.com/user-attachments/assets/b7d7927c-ba9f-424e-8f83-5fe12bcbcb2c)

**Comment by synthfi** [comment]
Are you able to send me the file so I could take a look? ksjaculus@gmail.com
