### ISSUE TITLE
can't save conlang

### ISSUE THREAD

**Issue by WindowsMeRulesGithub** [DraqueT/PolyGlot#1395]
My conlang won't save. Every time I try to save, i get this error:
![image](https://github.com/user-attachments/assets/0708bc4d-b23b-49dc-9db1-61de60e068e0)

**Comment by TrapinchO** [comment]
Just for the record, what version and os are you using?

most likely related to #1393

**Comment by DraqueT** [comment]
This is the same issue as #1393, just to confirm. I am closing this ticket, but please follow the linked ticket to monitor progress, @WindowsMeRulesGithub
