### ISSUE TITLE
No Install/Compile Instructions

### ISSUE THREAD

**Issue by zauberparacelsus** [DraqueT/PolyGlot#142]
This project does not provide any instructions for compiling and/or installing.  And as I am not a Java developer, any "obvious" things that may or may not be visible are not known to me.

**Comment by DraqueT** [comment]
Ahh, yeah. Making wrappers/installers for OSX and Windows is something that I've been meaning to implement for quite some time now. Here's a link to an online copy of the installation instructions in the manual. If you still have trouble with it, let me know. ^^

https://dl.dropboxusercontent.com/u/2750499/PolyGlot/readme.html#INSTALLATION

**Comment by zauberparacelsus** [comment]
I was actually talking about compiling the source, though after posting this I found that binaries were available under the releases area.
