### ISSUE TITLE
Focus pulled when searching on error (declensions)

### ISSUE THREAD

**Issue by Aincalandorn** [DraqueT/PolyGlot#147]
Found this in the latest release and the latest code in the repository (as of this post).

When searching for a local word, if PolyGlot comes across a word missing a declension, it moves the cursor to the ConWord field without pause, causing unintended edits to the word. Even when the word has the declensions it seemed to pull focus, or the declensions weren't registered properly.

**Comment by DraqueT** [comment]
Thanks for the heads up! I'm going to be releasing an iterative update soon, and a fix to this bug will be included!

**Comment by DraqueT** [comment]
Reworked behavior. When selecting word, errors still display, but no controls are locked. Controls now only locked after an edit of the word's properties.
