### ISSUE TITLE
Font handling

### ISSUE THREAD

**Issue by DraqueT** [DraqueT/PolyGlot#152]
This enhancement has two elements.

1) Users should have the ability to export a font from a PGT file.
2) When a PGT file is loaded, PolyGlot should detect whether the user's machine has the conlang font installed. If not, it should prompt the user and suggest that they export/install it. It should be a No/Yes prompt that takes them to the export option directly. It should explain that certain functions may not work correctly if it is not installed.

**Comment by DraqueT** [comment]
1 is completed, but I'm holding off on 2 until I can explore whether I need to include this option at all. I think I can get away with forcing java to load a custom font instead via a font family name check... Closing this as completed for now.

**Comment by jes3** [comment]
Hello Draque. I have a copy of PolyGlot on my computer. I like it very much. I also have an OpenPandora which has a small screen (4.3 inches). The PolyGlot java works on the OpenPandora, but it doesn't fit in the screen and I can't resize it to fit in the screen so I can click on the "plus" button. Is there a way to resize PolyGlot so it'll fit the small screen?

**Comment by DraqueT** [comment]
Thanks for the feeback, Jes! Anyhow, you cannot currently shrink PolyGlot like that, but I am working on very big UI reworks for the next version (v. 1.0). Hopefully the changes made will help with the small screen issue you're dealing with now! Unfortunately, there really isn't much to be done before that. When I first created the UI in PolyGlot, I was pretty new to Swing, and made it a bit clunky. Until I rewrite those parts, there's not much to be done.

**Comment by jes3** [comment]
Hi Draque, I'll wait for the next release than :) Thank you for replying! PolyGlot is a wonderful program. I love it! It works well on my PC. I'll wait for the next version so I can have PolyGlot be portable :) 

Keep up the awesome work!

**Comment by DraqueT** [comment]
You'll be happy to know that after 1.0 is out, my next project will be making mobile reader clients for Android and iOS! :3

**Comment by jes3** [comment]
That would be very cool if PolyGlot worked on my smartphone!!! It would be perfect... Android and my Open Pandora :)

**Comment by BegottenMeridian** [comment]
I can't wait for an Android release! That will be awesome!

Thank you so much for this conlanging tool. In my opinion, it is the best general purpose language construction tool out there.
