### ISSUE TITLE
Recently opened dictionary

### ISSUE THREAD

**Issue by Xoin** [DraqueT/PolyGlot#173]
Got mine at a decently odd spot which makes getting to it a bit journey when I just want to add one word.

**Comment by DraqueT** [comment]
Could you be more specific? I'm not sure I understand what you're saying here.

**Comment by Xoin** [comment]
Have a list of recently opened dictionaries in the File menu.

**Comment by DraqueT** [comment]
Ahh, that's a good idea. I'll see if I can't implement this for version 1.0.

**Comment by DraqueT** [comment]
Completed. Uncomment last element in ScrDictMenu.java init method once ini mod is completed for full functionality.
