### ISSUE TITLE
Consider making Types and Genders screens nonmodal

### ISSUE THREAD

**Issue by DraqueT** [DraqueT/PolyGlot#192]
Might want to implement this in the future for easier language browsing.

**Comment by NateDogg1232** [comment]
I have a suggestion for this. Instead of making it modal, just make everything else read-only

**Comment by DraqueT** [comment]
Hrm, that's something to consider... the difficulty is just that all other buttons and menu elements would be active at that point. I could implement something that would disable them as well, but that would take additional time. The big thing is that changing  type and gender affect behavior over the entire program, so I need to lock stuff down while they're being edited.

Def something I'll return to, though.

**Comment by DraqueT** [comment]
Pop behind issue for dialogs has been fixed. I'm closing this, at least for now.
