### ISSUE TITLE
Layering Issue?

### ISSUE THREAD

**Issue by tigfa** [DraqueT/PolyGlot#197]
Here is a picture for reference: 
![134](https://cloud.githubusercontent.com/assets/13210030/8536305/d5b825ba-2481-11e5-9c1a-3a53cccd07ab.png)

I have clicked the winrar. Naturally, it should go to the front, however, it is still obscured by the polyglot window. All of the other polyglot windows layer well, except for the main menu.

Please tell me if I explained something poorly, thanks!

**Comment by DraqueT** [comment]
Good catch, and thanks for the screenshot! The main menu is designed to always be on top of other PolyGlot windows, but should not remain above other windows when you deselect the program. I'll have this addressed in the next build.

**Comment by DraqueT** [comment]
Aaaaaaand corrected. Thanks again for bringing this to my attention!

**Comment by tigfa** [comment]
No problem! Everything else seems fine for now, I'll report any other issues.
