### ISSUE TITLE
When two tabs are selected quickly and closed afterwards, they stay pressed.

### ISSUE THREAD

**Issue by 5587026** [DraqueT/PolyGlot#207]
When two buttons are pressed on the main menu (http://gyazo.com/b3fe21afdf8fc81035b6e6c0edbfbcd2), and the windows are closed, one button, or sometimes two, stays pressed, even after returning to the menu (http://gyazo.com/b3f5d3dc6a3ead16d001e213ddaf5892).

**Comment by DraqueT** [comment]
Thanks for the heads up on this one! Might rethink how those buttons keep track of open windows...

**Comment by DraqueT** [comment]
Caught and corrected this one! ^^
