### ISSUE TITLE
no core on excel import screen

### ISSUE THREAD

**Issue by DraqueT** [DraqueT/PolyGlot#231]
this

**Comment by DraqueT** [comment]
Fixed.

**Comment by lxndio** [comment]
I still get this bug in 1.0. As of 1.0 being built on 26302d0 it should be fixed, shouldn't it?

**Comment by DraqueT** [comment]
Ack, thought this had been taken care of. X|

Thanks for the heads up here! The error that pops is 100% harmless, since this window doesn't use core functions (the check is just inherited). I'll get it corrected in the next update.

**Comment by DraqueT** [comment]
Fixed.
