### ISSUE TITLE
Blinking windows

### ISSUE THREAD

**Issue by Capital-EX** [DraqueT/PolyGlot#234]
With two or more windows open, the active window and the menu window will rapid switch which window has focus.
OS: Windows 7

**Comment by jes3** [comment]
Lexicon button stalls and does nothing. Some other buttons work. Debian device.

**Comment by jes3** [comment]
Going to > File > New, stalls and doesn't do anything. Debian device.

**Comment by DraqueT** [comment]
The flashing issue should be fixed (redownload to get the new build). I'll look into the "New" issue and create a bug if that hasn't been fixed by this as well.
