### ISSUE TITLE
Existing types get deleted when creating new types sometimes

### ISSUE THREAD

**Issue by lxndio** [DraqueT/PolyGlot#236]
When I add a type, sometimes an existing type gets deleted. That does not happen if you select the first type in list before adding a new type but then the program won't save anymore.

**Comment by DraqueT** [comment]
Thanks for the details there! People have mentioned this in the past, but I had never thought to try and recreate it be selecting another value. This fix will be part of a minor update in the coming weeks. ^^

**Comment by DraqueT** [comment]
And corrected! Thanks again for reporting this with some detail!
