### ISSUE TITLE
Pronunciations for declensions

### ISSUE THREAD

**Issue by scvannost** [DraqueT/PolyGlot#237]
[Enhancement] It would awesome to be able to see the pronunciation of the declensions of words in the dictionary. There are often times different sounds in the declined word than the root word.

**Comment by DraqueT** [comment]
That's a good thought! I might go ahead and add just that.

**Comment by DraqueT** [comment]
Completed. Tool tip text on mouse over for declensions is now set to their pronunciation on form load.
