### ISSUE TITLE
Info on some windows not opening on Debian

### ISSUE THREAD

**Issue by momikey** [DraqueT/PolyGlot#238]
I'm running Debian testing, and I had the same problem @jes3 mentioned in the comments to #234: the Lexicon window and a couple of others wouldn't open.

I ran PolyGlot in the terminal and found out why. Clicking on the Lexicon button gave me a`java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel`. This let me figure out the problem.

Debian's current default Java is OpenJDK 7, but this version doesn't include JavaFX. OpenJDK 8 does, with the `openjfx` package. Debian users will have to install that first, then run PolyGlot using OpenJDK 8. On my system, I used `/usr/lib/jvm/java-8-openjdk-amd64/bin/java -jar PolyGlot.jar` to do this.

I haven't tested much else, so I don't know if there are any other bugs that might come from using OpenJDK 8, but the Lexicon and Quickentry windows open now, and everything else seems to work.

**Comment by DraqueT** [comment]
Thanks for the sleuthing there! I'm definitely going to modify the Linux install instructions to reflect this.

**Comment by DraqueT** [comment]
Updated, both in program and online...
