### ISSUE TITLE
ArchLinux: Export to Excel size limitations

### ISSUE THREAD

**Issue by blakcap** [DraqueT/PolyGlot#243]
I was looking at the "Export to Excel" feature, and I was able to export a new language with just one entry in the Lexicon. However, using the demo `Lodenkur.pgd` language, and I got an:
```
Export Problem: The maximum length of cell contents (text) is 32,767 characters
```
![screenshot from 2015-08-13 23-26-07](https://cloud.githubusercontent.com/assets/5877394/9268334/bf6c1dd0-4212-11e5-9891-3058ca72a16d.png)

I didn't get anything else, so I can't give a stack trace. I'm guessing it's your fleshed out Grammar being longer than 2<sup>15</sup>-1. Which is actually cool, that you have that much!

FYI: Got this on Linux (Arch) with OpenJDK 8 & JFX installed, using the newest (1.0.1) PolyGlot release.

**Comment by DraqueT** [comment]
Thanks for bringing this to my attention! I think this might exclusively be a problem in Linux, as I haven't been able to recreate it on my machine. I'll make a note to spool up an Ubuntu box as soon as I can to test against this. 

My dictionary doesn't have nearly that many words (I wish!) so I suspect it's anotehr issue. ^^;

**Comment by DraqueT** [comment]
Can't reproduce this any more. Was likely corrected back when I included code to purge corrupted (massive) declension entries.
