### ISSUE TITLE
ArchLinux: PDialog windows lack toolbar properties (can't exit)

### ISSUE THREAD

**Issue by blakcap** [DraqueT/PolyGlot#244]
From the main menu, when I select any of `Genders`, `Types`, or `Lang Properties`, there seems to be no way to exit:
![screenshot from 2015-08-13 23-27-53](https://cloud.githubusercontent.com/assets/5877394/9268386/5a4468b2-4213-11e5-8506-852af766ca3c.png)
![screenshot from 2015-08-13 23-28-19](https://cloud.githubusercontent.com/assets/5877394/9268388/5b7b207c-4213-11e5-8a5b-80c71b8fb00c.png)
![screenshot from 2015-08-13 23-28-53](https://cloud.githubusercontent.com/assets/5877394/9268390/5cf78fb2-4213-11e5-955e-4badf212fdd4.png)

It's just these three windows without either a "Done" button or a big "X" in the top right. Am I missing something obvious?

FYI: Arch Linux (GNOME 3.16.3), OpenJDK8 & JFX installed. Launched with ZSH, if that matters at all.

**Comment by DraqueT** [comment]
This has been corrected. All modal windows have button based exits now.
