### ISSUE TITLE
Main Menu won't work.

### ISSUE THREAD

**Issue by Xarxai** [DraqueT/PolyGlot#247]
Polyglot 1.0.01 opens fine, but clicking either lexicon or quick entry causes the program to "think" seemingly infinitely.  Clicking Lexicon again after it's already selected results in an error.  The rest of the buttons bring up menus, however.  When I attempt to close the program, nothing happens, the only way I've been able to close it is through task manager.

![error](https://cloud.githubusercontent.com/assets/14024260/9559895/97aba242-4dcb-11e5-977a-a38dbe7734a4.JPG)

**Comment by DraqueT** [comment]
Thank you for taking the time to file a bug report and to include screens!  :3

First off, what version of Windows and Java are you running? I've tested on everything from Win XP forward with success. Polyglot does require at least Java 7 to run properly. If you're running 6 or lower, it can cause some really difficult to predict errors like that If you're running Java 7 (or preferably 8) and still having the issues, let me know and I'll look more closely at what might be causing the issue!

**Comment by Xarxai** [comment]
I'm running Windows 8.1, 64 bit, and my java is version 7.  I'll attempt to update it to 8 and see if that fixes the issues.

**Comment by Xarxai** [comment]
Draque-
Updating to v. 8 seems to have fixed the issues!  Java was telling me it was fully up to date, so I checked the site instead.  Thank you very much!

**Comment by DraqueT** [comment]
Glad that fixed it! I'm still going to check out what scenarios lead to J7 acting up, though... 

Thanks again for reporting all this! That's how problems get fixed. ^^
