### ISSUE TITLE
Stream Safety (Windows saving problems)

### ISSUE THREAD

**Issue by DraqueT** [DraqueT/PolyGlot#249]
Stream safety is being poorly managed. Refactor all sections with IOStreams to use the proper try with resources pattern. This is causing problems with some OSes that release IO permissions differently.

OLD: Open a PGD file. Now quickopen another (using the recent files menu). Immediately save. This results in a save error because the file is "in use." Track down and fix, obviously... seems to be Win8 exclusive isue.

**Comment by DraqueT** [comment]
Test this on windows 10 (kyle's gaming box will do). If it only exists for W8 users... ehh. Then its priority is pretty low.

**Comment by NateDogg1232** [comment]
I have a Win 10 machine that I can test it on

**Comment by DraqueT** [comment]
Thanks much!

**Comment by NateDogg1232** [comment]
Is this with the latest commit?

**Comment by DraqueT** [comment]
This issue should still exist with the latest commit. If you aren't seeing it, then I think it's exclusive to Windows 8/8.1.

**Comment by NateDogg1232** [comment]
No. I just got the error. It still exists in Windows 10

**Comment by DraqueT** [comment]
Ok, appreciated! It must be some issue with how Windows handles file reservation that was implemented in 8 and persists now... Thanks for your help tracking this down! ^^

**Comment by NateDogg1232** [comment]
No problem! It's a good thing I just recently updated!

**Comment by DraqueT** [comment]
Fixed.
