### ISSUE TITLE
Declensions Don't Save

### ISSUE THREAD

**Issue by shinobhi** [DraqueT/PolyGlot#251]
When I try to add declensions to a noun, for whatever reason they won't save.

**Comment by DraqueT** [comment]
Thanks for sending a bug report, I appreciate when people take the time to!

Could you upload the PGD file that you're having trouble with somewhere that I could get it? If I can reproduce the bug that you're seeing, I'll be much closer to quashing it for you.

**Comment by shinobhi** [comment]
Sure! Where can I send it?

**Comment by DraqueT** [comment]
Just toss it over to draquemail@gmail.com and I'll take a look at it. :3

**Comment by DraqueT** [comment]
This has been corrected.
