### ISSUE TITLE
Automatic Declension Generator not working after I reopen my .pgd file

### ISSUE THREAD

**Issue by PointLess1904** [DraqueT/PolyGlot#252]
So after having saved my file for the first time and reopening it, all of  my declension presets seemed to be not working, as they were not shown in the Lexicon. After navigating to the Automatic Generator, it turns out that the rules are still there, but all the Regex expressions are missing.

**Comment by JukeBoxHeroTP** [comment]
I believe this is a part of issue #250 which was fixed in commit 65595dc. I do not believe this change has been put into a release version of PolyGlot yet, but you can read through the comments of #250 to see how I went about fixing the issue in the current version.

**Comment by PointLess1904** [comment]
Thanks, I'm going to try implementing your changes.

**Comment by DraqueT** [comment]
I really need to put together the new release that includes this fix. In the mean time, let me know if you want me to mail you the newest jar or something. That will get you where you need to be.

**Comment by PointLess1904** [comment]
I implemented JukeBoxHero's fix from #250, and everything works as it should now, but thanks nonetheless!
