### ISSUE TITLE
Add partial matches for search in field Natlang word

### ISSUE THREAD

**Issue by kdelwat** [DraqueT/PolyGlot#254]
I've been finding it quite difficult to find words in my lexicon as the "NatLang word" search is exact. Would it be possible to allow it to match only part of the word, like the "Dictionary" search currently does?

**Comment by DraqueT** [comment]
This is a good idea! I'll definitely implement it in the next release. I've unfortunately been crazily busy as of late, but am hoping to get back to this project soon!

**Comment by DraqueT** [comment]
Implemented.
