### ISSUE TITLE
Update readme with How To: eliminate winrar archival association with .jar files

### ISSUE THREAD

**Issue by RonynCato** [DraqueT/PolyGlot#331]
So, how am I actually supposed to run this thing?

I recognize that as a Windows user I'm basically a cockroach, but could somebody tell me how it actually works?

**Comment by DraqueT** [comment]
Hrm. Once Java is installed, you should just have to double click the PolyGlot.jar file to start it up. What's happening when you try that?

**Comment by RonynCato** [comment]
It opens it up in winrar

**Comment by DraqueT** [comment]
Here's a video tutorial that shows you how to disable winrar grabbing/opening jar files. I'm probably going to update the help file with instructions on how to do this as well.

Thanks for letting me know this was an issue!

**Comment by DraqueT** [comment]
I'm closing this ticket now, but if you continue having issues with opening PolyGlot, please reply here to reopen it.
