### ISSUE TITLE
Accent support?

### ISSUE THREAD

**Issue by ktracer-isp** [DraqueT/PolyGlot#332]
I'd like to be able to define an accent character in the pronunciation guide that modifies the sound of other characters. I have a conlang wherein there's a "voice" character; e.g. "p" is `p`, but "ph" is `b`; "k" is `k`, but "kh" is `g`. The "h" character is only ever used as an accent, but I'd like to have it as a character so I don't have to define all the voiced and voiceless variations independently.

**Comment by DraqueT** [comment]
This is pretty easy to do in PolyGlot, actually!

Take a look at the pronunciation chart. To the side are up and down arrows. This allows you to move entries up and down in the list. The reason this is important is that placement in the list determines precedence. As long as "ph"-> "b" appears before "p" -> "p", then it will always default to the first rule when it encounters the letter combination.

Let me know if this is what you were looking for. ^^

**Comment by DraqueT** [comment]
I am closing this ticket now. If you continue to have problems, please reply here to reopen the ticket.

**Comment by ktracer-isp** [comment]
Works for me! Though I have to look at my home browser and figure out why it logged me in with this account.
