### ISSUE TITLE
Lexical Notes not Saving

### ISSUE THREAD

**Issue by pennamechris** [DraqueT/PolyGlot#379]
Notes feature in Lexical families doesn't save.
Feature request- exporting of Families into pdf file with other information.

BTW, thanks so much for this little program. I use a mac and its so hard to find something mac compatible for conlangs

**Comment by DraqueT** [comment]
Thanks for bringing this to my attention! The next release of PolyGlot is going to be a really big overhaul, so I appreciate knowing about messy bugs before I make that release! ^^

**Comment by DraqueT** [comment]
Completed. Rolling this into #376 with everything else recently.
