### ISSUE TITLE
Past dictionaries not opening in 1.4

### ISSUE THREAD

**Issue by co50ft** [DraqueT/PolyGlot#383]
![screen shot 2017-01-19 at 12 36 08 pm](https://cloud.githubusercontent.com/assets/25227675/22113986/ed2fcb96-de5f-11e6-84e3-d1c7c3beccc9.png)
When opening PolyGlot dictionary files made in previous versions, this error message pops up. The example dictionary loads fine, but my dictionaries don't. Though they still open fine in 1.3 and 1.1. 
Thanks!

**Comment by DraqueT** [comment]
Thank you for the bug report! I can't find all the bugs myself, so I really appreciate people taking the time to write them! Could you please attach a copy of the language file giving you trouble to this ticket? I am having trouble reproducing the error, and that would help me track it down.

**Comment by co50ft** [comment]
[Problem Languages.zip](https://github.com/DraqueT/PolyGlot/files/719010/Problem.Languages.zip)
Here, you go, both these languages have been having the problem for me. Let me know if you need anything else. Thanks for all your work on this program, it's so helpful and greatly appreciated!

**Comment by DraqueT** [comment]
Ok, took a look at them... The first, AmauenC is really confusing. It looks like the file itself is actually a Mac shortcut file. It looks like it somehow got created for your language file, then the shortcut was renamed to the same name as the file itself.

The second one was a bit more complex, and DID uncover a new bug! This one had to do with miscasting that happened only in edge cases such as yours.

Anyhow, I am currently working on PolyGlot 2.0, and this fix will be present in it! Sorry that it's giving you some troubles at the moment.

**Comment by DraqueT** [comment]
Oh, and thank you for taking the time to upload them and everything!
