### ISSUE TITLE
Mac Frontend

### ISSUE THREAD

**Issue by DraqueT** [DraqueT/PolyGlot#386]
Create a Mac frontend like the Windows one. This might be more difficult/less possible... but good to try anyhow.

**Comment by DraqueT** [comment]
Removing from 2.0 release. For a future release, unfortunately. : \

**Comment by lucymhdavies** [comment]
Happy to test this out, when it's ready.

macOS user here :)

**Comment by jacoblysgaard** [comment]
Adding my 10c to this. A mac frontend would be great!

**Comment by DraqueT** [comment]
This was addressed with the move to Java 12. PolyGlot is now a native image on OSX.
