### ISSUE TITLE
Error importing lexicon from CSV

### ISSUE THREAD

**Issue by kdelwat** [DraqueT/PolyGlot#387]
When importing a lexicon from CSV, I get the following error:
```
Could not import from file /home/directory/lexicon.csv
Check the make certain that column mappings are correct (nothing above max cell value) and that the file is not corrupt: 4
```
This occurs with the following settings:

![screenshot from 2017-02-06 12-08-56](https://cloud.githubusercontent.com/assets/1031518/22631625/e39fb39e-ec64-11e6-85da-3c9a063e311f.png)

Deleting the column number next to 'Definition' causes the error to switch to 1, then 2, and finally the import works when only ConWord is specified with column number 0.

I would normally put this down to a problem with my input file, except that converting the CSV to an XLS file allows import to work perfectly.

I've uploaded the offending CSV file [here](https://dropfile.to/6Er4MaV), hopefully that helps with debugging! Thanks for all your hard work on PolyGlot 😄.

**Comment by DraqueT** [comment]
Oh wow, thanks for the really thorough bug report! I'm taking a look at this right now for you. It's going to be a week or two more before the next version is ready to release, but once I get this importing correctly, I'll post the language file here for you.

**Comment by DraqueT** [comment]
Ok, I found/fixed the bug! Here's the language file I imported. Also, I snagged the gender values of the words by putting column 3 into the Classes field, which can handle any arbitrary type word classification.
[LANG_01.zip](https://github.com/DraqueT/PolyGlot/files/754958/LANG_01.zip)

**Comment by kdelwat** [comment]
Thanks so much, that's very helpful!
