### ISSUE TITLE
Class based conjugation/declension rule filters

### ISSUE THREAD

**Issue by Rick-ASCII** [DraqueT/PolyGlot#397]
Add the ability to change the conjugation/declension of a word based on its lexical class, in case that's not easily filterable, or filterable at all, with the regexes in the conj/decl menu.

**Comment by DraqueT** [comment]
Hey there! This is a really fantastic idea! This will probably not appear in PolyGlot 2.0 unless I get some extra time before the end of the month (when that's slated t come out), but it will absolutely be implemented in future versions! I am planning on doing a revamp of the conjugation system, as it is clunky and confusing right now, even if it's powerful.

Thanks for the input!

**Comment by DraqueT** [comment]
This was completed in another ticket. Marking as dup/closing.
