### ISSUE TITLE
Line breaks being edited out of definition.

### ISSUE THREAD

**Issue by electric-snake** [DraqueT/PolyGlot#403]
Useful for words with multiple definitions

**Comment by DraqueT** [comment]
On deselecting and reselecting a definition, line breaks are edited out. This is due to definitions now being saved in HTML. On both the front and backend, have '\n' -> "<br>" and vice versa.

**Comment by lucymhdavies** [comment]
If it's saving in HTML format, I suppose it could be updated to '\n' -> "<br>" and vice versa?

**Comment by DraqueT** [comment]
Now inserting line breaks where they don't belong... reopening.

**Comment by DraqueT** [comment]
After clean/rebuild, unable to reproduce error... might have been files failing to build correctly after I modified them. Closing.
