### ISSUE TITLE
Override Pronunciation Rules not working

### ISSUE THREAD

**Issue by electric-snake** [DraqueT/PolyGlot#405]
When "Override Pronunciation Rules" has been checked and a custom pronunciation has been added, navigating away from the word and then back to the word will cause the program to replace the custom pronunciation with the autogenerated one.

**Comment by DraqueT** [comment]
Thank you for all the suggestions and for the bug reporting! I really appreciate when users interact and let me know about their experiences with PolyGlot! You make really good suggestions, and I'll be working to include them as features with the net release! ^^

The syllables one will be tricky, but I'll try and have something put together. ^^

**Comment by DraqueT** [comment]
Bug confirmed. To activate, click override, modify pronunciation, then deselect/re-select word. The bug does not pop when modifying the word itself.
