### ISSUE TITLE
Pasting and Alt-Codes in Phonology Entries

### ISSUE THREAD

**Issue by ZodiacBeast** [DraqueT/PolyGlot#408]
Hello, I'm a first time conlanger and am finding this program to be extremely useful. However, I cannot define some of my language's phonology because my vowels are Latin style - including macrons.

The only way I can get a...uh...macroned letter into the entry would be to use an alt-code or to paste it, neither of which I can currently do.

I can paste characters into my languages "alphabet" list on the "Lang Properties" tab, so I was surprised when I couldn't paste characters to make defining phonology quicker...or in this case possible.

Is there a way around this, or am I just missing something obvious? Can somebody please help me with this? It's one of the only things stopping me from running wild, Hulkamania style.

Thanks in advance,
ZodiacBeast

**Comment by lucymhdavies** [comment]
If you closed the ticket, does that mean you figured it out?

**Comment by ZodiacBeast** [comment]
No, I just decided to stop using the program (for various reasons).

**Comment by DraqueT** [comment]
I'm sorry to hear that the program wasn't what you were looking for, but would you mind elaborating on the paste problems a bit? Was there some place that wouldn't allow pasting? I've looked through the phonology section, and all of the text fields were compatible. Was there some other method that you were using? 

I just want to make sure that I get this cleaned up if it's a bug.

**Comment by ZodiacBeast** [comment]
I guess I could have been a little clearer.

On the "Phonology" tab, if I press the green plus to add a character to define, the program allows me to type the letter "A" (for example) into the field, but if I were to copy the letter "A" from, say, a word document or a web page and try to paste it into the field, I am unable to. Actually, I can not right click here at all.

The Alt-code came from me trying to use the process to skip pasting once I found out that didn't work, but that didn't work either. It seems that the program recognizes _some_ alt codes, as letters with tildes work just fine.

**Comment by DraqueT** [comment]
Are you on a mac? There is a known issue that sometimes option+V does not paste. Ctrl+V will paste on all systems.

I've opened a new ticket to add a dropdown menu to text boxes with cut/copy/paste options, which should be more convenient to a lot of users such as yourself.

**Comment by ZodiacBeast** [comment]
No, I was one of the first adopters of Windows 10. Still don't see what the big deal is about it. *shrug*
Anyways, ctrl+V solved my problem and I can paste anywhere now (the power!). Thank you.
