### ISSUE TITLE
Enforce RTL adds line breaks to multi-line text boxes

### ISSUE THREAD

**Issue by blindcat97** [DraqueT/PolyGlot#418]
When Enforce RTL is selected, there are extra line breaks added to the beginning of any multi-line text boxes, such as word descriptions in the lexicon, or the author/copyright info box in lang settings. This seems to happen every time I enter a new submenu. For instance, from a blank file, if I create a test word with some text in the description and then turn on Enforce RTL, after clicking through a few other menus (phonology and grammar, for instance), when I return to the lexicon, there will be some extra lines at the top of the box. If I jump back and forth between the lexicon and some other menu, there seems to be an infinite number of lines added. These are saved with the file, and nothing I can do seems to have fixed it. 

I'm not sure that a screenshot is needed, but I've included one just in case. The extra lines before the definition were not entered, and I have attempted to simply remove them manually several times. A few more jumps between menus and they were back.

![image](https://cloud.githubusercontent.com/assets/13594367/24530394/a3138e1a-157f-11e7-913e-fe65ff79465a.png)

**Comment by DraqueT** [comment]
Thank you for the detailed write up here! Once I correct this, I can give you access to a beta of the current build if you like. just let me know!

**Comment by blindcat97** [comment]
Thank you very much! That would be wonderful. Although this problem isn't crippling to me quite yet, it'd be very difficult to work with once I get my own script going :)

**Comment by DraqueT** [comment]
And fixed! What's your email? I'll toss you a download link. ^^

**Comment by blindcat97** [comment]
It's blindcat97@gmail.com
Thank you very much for the help! Polyglot is a wonderful program and it's nice to know that it's author is extremely helpful!
