### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Konlab** [DraqueT/PolyGlot#419]
Dear devs/support!
Before I tell you my question I have to tell that your software is awesome and I begun using it exclusively, but I ran into some problems I don't know how to resolve.
1. If I export to PDF and a word has multiple local word meanings it it just takes them as one. I separated them by commas, like in the documentation
2. Word repetition check (so I can see that a word isn't in the dictionary multiple times) doesn't work for conjugated forms
It would be awesome these worked somehow. Am I missing something, or these aren't in my version yet...
Sorry for my english and bon courage for working on this awesome software!

**Comment by Konlab** [comment]
I see that you are open to ideas so I can tell you one more idea:
Levels of conjugation - instead of creating conjugations all possible combinations an additional option to put conjugation pattern changes above eachother, so you can apply plural first, then case for example. Useful for saving a little bit of time
Useful for derivational morphology too, if you could add translation for each one

**Comment by DraqueT** [comment]
Heyo! Thank you for the input here! Those are really good ideas! Some of these things can already be accomplished with PolyGlot.

You can enforce word uniqueness for both conwords and local words. These settings are found in language Properties. Once that's selected, it will disallow moving off of copies (unless you click the rule override option for a word).

The multiple words suggestion for PDF printing is one that I will implement before the next release for sure!

The conjugation change is one that I'm going to put some thought into. I need to revamp how conjugation works, but that's a really complex system, and I might need to break compatibility for people who have used it in the past... it's a lot of work to set up, so I need to figure out a conversion tool first. I don't want users to get angry and be left with a bunch of work that is now incompatible.

Again, thank you for the suggestions! I hope PolyGlot is helping you with your work. :3

**Comment by DraqueT** [comment]
All changes either implemented, or documented in other tickets. Closing.
