### ISSUE TITLE
Line breaks added mid-paragraph on multi-line text boxes 

### ISSUE THREAD

**Issue by blindcat97** [DraqueT/PolyGlot#420]
Perhaps related to the same issue I reported earlier, in which Enforce RTL caused a lot of empty line breaks at the beginning of multi-line text boxes, I'm now encountering a similar issue with random line breaks replacing spaces in the middle of paragraphs. It is caused by the same thing, switching between different menus, and switching back and forth several times causes it to become very noticeable (whereas it can sometimes be overlooked as just strange word wrapping). In a test prior to the one shown in the included snapshot, I had managed to switch back and forth enough that there was only a single word per line. It causes this in the lexicon, author info, and any other multi-line box as well. 

Just in case, I ran a few other tests, both by toggling Enforce RTL and leaving it on, as well as clearing the regular expression I had in the type pattern box shown (in case I had somehow caused a fatal flaw. I'm not very good at regex...) but none of these fixed the problem. I assume it is related to the same issue from before, as I am running the 2.1 Beta that was sent to me. Once again, I've included a screenshot to make it very clear what the issue is.

![image](https://cloud.githubusercontent.com/assets/13594367/24582076/ddaa8688-16f5-11e7-98a8-cf1e9e3e113a.png)

**Comment by DraqueT** [comment]
Thanks for the heads up there! The largeform text boxes have definitely been giving me some guff so far. X|
 
I'll take a look at this and keep this ticket updated. :3

**Comment by DraqueT** [comment]
Took some digging to find the cause of this one, but I'm just committing the code now. Let me know if you'd like me to toss the corrected version over to you at any point! ^^

**Comment by blindcat97** [comment]
Yes, I would greatly appreciate the fixed version. Thank you for taking the
time to provide that :)
