### ISSUE TITLE
Add support

### ISSUE THREAD

**Issue by NateDogg1232** [DraqueT/PolyGlot#421]
I would love for you to add the support of agglutinivity in your conjugation/declension structure

Ex.: Instead of just replacing, allow things to be put onto each other in a specific order

I would like this because my conlang is agglutinive

An example:
Litakad
Lit-a-k-a-t
Be-pres-fact-1st-perfective

**Comment by DraqueT** [comment]
Hey there! You should be able to do this no problem. For the regex value to replace just put "$" (sans quotations) and the empty end of the word will be "replaced."

For example, if you have a very basic past tense rule for English, you could conjugate "jump" like so:

Regex: $
Replacement: ed

When conjugated, PolyGlot would add "ed" to the end of "jump." The rules and transformations are applied in the order that they are shown in the menu (the arrows to the right move them up and down to help you reorder).

Let me know if this solves what your problem, and I hope PolyGlot is working well for you! :3

**Comment by DraqueT** [comment]
I'm closing this ticket for now. If you'd like to discuss further, feel free to reopen it!
