### ISSUE TITLE
overriding pronunciation

### ISSUE THREAD

**Issue by pennamechris** [DraqueT/PolyGlot#423]
Hi, thought I'd report a minor bug.
I've been having trouble overriding pronunciation rules, clicking the boxes isn't sticking. Is there something I'm doing wrong or is it an actual bug?

Loving the newest version btw. Thanks so much for all the work you do on this.

**Comment by DraqueT** [comment]
Heyo! Glad you're liking the newest release! You have actually found a bug that has already been fixed. If it's causing you grief, let me know an email it would be good to send it to and you can have the latest beta build of the next version. It's working correctly in that. ^^

**Comment by pennamechris** [comment]
That'd be fantastic! chris(.)blank(at)gmail(.)com
