### ISSUE TITLE
Two errors in Parts of Speech menu

### ISSUE THREAD

**Issue by blindcat97** [DraqueT/PolyGlot#430]
I had two parts of speech listed on this file, and decided to delete one of them in order to replace it with several new, better ones. When I deleted it, which should've left only Pronouns in the list, I was given the error pictured below.
![image](https://cloud.githubusercontent.com/assets/13594367/25553648/a541e880-2c86-11e7-810f-4bd51ca51d05.png)

The data remained as it should've for Pronouns, but the name was erased, and (as expected) became red to demand I fill in the field. I've included another screenshot below of this. It continues to happen even when several parts of speech are added and then removed, as well as after restarting the programme. Once I delete all but one, the error appears.
![image](https://cloud.githubusercontent.com/assets/13594367/25553666/40b29e54-2c87-11e7-8c65-e0203d0a2e76.png)

Another issue, although less significant, is that when I first open the part of speech submenu upon loading up the programme, the automatic window resizing makes the window the exact width of my entire monitor. That is to say, my monitor's resolution is 1366x768, and the window will fit that 1366 width, even though it is not aligned with the edges of the screen. This causes the right side to simply shoot out of sight until I move the window back. The height remains as it should. When I switch to any other submenu and then switch back to parts of speech, the automatic resizing happens as expected, rather than stretching out to ridiculous lengths. 

Note that I'm running a 2.1 Beta that was provided to me on April 10th.

**Comment by DraqueT** [comment]
Thank you for making a bug report! Could you please send the language file to my email at draquemail@gmail.com ? I am not sure what's making this error pop up for you, but I will definitely look into it!

**Comment by blindcat97** [comment]
I'm not sure if you wanted additional info sent as an email or added to this issue, but I'll assume the latter. 

I've done some additional testing in order to find out what exactly was causing the issue. The resizing issue might be related to some other part of the specific language file, as I encountered it again when I rebuilt the file from scratch, but not in a test file I've been using. Maybe the unusual orthography? Regardless,  I think there may be a fundamental problem with saving files, unless there is simply a major problem with my particular installation.

The last entry added to the parts of speech menu before saving and closing always loses all data except the name. The notes, gloss, etc. are all lost, as well as the definition mandatory setting. However, this only happens when I save and close from the parts of speech menu. If I go to another menu and save from there, when I restart the programme and load the file, everything is preserved. 

While testing this, though, I ran into a much larger problem with saving. I went to the lang properties menu to save for the test, where I first checked "Ignore Case" to see if it was related. I immediately saved and closed the programme, and only coincidentally noticed when I came back to that menu that Ignore Case was unchecked. Out of curiosity, I checked it again as well as filled in the first three fields with some random data. Save, restart and reload, and all of that data was gone. While further testing this save issue, I realised that if I switched to another menu, any at all, and THEN saved, it would not lose the data. 

I'm seeing more problems now with the parts of speech menu, as related to the same type population error from above (all of this being in my test file, which only has a few plain characters in the phonology, so I no longer thing orthography is related). I'm going to test them a little more and add another comment, for readability's sake.

**Comment by blindcat97** [comment]
The error appears specifically when I delete the last part of speech entry listed. When the first or second entry is deleted, there is no problem. In this test file, I had 3 entries, and the first two could be removed without issue. When I went to delete the third, assuming there were more entries remaining (deleting the only entry causes no problems), I received a similar type population error. If there were two entries left after the deletion, the error came up as 2 >= 2, but otherwise no difference. The topmost entry still loses the name data, and if I try to close the window without correcting this issue, I receive the following error.
![image](https://cloud.githubusercontent.com/assets/13594367/25567444/8f0854a6-2dbb-11e7-9d3d-50bee4e30cf9.png)
I cannot close the programme, either with the X or alt+F4, until SOMETHING is put in the name field. The only way I found to close it without inputting something was to use task manager, and it still produces the error before Windows forcibly kills it entirely. I am no longer prompted to save before closing, even with something put in the name field.

I apologise if all of this is a bit excessive, but these all seem to be problems that might be encountered by even a casual user (not someone poking around like I am), so I hope to offer some help.

**Comment by DraqueT** [comment]
Thanks for sending over your language file! I've been doing some testing with it. Unfortunately, I have not been able to recreate the errors that you're seeing so far.

What OS and version are you running on currently? I develop on a Mac, and I'm wondering whether there's something specific to your OS that is making the errors pop. Once I know the OS, I'll see if I can create a dev environment on a system with the same OS over here and recreate the errors.

Again, I really appreciate the detailed error reports that you're creating! They make tracking down bugs so much easier! :3

**Comment by blindcat97** [comment]
No problem, I actually very much enjoy testing these things out. I'm a nerd like that :)

I'm running Windows 10 Pro 64-bit, version 1703. I've also got Java 8, update 131 installed. I do notice that Java updated right before these problems started, but I also believe I didn't see them until after I installed the new Creator's Update for Win10, so I'm not sure if or which of these could be related.

**Comment by DraqueT** [comment]
Alright! Thanks for the find there! I found/corrected this issue, and it was a more serious bug than I had anticipated. Def hope it hasn't caused people too much frustration in the past.

**Comment by DraqueT** [comment]
I just emailed you a new beta version that should correct the issues you found.

**Comment by blindcat97** [comment]
I have not received any email yet?

**Comment by DraqueT** [comment]
Ack, I'm sorry! Please toss me an email at draquemail@gmail.com. I think I sent this to the wrong person. X|
