### ISSUE TITLE
Auto-population Issue

### ISSUE THREAD

**Issue by gingali** [DraqueT/PolyGlot#431]
Auto-population in lexicon will not auto-populate some words even though all orthographies and corresponding Latinized letters are recognized in phonology.

**Comment by DraqueT** [comment]
Could you send me the language file you're using at draquemail@gmail.com ? I'll take a look at this and see if I can't correct the problem for you. :3

**Comment by DraqueT** [comment]
Is this still an issue? I am looking back through my email and cannot find one that seems like your language file. If I'm you sent one that I just somehow misplaced it, let me know. Thanks.

**Comment by DraqueT** [comment]
Unable to recreate and no response from user. Closing for now. Reopen if contacted by user.
