### ISSUE TITLE
Fonts not seeming to work?

### ISSUE THREAD

**Issue by Mrtoast98** [DraqueT/PolyGlot#432]
I tried to put in a custom font and it's not showing up in the font selection screen. I'm not sure what i did wrong, i put it in the font directory so it should work? what did i do wrong?

**Comment by DraqueT** [comment]
What OS are you using? PolyGlot pulls the font lists from your OS, so it will only know about them if it does. If you're using Windows or a Mac, try double clicking the font to install it. If you're using Linux, I'm not 100% sure. That might depend on the version you're on.

Let me know if this helped solve your problem! :3

**Comment by Mrtoast98** [comment]
Thank you so much i managed to get the font working

**Comment by DraqueT** [comment]
Glad it's working now! :3
