### ISSUE TITLE
Create Bulk Translation Tool

### ISSUE THREAD

**Issue by DraqueT** [DraqueT/PolyGlot#434]
This is a tool for translating lists of words. It does not cover grammar.

This should be a separate window. It should be modal, so the main screen is locked. When it comes up, the main screen should switch to the Lexicon view.

On the top of the screen should be a dropdown with the choices Natlang->Conlang and Conlang->Natlang

On the left side should be an editable list (or a text field for comma delimited words?). The user editable control should switch to the correct font as appropriate. The user should be able to add words here. On the bottom of the window should be a "translate" button.

Once the Translate button is clicked, most other controls should deactivate. At this point, PolyGlot will cycle through each word. The current word should be selected automatically (whether in the list, the text box, etc.).

As each word is cycled to, a second list box, the "translation candidate" list should populate. This is populated with possible matches for the word being translated. They should be ranked (consider how best to do this). Selecting any one will cause the same word to be selected on the main screen, displaying its full values and definition. 

Once the user has selected a word they are happy with, they can click the "Next" button. They may also click the "Skip" button, which will simply move to the next word without doing anything. If "Next" is clicked, the selected word will be paired with the user-entered translation word and added to a text box in the form "<USER ENTERED WORD> -> <ACCEPTED TRANSLATION>". The text box must be of the same type used in the grammar section to ensure that proper fonts may be used even when they are not present on the relevant system.

**Comment by DraqueT** [comment]
Remember the getSuggestedTransWords() method on the ConWordCollection class. This might need to be fixed up a bit, but can be the basis for this feature.

**Comment by TheLonelyAdventurer** [comment]
The beta build works just perfectly out of the box. I also noticed that font scaling now behaves just fine.

Thank you for developing this software!

**Comment by DraqueT** [comment]
GPT is here. Closing this permanently.
