### ISSUE TITLE
Windows Frontend/Antivirus

### ISSUE THREAD

**Issue by LunarGem** [DraqueT/PolyGlot#438]
Hello,

My antivirus seems to think that polyglot frontend.exe is a Trojan. Would you have any idea why that is? Will the program still run properly after my antivirus has removed that file (which it has)?

Thanks! I love the program already!
EDIT: spelling

**Comment by DraqueT** [comment]
Huh... What virus detection are you using? If I'm using a bad standard or something, then I should probably clean that up. The file registers itself as the consumer of pgt files once it has bee run, so maybe that's what does it? None of the modifications it makes happen until it has properly performed user verified elevations, though.

Anyhow, PolyGlot will work 100% fine without the frontend. You just won't be able to integrate the files with the program for double clicking, and they won't be given their custom icon.

**Comment by LunarGem** [comment]
Ah, ok. Thanks! I'm using Norton Antivirus. It's saying it's Trojan.Gen.8!cloud.

**Comment by DraqueT** [comment]
Thank you for the detail there! I looked up the description, and it seems like Symantec recently created new patterns that sweep up some behavior of my frontend X|. I'll have to analyze when I have time and rework it.

If you want to use the frontend, it should be safe to whitelist. I compiled it myself on a network isolated Windows virtual (heck, the code is included here, you could do so as well), so it should be clean. Like I said before though, PolyGlot will work fine without it, as it only provides windows integration.

**Comment by LunarGem** [comment]
All right, it's good to know it'll work fine without it (I try not to poke with the antivirus settings just to be on the safe side). I took APCS last year, if you need any Java programming done I'd love to help out!

**Comment by DraqueT** [comment]
If you are interested, shoot an email to draquemail@gmail.com! I'm not sure what all pieces parts I'll want to address next, but we can talk it over, and you can certainly fork the project and mess around a bit! I've tried to make it pretty clear, but I'll be frank. Some of the older code (UI code primarily) is pretty difficult to read.

**Comment by LunarGem** [comment]
I'll let you know if I get some time over the summer (honestly most of my non-conlanging time is spent on freelance web design, indie game development, and trying to become edumacated [basically a highschooler's day job 😛 ]).

**Comment by ColinCheese7** [comment]
Hello,
I am sorry for being awfully late, but I tried to download PolyGlot yesterday and this same bug appeared.  However, it seemed to be that Norton was not letting any of the PolyGlot files to be opened because even if I ignored the frontend, I could not open the actual program.  This rendered the program unusable, as the frontend was supposedly a trojan, the program could not load, and the files were not unzippable.  Will the program work if I simply deleted the frontend?  Thank you for taking the time to read this complaint, and I hope to be using PolyGlot for my language in no time.

**Comment by LunarGem** [comment]
@ColinCheese7 Did you try opening the .jar file? It may not open via doubleclick. The program ran just fine without the frontend for me, but you can always just whitelist it (I call it telling Norton to "drop it" 😛 ).

**Comment by ColinCheese7** [comment]
@LunarGem I haven't done that without the frontend.  I'll try it out soon.  Thank you!

**Comment by DraqueT** [comment]
I should just remove the frontend from the forward facing zip... might do that later today. It's now recognized widely as a virus for some reason and I really need to correct that before the next big release. It's confusing way too many people.
