### ISSUE TITLE
"Unable to write file to this location. PolyGlot does not have write permission"

### ISSUE THREAD

**Issue by blindcat97** [DraqueT/PolyGlot#444]
I'm receiving the following permission error every time I try to save my dictionary with a new name. The loaded file works fine and can be saved without problem, but the moment I try to rename the file and save to the exact same directory that I've used the entire time, it gives an error. Upon further testing, this issue appears when the file is renamed OR a new file is created. Restarting the programme and attempting to save a brand new file without ever loading my old one does not work either. It gives the same error no matter what folder I attempt to save to, even Desktop or Documents (no subfolders). 

It's likely that this issue has been present since I received this beta version on May 10th, but I had not attempted anything other than saving over my usual file. I checked to see if special characters in the filename or language name affected it, but there is no obvious source of the issue on my end. Possibly related to the saving issue fixed before, where data was mysteriously lost on the last submenu accessed?

![image](https://cloud.githubusercontent.com/assets/13594367/26454343/d6b3586e-4134-11e7-88a0-d5de250cc635.png)

**Comment by DraqueT** [comment]
Good catch! This one seems to be a problem with the beta, and I'm looking into it now.
