### ISSUE TITLE
Regex Question

### ISSUE THREAD

**Issue by LunarGem** [DraqueT/PolyGlot#451]
Hello again!

I know you've probably got better things to do than supplement my coding deficiencies, but I hope this question will be quick. In my conlang, tenses have suffixes, but when a word ends with a consonant, I want the suffix prefixed instead. I'm having trouble getting the autoconjugation tool to do this. I'm using the regex ^(.+)$ and the replacement ro\1 . ro is the affix. What am I doing wrong? (I admit I just learned regexes...)

**Comment by DraqueT** [comment]
Hey there! Not at all! Regex takes some getting used to, and I an help you a bit there. What you want to do is to make two separate rules, one for consonants, one for adjectives. If you use the replacement value ^(.+)$ you are telling polyglot to replace the start of a word plus one or more characters plus the end of the word... which is the whole word ^^;. Below I have what you should need!

The regex for the consonant rule should look like this: .*([^aeiouAEIOU\W\d]|nt)$
consonant replacement: $

Regex for vowel rule .*([aeiouAEIOU\W\d]|nt)$
vowel replacement: ^

Let me know if that helps!

**Comment by LunarGem** [comment]
Thank you! I guess I still have a lot to learn 😛. (Probably should get started on that if I'm going to be a programmer...)

**Comment by LunarGem** [comment]
Can I ask a quick question about how to get Polyglot dictionaries from one computer to another? I tried exporting and importing but it's not coming out right on the other end. @DraqueT

**Comment by DraqueT** [comment]
You can just copy the PGT file over. It saves everything you need right in there, even special fonts that you're using for scripts. As long as you have PolyGlot on the other computer as well, it will be able to open the file normally. :3

**Comment by LunarGem** [comment]
Silly me, I hadn't saved the file so I couldn't find it. XD
