### ISSUE TITLE
Request/Question Root Based Dictionary

### ISSUE THREAD

**Issue by pennamechris** [DraqueT/PolyGlot#452]
I have a conlang I'm working on that is root based with consonant clusters. I know there was a recent discussion about Etymology for future versions, I was wondering if it would be possible, since I know its still in the 'working on' phase, to have a root base dictionary set up?

**Comment by DraqueT** [comment]
Possibly? How do you imagine this meeting your needs best? I'm currently in the planning phases of how the root system will work, and am compiling suggestions from quite a few people.

Also, thank you for your interest in PolyGlot! :3

**Comment by pennamechris** [comment]
Mostly I was just thinking of something rather simple. Root being placed as a parent perhaps and children under it. So if the Root were something like tls, you could open tls and have talas, atlos... or whatever as children as different word classes. In other words, Root as the main entry then there would be tears underneath for other classes of words.

I'm not entirely sure how feasible such a thing is, or how simple it is. I'm not tech savvy. I know things often sound simple and really aren't when it comes to the coding and such.

**Comment by LunarGem** [comment]
My language is also root based, my idea of this feature is more like having words and you can select which are children of another and whose children they are, but I'm new to linguistics. I'd be willing to try and work this out if I get time.

**Comment by DraqueT** [comment]
Moving forward on this one! I think you'll both really like what's coming together. ^^

**Comment by DraqueT** [comment]
Remember to reference #86 while continuing work on this ticket.

**Comment by dannYves** [comment]
> Mostly I was just thinking of something rather simple. Root being placed as a parent perhaps and children under it. So if the Root were something like tls, you could open tls and have talas, atlos... or whatever as children as different word classes. In other words, Root as the main entry then there would be tears underneath for other classes of words.

This would work great for synthetic languages - even simplifying real life languages like Hebrew or Arabic which are all done by root and categorizing words in a better way. My conlang is synthetic and these type of languages operate a little but differently than analytical ones, I have tried all kinds of different apps to help with this and there really isn't one like that out there on the internet. I can't wait to see the new integrated update :-) :-D

**Comment by DraqueT** [comment]
Alright, guys! This was a bigger job than I had anticipated, but the next version of PolyGlot has etymology 100% integrated! Just spreading it through some of the other modules before releasing...
