### ISSUE TITLE
Full regexes for phonemic orthography

### ISSUE THREAD

**Issue by Jengamon** [DraqueT/PolyGlot#455]
**EDIT**- Adds:
- replacement functionality to pairs (regex)
- recursion option, which applies each transform to the *whole string* in sequence. This allows for an earlier pronunciation to be edited by a later one. This is useful when complex replacements take place.
**ENDEDIT**
This is just a nice suggestion, but is it possible for full regexes, on the level of at least the conjugation transformers to be put in place for the phonemic orthography section. I wanted to include a rule that palatizes consonants if they were followed by a letter, but that letter can be used independently, but since the orthography section doesn't provide for substitutions, I'm stuck.
![image](https://user-images.githubusercontent.com/1479994/27044215-67c13b2e-4f62-11e7-8d96-f4b2b3da543a.png)

**Comment by DraqueT** [comment]
Thank you for reporting this! This isn't a missing feature... it's a bug. That should absolutely be working right now.

It'll be fixed by the next version! And I can send you a preview version once this one is done. :3

**Comment by DraqueT** [comment]
![image](https://user-images.githubusercontent.com/8284425/27050869-08bf357a-4f82-11e7-9642-7088e5906207.png)
![image](https://user-images.githubusercontent.com/8284425/27050878-1ace14fc-4f82-11e7-8d79-6ececf0c6b93.png)

Hrm. I think this is currently working. Check out the example I gave here. If this isn't addressing what you're talking about, let me know. I just followed what was in your example there. I would have to take a closer look at your PGT file if it's still acting up for you.

Let me know! ^^

**Comment by Jengamon** [comment]
I'm specifically talking about substitutions. The rule ([^y]y | $1ʲ) on the word pye, I want it to produce "pʲe" rather than "$1ʲe".

**Comment by DraqueT** [comment]
Ahh, I had missed that! Hrm. Yeah, I think I can get this working without too much work! I'll post here again when it's complete. ^^

**Comment by DraqueT** [comment]
Alright, finished this up! Let me know if you would like a preview copy of the newest build! Be warned though that it contains some features that aren't fully tested, and is not a stable, release version.

**Comment by Jengamon** [comment]
Could I have a preview copy? I really want to test this.

**Comment by DraqueT** [comment]
Sure thing! What email address should I send a link to? :3

**Comment by Jengamon** [comment]
somelonelypanda@gmail.com

**Comment by Jengamon** [comment]
I found something weird.
I have two rules for phonemic orthography in the following order:
([^y])y -> $1ʲ
ñ -> ɲ
![image](https://user-images.githubusercontent.com/1479994/27137682-21ba7824-50e4-11e7-9430-a7386625e439.png)
As shown, it says the pronounciation is ñʲ ɒ, when it should be ɲʲ ɒ. Is it possible to perform double substitutions for phonics?

**Comment by DraqueT** [comment]
Ok, interesting... I think what I'm going to do here is add a recursion checkbox. Having it scan through multiple times would break many people's languages (primarily those that use fonts to create new scripts which overlay existing characters). Once that's implemented, I'll toss you another beta. :3

**Comment by DraqueT** [comment]
Alright, this one should function more like you expect now. ^^

Just be sure that you select the recusing option beneath the phonology table.
