### ISSUE TITLE
Allow Romanized Entry

### ISSUE THREAD

**Issue by LunarGem** [DraqueT/PolyGlot#457]
For people who aren't finished learning their conlang or at least the keyboard associated with the font they made, maybe an option to type in the romanization and have it translate?

**Comment by DraqueT** [comment]
This is something that I've considered, but unfortunately romanizations aren't all unique. There are plenty of languages where the romanized version of words actually drops uniqueness and introduces ambiguity. In cases like these, there's no good way to go back from the romanized version to the original in a safe way.

Thank you for the suggestion, though! Even if I don't implement everything that people send in, I really appreciate the fact that people are looking for ways to make PolyGlot better!

**Comment by LunarGem** [comment]
All right. I think it's great that you look at and take the time to respond to all of these. Perhaps instead an option to display romanization or local word instead of conlang word in the lexicon layout?
