### ISSUE TITLE
Not opening

### ISSUE THREAD

**Issue by miacomet** [DraqueT/PolyGlot#458]
I just downloaded your program, and I'm very excited about it, but it's not opening.

I unzipped the file and clicked on polyglot frontend, and I got a message to associate a file type with polyglot, which I accepted. I clicked on it again and nothing happened. Nothing is opening. Any ideas what could be amiss?

**Comment by DraqueT** [comment]
Unfortunately it seems like there's a new Windows Defender issue that's preventing the frontend from functioning properly. I'm going to have to look into this to see exactly how it needs to be corrected. BUT! You should still be able to use PolyGlot. Just open up the .jar file by double clicking it. If you have Java installed, that will open it right up. ^^

**Comment by DraqueT** [comment]
As a heads up though, I _am_ going to add a ticket to this to remind myself to correct it whenever I get access to a PC to develop on more regularly.

**Comment by LunarGem** [comment]
To open it, don't click the frontend file, click the jar file. Just what I figured out @miacomet
