### ISSUE TITLE
Could not find the main class

### ISSUE THREAD

**Issue by Seeka092** [DraqueT/PolyGlot#464]
I'm trying to use PolyGlot to organise details for several conlangs for a book I'm trying to write, but whenever I try to run it as specified in the readme, it comes up with "Could not find the main class: PolyGlot.Screens.ScrMainMenu. Program will exit."

Please help!!

**Comment by DraqueT** [comment]
What OS and version are you currently running? Also, is Java up to date for you? Very old versions of Java can result in this error when running PolyGlot. Either way, I'll help clear up the problem. ^^

**Comment by Seeka092** [comment]
I'm running Windows 10. As for Java I'm not sure, I'll check tomorrow after work and if it's out of date I'll update it and let you know. Thanks :)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Seeka092** [comment]
Just letting you know I updated Java and it worked! Thanks man! :)

**Comment by DraqueT** [comment]
Glad to hear it! Let me know if you need any other help. ^^
