### ISSUE TITLE
Tooltip box too short.

### ISSUE THREAD

**Issue by DraqueT** [DraqueT/PolyGlot#465]
For some tool tip messages, the display box is too short. It should be extended as much is appropriate to ensure this no longer happens.

**Comment by LunarGem** [comment]
I'll take a look at it, see what I can do.

**Comment by DraqueT** [comment]
If you make a fork of the project, I should be able to assign it to you. :3

**Comment by LunarGem** [comment]
Done!

**Comment by DraqueT** [comment]
Hrm, looks like you need to accept a collaborator invite as well before I can add you. When committing code, please just push to your branch, then do pull requests, though.

**Comment by LunarGem** [comment]
Definitely. Invitation accepted.

**Comment by DraqueT** [comment]
Alright! All yours! :3

**Comment by LunarGem** [comment]
On it!

**Comment by LunarGem** [comment]
Can I see a screen shot of this issue when you get a chance? Pretty sure I found the suspect code, but a screen shot would help me figure out what to do about it..

**Comment by DraqueT** [comment]
Sure thing, check this out:
<img width="1440" alt="screen shot 2017-07-12 at 11 03 03 am" src="https://user-images.githubusercontent.com/8284425/28124499-d70a7a94-66f1-11e7-9bb1-64e88d768b4c.png">

**Comment by LunarGem** [comment]
I have a quick fix implemented but I need to do some investigating (and figure out how to set up my dev environment) to find the real issue.

**Comment by DraqueT** [comment]
Sounds good!

**Comment by DraqueT** [comment]
After a java update, this seems to have resolved itself... I think there was a problem with the graphic sizing element when making a call to render/estimate the graphical size of a given font. Tossing in a constant value for a bit of padding and calling it a day here, as a heads up.

**Comment by LunarGem** [comment]
All right! I am having some issues on my coding computer anyway.
