### ISSUE TITLE
Make window stop resizing itself automatically

### ISSUE THREAD

**Issue by Schyrsivochter** [DraqueT/PolyGlot#487]
(Windows 10, Java 8 x64)
The PolyGlot window keeps resizing itself whenever I switch between the different functions (Lexicon, Grammar, Phonology etc.) It does this even when it’s maximised. I don’t want this. I want the window to stay the same size, especially when I’m working with a maximised window, so I don’t have to keep maximising it again.

**Comment by DraqueT** [comment]
Thanks for taking the time to make a ticket! This feature has been added already and will be included in the next release. It was annoying to a lot of people, so it was one of the things that I decided to make an off-option for.

Once I release the next version, it should default to no auto-resizing.
