### ISSUE TITLE
Make feature to creäte ‘special forms’ in inflection

### ISSUE THREAD

**Issue by Schyrsivochter** [DraqueT/PolyGlot#488]
When creäting inflection forms (conjugation/declension), one should have the ability to creäte ‘special forms’ that don’t follow any inflectional category—such as infinitives, gerunds, or participles for verbs, which usually don’t have person or number.

**Comment by DraqueT** [comment]
This is a good idea! I'm not sure that I will be able to implement this in time for the next release (which will hopefully be soon), but I'm definitely going to make this one happen! Thanks for the suggestion. :3

**Comment by DraqueT** [comment]
This ticket has been addressed and completed within the context of another ticket.
