### ISSUE TITLE
Integrate IPA text-to-speech

### ISSUE THREAD

**Issue by DraqueT** [DraqueT/PolyGlot#490]
Use the project phoneme-synthesis (https://github.com/itinerarium/phoneme-synthesis) and integrate IPA text to speech in polyglot.

Remember to update documentation to include credit.

**Comment by scottgit** [comment]
This would be FANTASTIC (upvote from me). After downloading the PolyGlot software today and playing with the IPA tool, I then spent hours today searching online to find a way to get my conlang words pronounced for me... to virtually no avail! I did find the phoneme-synthesis project and it was okay, but needs mapping enhancement to get to a fuller IPA pronunciation potential (which is needed for good conlang use). Some IPA that I attempted did not get pronounced at all. 

I found in some cases, putting a Romanized form in [this translator](http://www.oddcast.com/home/demos/tts/tts_example.php) and playing with the different pronunciations by different languages was more helpful, but ultimately mapping IPA to get the verbalization would seem best.  However, I think that would have to include some added function for [diphthongs and triphthongs](http://www.yorku.ca/earmstro/ipa/diphthongs.html).

**Comment by snorepion** [comment]
This sounds great to me as well; maybe you could also implement a system for users to add their own audio for a word in the case that phoneme-synthesis doesn't work or if they want to use their voice.

**Comment by DraqueT** [comment]
As an update to everyone who has commented here, this is something which will unfortunately have to wait a bit. I've looked into this, and creation of an IPA to speech platform is something that would be a larger effort than PolyGlot itself.

If anyone finds an open source project that looks promising, please feel free to comment here. Until then, this mod is unfortunately going to have to stay on hold.
