### ISSUE TITLE
Suggestion for a setting showing how a language changes over time

### ISSUE THREAD

**Issue by Philosopherhawk** [DraqueT/PolyGlot#496]
Does the Polyglot Software have a setting to show ( once you created your language ) How will it change over a course of say, 1,000-2,000 years, etc.?...If not, there should be.

This would be very helpful for writers whose stories may be set over a period of centuries on their world and show how their Alien Character's language would change over time.

**Comment by LunarGem** [comment]
Not my repo, but how would that work? Everyone's language is different, how would a code solution determine language evolution universally? If you have a suggestion for this I'm interested, or if Draque knows how he'd do this.

**Comment by DraqueT** [comment]
I think you would probably be best served to make a class with selections for era on words. Additionally, the next version of PolyGlot (which should be out in the next month or so) has a complex etymology system that I think would be very helpful in creating a language that is layered by evolution over time.

Thanks for the feedback, and let me know if you have any ideas or requests! :3

**Comment by DraqueT** [comment]
Closing ticket for now. May revisit later.
