### ISSUE TITLE
Screenwriting Software

### ISSUE THREAD

**Issue by DTWatson** [DraqueT/PolyGlot#501]
Is there a way to make this program compatible with the Final Draft screenwriting program to make it easier to incorporate my work into my stories directly from the screen. It would be helpful if the modification was also capable of a conlang grammar, spell check, and evolving dictionary in the interface to make it easier to use while writing.

**Comment by DraqueT** [comment]
Heyo, just checking once more to see if you've got any good direction for me here. I don't really have familiarity with Final Draft, but if you let me know specifically what you're hoping for, I might be able to work something out.

**Comment by DTWatson** [comment]
I haven't worked with other programs. I do often work with Final Draft. In
terms of compatibility, I need to be able to develop my conlang as I write
rather than having to switch back and forth. The evolution and sound of the
conlang is closely connected to my story.

Think LOTR. The sound of Black Speech is different from any of the Elvish
languages. And of course the feeling the audience has toward Sauron and the
Orcs and Oracai are totally different.

As I write my screenplay, it helps to be able to directly integrate my
conlang into my work. Writing a screenplay and a conlang are both enjoyable
but come from two completely different trains of thought. To develop the
one breaks the train of thought for the other.

Final Draft is a continuously evolving program just as yours is.
Integration involves coding and legal issues. I'm a lawyer and can assist
on the latter, but can't do anything for you on the former. I only offer
because I would hate to be the person who offers a problem without
presenting a path to a solution.
