### ISSUE TITLE
Language Statistics Doesn't Use Unicode

### ISSUE THREAD

**Issue by ElsaTheHobo** [DraqueT/PolyGlot#503]
As title says; My file uses all sorts of symbols in phonology and orthography, such as IPA symbols and non-english glyphs, which end up appearing as either a ? or a � when I try to view my language's statistics.

**Comment by DraqueT** [comment]
Thanks for the heads up! The Language Statistics section is one that I mostly rewrote, and I should have anticipated this. I'll probably make a bugfix release in the next few weeks (I guarantee there will be more issues found with some of the new fewtures) and this will be among the ones addressed. ^^
