### ISSUE TITLE
Composite Fonts

### ISSUE THREAD

**Issue by ElsaTheHobo** [DraqueT/PolyGlot#505]
Enhancement: Allow the selection of a "secondary font". Not only does this cover the local language's font, but if there are any missing characters in the conlang font, aka primary font (such as the punctuation symbols used in regex), then these will 'fall back' to the secondary font.

**Comment by DraqueT** [comment]
Thank you for the suggestion! I am looking into how difficult it would be to default to a unicode compatible font when characters are inserted which do not exist in the font natively.

**Comment by DraqueT** [comment]
Unfortunately this one is going to be too difficult to complete. If characters from multiple fonts are required in your script, a custom font must be created.

**Comment by snorepion** [comment]
[Would something like this work?](https://stackoverflow.com/questions/9482255/how-do-i-specify-fallback-fonts-in-java2d-graphics2d) It wouldn't allow people to customize fonts, but you could have a fallback font with a lot of characters like Segoe UI or Times New Roman. I don't know whether this technique fits into your project, though.

**Comment by scottgit** [comment]
@DraqueT 
I was going to open a new issue related to this, so instead, let me post here to urge a possible reopening of this.

I can definitely see where

> looking into how difficult it would be to default to a unicode compatible font when characters are inserted which do not exist in the font natively ... [would] Unfortunately ... be too difficult to complete. If characters from multiple fonts are required in your script, a custom font must be created.

But how difficult would it be to do either:

1. Simply allow a secondary font to be user applied in a RegEx field. That way, a more normal Latin font could be used for RegEx expressions (controlled by the user) and then switch to the conlang font for any of those characters needed in the RegEx? _or_
2. Create a small character dialog (probably on a right click in RegEx capable fields) that allows the user to select the RegEx metacharacter(s) to insert into the field, which uses a "normal" font display for that inserted character _only_ (leaving anything directly typed in the field still the conlang font).

I've run into the annoying issue that I cannot **build a special font with the needed RegEx characters**, as my font utilizes nearly all those font "spaces" for various marks, accents, etc. in my language. Yet those marks in my conlang do not display well when trying to put them in some order normal to a RegEx expression (besides not being intuitively obvious that they are part of a RegEx expression).
