### ISSUE TITLE
Searchbar freezes game

### ISSUE THREAD

**Issue by ColinCheese7** [DraqueT/PolyGlot#506]
I have noticed that twice while using this program in the 2.1 version, when I type something in the search area, the program will freeze, and the only way to close the program out would be ending the task in Task Manager.  Is this simply a glitch unique to my computer or an actual bug?

Thanks for listening!

**Comment by DraqueT** [comment]
Huh boy. Yeah, this is definitely a real one. I had thought I squashed it a while back. Have you found a way to reproduce it? If you can tell me what activates the bug, I can definitely fix it. It's part of a race condition that resulted from me not really understanding how to use javaFX back when I first implemented it.

Thanks!

**Comment by ColinCheese7** [comment]
It seems to produce once the search-bar is used a second time.  I am still a beginner in computer science and programming, so I try not to fiddle with what isn't mine.  I hope this helps!

**Comment by DraqueT** [comment]
Thank you for the tip there! Just created a fix which I believe should plug at least this hole. I wish I was better about thread safety and swing design back when I created the framework for this. X|
