### ISSUE TITLE
Some Etymology Issues

### ISSUE THREAD

**Issue by dannYves** [DraqueT/PolyGlot#507]
First off what a wonderful update you have going on- thank you for all your hard work , it is always appreciated =)
I did encounter a few issues here and there which I am going to list for you- with a majority of issues stemming from within the etymology feature.

1- Unable to edit pre-existed (external) etymology entries. I have to delete the entire entry and recreate it.

2- If you have more than one (external) etymology sometimes it arranges itself according to the first entry and other times it does the complete opposite. There is no way to manually align the entries if need be (in the picture shown I, instead, simply just added all the etymologies under one row).

![capture2](https://user-images.githubusercontent.com/28152639/31649930-223c6bb6-b2e3-11e7-9740-7ae8915f2b6a.PNG)

3-  Font is not recognized in etymology window. The font which is used in the etymology window (in the picture) is the same font that was uploaded to the PolyGlot application.

![capture3](https://user-images.githubusercontent.com/28152639/31649897-01a9c0a6-b2e3-11e7-88f0-df905e47bd24.PNG)

**Comment by DraqueT** [comment]
Heyo! It's been a bit since you left this comment, but I wanted to thank you for the bug report! I really appreciate it when people take the time to write these up! I'm looking at the problem now. :3

**Comment by DraqueT** [comment]
This functionality ultimately needs to roll under a user controlled display font enhancement. Closing this one for organizational purposes. (see #528)
