### ISSUE TITLE
Phonology regex does not support lookahead/lookbehind

### ISSUE THREAD

**Issue by dapperdanman1400** [DraqueT/PolyGlot#508]
NOTES: Make clear in documentation/labeling/hover text that the recursion checkbox enables lookahead/behind regex functionality.

The help file says the phonology module supports regex, but it doesn't work with lookahead or lookbehind it seems.

**Comment by DraqueT** [comment]
Click the recursion checkbox below and that should activate for you. I realize now that I should document this a bit better.

If this still doesn't work for you, could you let me take a look at the language file you're using? This is specifically functionality that should be working, and it's definitely a bug if it's not.

Thanks for taking the time to report this!

**Comment by dapperdanman1400** [comment]
That makes it work! Yeah, the documentation is a little unclear what the Recursive Patterns checkbox really does.

**Comment by DraqueT** [comment]
Alright, sounds good! Making this an enhancement ticket. :3
