### ISSUE TITLE
Program hangs up if entering an illegal value in quickentry

### ISSUE THREAD

**Issue by Khurzol** [DraqueT/PolyGlot#512]
The program doesn't crash but can't be interacted with and plays an error sound when trying to click the main window, as if the error popup was still shown, even though it has already been closed. You can't even close the program down, you need to shut the process in the task manager.

Very easy to reproduce : in quickentry, enter an empty entry.
Note that Quickentry still "works", and can be used to add new entries, but you can't save anything, as the main window doesn't respond to anything, even hotkeys.

**Comment by DraqueT** [comment]
Thanks for the bug report here! I'm going to try to release a bugfix version of PolyGlot in the next couple of weeks, and I really appreciate people taking the time to write up necessary fixes! :3

**Comment by DraqueT** [comment]
Bug fixed! Thanks again for the heads up. This was a potential problem in a ton of other places which I wasn't even aware of initially!
