### ISSUE TITLE
Phonology Data Import

### ISSUE THREAD

**Issue by yatenari** [DraqueT/PolyGlot#515]
I am not sure how exactly this could work - maybe either with a import feature for Excel/CSV or as a way to copy/paste multiple lines as long as the copied area has two columns like needed for the input. The thing is, it is a bit tedious to type in a complete mapping of a font if there isn't a 1:1 basis (and maybe no upper case/lower case distinction). It works fine if there is a small (i. e. up to twenty or maybe thirty) numbers of characters to type in - but it could get troublesome if there is more than that which has to be romanized. The same goes for phonemic orthography (which might very well far surpass the number of characters due to special combinations). Having to enter every entry manually is - when migrating a language to PolyGlot - quite ... well, tedious, as said before. Especially if these things already exist in a (neat) table format - like the words.

Also, there might be an issue with import and phonology data _already inputted_. I don't know what exactly caused it, but when I first tested inputting a few words into PolyGlot and _afterwards_ tried to import data from Excel, I got the pronunciation and the romanization kicked out of my lexicon. I had the few words that were inputted before, where things were fine, and the imported words retained the pronunciation that was in the import - which makes sense somewhat - but the romanization didn't work for them. I checked the romanization, made sure it was enabled, but it didn't work properly. When I deleted part of it and newly typed it in, it _did_ work. The testing only had a simple 1:1 character mapping I could easily input, but if it was something more complicated, I'd worry about breaking it (and having to type it new instead of simply deleting it all and newly copy/pasting it, for example).

**Comment by DraqueT** [comment]
Thank you for the suggestion! I'll have to think for a bit the best way to implement something like this, but if it's a time saver for users, it's something I'll definitely look into.

**Comment by DraqueT** [comment]
I have not been able to reproduce the bug that you mention here. Would you mind sending me the excel file that you were using so I could test the exact sequence that led to the bug? If that's something you're comfortable with, please toss it over to draquemail@gmail.com and I'll see what I can suss out from it. ^^

**Comment by DraqueT** [comment]
Closing for now. If this pops up again, please let me know and I'll see if I can address it!
