### ISSUE TITLE
Random freezes causing work to be lost

### ISSUE THREAD

**Issue by quidaaya** [DraqueT/PolyGlot#516]
Hi, I want to start off with, despite the following bug, I am really enjoying this software, I am looking forward to see where it goes.

Now, with the bug.
Every once in a while, doing a random event, such as pressing "tab" in the Grammar section while I'm typing out a section, opening the "Word Quickentry" tab, or searching for words in the lexicon will cause the application to freeze and for me to lose a lot of progress, depending on what I was doing.

Am I doing something wrong or is there a deeper bug behind this?

Thank you, quidaaya.

**Comment by quidaaya** [comment]
Another note, I am updated to the latest version, if that makes any difference.

**Comment by DraqueT** [comment]
Thank you for the feedback! This is a pretty nasty bug that popped up in the newest version. I'm trying to carve out some free time for myself to address it. The loss of progress for users is just too frustrating to allow to exist.

I'll update this ticket again once it's corrected, and will hopefully make a release soon after!

**Comment by pennamechris** [comment]
Glad to hear it! I've been having this issue myself. Love this program and all you've done with it. While the bug is annoying, I'm loving everything else.

**Comment by quidaaya** [comment]
Thank you very much! Looking forward to the fix.

**Comment by DraqueT** [comment]
After reviewing, I realized that this is a bug which was fixed via an earlier correction I made. If you'd like a beta build that includes this fix, toss me an email! ^^
