### ISSUE TITLE
Bug: freezing when using Search/Filter

### ISSUE THREAD

**Issue by ianmspackman** [DraqueT/PolyGlot#517]
(Windows) PolyGlot freezes up when (I think) I enter anything in a text box in Search/Filter. (It's difficult to be certain of exactly the conditions, because of having to force-quit and restart each time.)

**Comment by DraqueT** [comment]
Thanks for the heads up! This is unfortunately a bug that is giving a lot of trouble. Fixing it has been the main hangup for the next version, but it's something I'm working on atm. I appreciate it when people take the time to make bug reports! Thanks for that! :)
