### ISSUE TITLE
Give option of having lexicon "autofill" with words from conjugation/declension module

### ISSUE THREAD

**Issue by dapperdanman1400** [DraqueT/PolyGlot#522]
Enhancement:

I am working on an agglutinative conlang, and I use the conjugation/declension module more as an "inflection" module for many of my words. A lot of totally separate words in the local language (in my case, English) would just be inflections of a single root in the conlang. An example are the words "here", "now", "this" are all the same root inflected differently. Instead of manually inserting the separate inflected variants into the lexicon, I think it'd be a good idea to give the option in the conjugation/declension module of having the different inflections automatically appear as separate entries in the lexicon, with their own local definitions fields, etc.

**Comment by DraqueT** [comment]
For something like this, I would recommend using the etymology system. Create both words, then set the origin as the parent of the inflected variant. If you need to have distinct entries for some of them like that, this might be your best bet.

Let me know if this was helpful for you! :3

**Comment by dapperdanman1400** [comment]
Yes, that is what I've resigned to doing for now. But then it leaves me having to override all the autogenerated conjugations/declensions for said words and just leaving them all blank...I have quite a few of these types of words. From a user's standpoint, I still feel like incorporating this into the conjugations/declensions module would be more user friendly. My two cents anyway.

**Comment by DraqueT** [comment]
For technical reasons, this ticket is not currently feasible. Will be revisited later after overhaul of lexicon entry entries.
