### ISSUE TITLE
Option to include conjugations when exporting to PDF

### ISSUE THREAD

**Issue by awkvardaardvark** [DraqueT/PolyGlot#524]
(enhancement)
an option to include the conjugations of words when doing file>export to pdf. Can put this either in the grammar guide or in the list of words itself as "sub words" underneath original word

**Comment by DraqueT** [comment]
Thank you for the suggestion! I'll try and include this option for the next
release.

- Draque

**Comment by DraqueT** [comment]
Heyo! Just wanted to give you the heads up that this has been implemented and will be included in the next version of PolyGlot. ^^
