### ISSUE TITLE
Allow for multiple senses and homonyms

### ISSUE THREAD

**Issue by yatenari** [DraqueT/PolyGlot#529]
I've come across the minor issue that I have words that are basically the same but differ in meaning - in short, I have words with multiple senses and homonyms (even though the latter are more rare). Currently, for every basic sense there is a separate entry. I don't have many multiples yet, so it didn't make much of a difference to have two entries under the same word without difference in the word list. However, I'd like to separate homonyms from multiple senses, since the way to arrive at them is different (compare 'lead' the metal and a 'lead' in a case - I'd like to have something to make them easier to separate from the differing meanings of the same word). I am not sure how to implement it, though.

It's what results in dictionaries in numbered words (lead 1 - metal; lead 2 - a hint) or in case of senses numbered entries after them (like, lead 1. metal, 2. hint). Not looking at the exact ordering of these (which might be implemented through selecting the number in a sequence manually), my guess would be to have an entry have an optional field for [additional sense of] with a dropdown referring to the word list and a field for the (calculated?) numeral (the homonyms could be detected automatically as every word that is equal to another without having this [sense] field activated). Well, at least I guess that would be a way to do it in a hopefully simple way.

I currently have it simply put as a custom field thing, but the main purpose of such a feature would be the increased usability of the dictionary, which makes my work-around rather useless (it appears in the dictionary, but since there'd be need of a lot of tweaking for the stylesheet to display it half-way correct, it is only a way to store the information for now).

**Comment by DraqueT** [comment]
You have have duplicate words in your dictionary (unless you've disallowed that in the language rules for your language). Would that be helpful? That would allow for multiple words with the same spelling (but different definitions/properties).

Moving forward I'll have to put some thought into how handling this in a more comprehensive way might work though. Thank you for your comment/idea! I always appreciate feedback. :3

**Comment by yatenari** [comment]
I'm currently using duplicate words, just with an additional custom field so I can see in the entry if it is supposed to be a word with multiple senses or a homonym. It's a feasible workaround, but gets a bit cluttered if there a words with more than two or three senses (most words I have only go up to two senses currently, but I have one word that has necessarily five and the lexicon thus has five entries under the same headword). It's not that big an issue in the lexicon view (since opening an entry is just a click), but it clutters up the exported dictionary since there are five separate main entries for essentially the same word (the current set-up would work for homonyms, though).

This is a mostly "cosmetic" issue since there are ways to implement multiple senses for a word, only they aren't as "nice to look at". ;-)
