### ISSUE TITLE
Error opening .pgd with special characters in name

### ISSUE THREAD

**Issue by etothepi16** [DraqueT/PolyGlot#530]
Special characters seem to cause PolyGlot to look for stripped character in file names (leading to file not found.
   - This is a problem with the windows frontend. Research why special characters are not being respected here.

USER FEEDBACK BELOW:
![polyglot error](https://user-images.githubusercontent.com/24741952/35476739-e91cca38-0382-11e8-96eb-02281e9eacb3.PNG)

I created a test .pgd with the name śliam, and as the screenshot shows, polyglot attempted to open sliam.pgd, which obviously does not exist...

**Comment by DraqueT** [comment]
Thanks for the heads up! This is a bug that I thought I quashed, but it looks like when running on Windows, it's still an issue... Thank you for bringing it to my attention!

In the mean time, I think the work around is simply to use standard characters in the filenames. The next version will allow for special characters though. ^^

**Comment by DraqueT** [comment]
Heyo! Fixed this one finally. Gonna close it now. Toss me a message if this has been bugging you and I can get the new version of the frontend over to you.
