### ISSUE TITLE
Regex Filter: Bug?

### ISSUE THREAD

**Issue by Mercure250** [DraqueT/PolyGlot#535]
I tried using the regex filter in the declension autogenerator, but it seems to have problems (or I don't understand something about regular expression, but I don't really think it's the problem because when I check on your guide for using Polyglot as well as the additional resources, it seems I did everything properly). The "everything" filter (.*) works, but when I want to get specific, it doesn't anymore. Note that it only applies to the filter, right below the rule's name, and not to the transformations within the rules, which work fine. See the screenshots below (don't pay attention to French); I try to be specific in the filter, but the form doesn't appear (only the first one is filled because it's the base form and I just set the rule with a regex filter of "everything" and no transformation), but as soon as I put "everything", it's fine. I tried removing the dot to see if the problem lied there, but it changed nothing. 

![screen shot 02-13-18 at 12 03 am](https://user-images.githubusercontent.com/34697807/36134258-95857f1a-1051-11e8-9545-f35aa48be4aa.PNG)
![screen shot 02-13-18 at 12 03 am 001](https://user-images.githubusercontent.com/34697807/36134292-db2d3abc-1051-11e8-96ed-2569c87f9f8b.PNG)
![screen shot 02-13-18 at 12 04 am](https://user-images.githubusercontent.com/34697807/36134293-df929df4-1051-11e8-8f51-f344d9131cba.PNG)
![screen shot 02-13-18 at 12 04 am 001](https://user-images.githubusercontent.com/34697807/36134297-e30c4e8a-1051-11e8-89f3-671d9f0e4cbf.PNG)

**Comment by DraqueT** [comment]
This is something I should probably rework to make more clear. The regex
that you're having issues with is actually a filter which accepts the base
word as it appears in the lexicon. So for your Present Imperfect form with
the filter ".*ah$" the transformations will only be applied if the lexicon
form of the word ends in "ah".

Please let me know if I'm misunderstanding your problem here. Either way,
I'll help to get your language file set up like you need. :3

- Draque

**Comment by Mercure250** [comment]
Ah, I understand. It's working properly, now!
Now, however, I noticed another issue : When I save, close the program and start it again, and open my save, the first word in my dictionary loses its part of speech. It's just the first word, so it's not that big of a deal since it takes one second to fix, but it's still a bit annoying.

**Comment by DraqueT** [comment]
Heyo! Been a while since I checked this ticket out, but wanted to give the heads up that the missing first word's part of speech issue is addressed as well as of now. ^^
