### ISSUE TITLE
Limit Autogeneration Depth

### ISSUE THREAD

**Issue by Mercure250** [DraqueT/PolyGlot#539]
Implement something which prevents autogeneration from going apeshit and creating infinite loops. The limit can be something arbitrary to prevent running into the halting problem.

USER INPUT BELOW:
Hi, my issue here isn't something that blocks me particularly, but I see could block someone.

Let's say I decide, in my declensions, to say that nouns ending with -a in their base form will receive an -m in whatever case. Then, I decide that words ending with -m in their base form will receive an -i for the same case. Now, of course, in the list, if I put the latter rule after the former, words ending with -a will receive -mi instead of just -m. The problem can be easily fixed by placing the rule for words ending with -m before the rule for words ending with -a.

But then, what happens if I decide that words ending in -m (in their base form) instead receive an -a? If I put the -a rule before, then words ending with -a (in their base form) will receive -ma instead of just -m, and if I do the opposite, words ending with -m (in their base form) will receive -am instead of just -a. It becomes a sort of loop.

And there is currently no way to prevent that. So I propose that you make rules clearly separated, so that they apply to the words that fit the filter but only in their base form, and then we could, inside the rule, put the transformations in the order we like so that the last transformations apply to the forms that underwent the first ones.

I must admit that it indeed was a problem for me, but I decided it wasn't too bad to just change my rules so that this problem doesn't appear anymore. My lang was forgiving enough for that, but I can imagine it could be a problem for someone else's lang.

Edit : Err nevermind, I actually found another, less forgiving case like that in my lang...

**Comment by DraqueT** [comment]
So I've put a lot of thought into this... and ultimately I don't see a method to implement this that doesn't run into the halting problem (a famous limitation of path analysis).

That having been said... I do think that I should probably limit the depth that this can go to somehow. Could be something arbitrary but large, as no spoken language will ever have conjugations with hundreds of rules that people have to apply on the fly.

Hm. Gotta put some thought into it. Thanks for taking the time to write this ticket up, though! I really appreciate it when users give me feedback. :)
