### ISSUE TITLE
Autogenerated pronounciation not working 

### ISSUE THREAD

**Issue by Keniko** [DraqueT/PolyGlot#541]
Any letter typed after c (key)/ch (sound) does not appear in the pronounciation area. Everything typed before works as expected. Nothing different was done to this character to cause this as far as I know.

**Comment by DraqueT** [comment]
Hrm. For this one, could you upload a copy of your language file for me to take a look at? I would need to see this bug in action to see what's going on there. Thanks,

**Comment by Keniko** [comment]
How would I go about uploading the file, as it's not a supported file type on this website?

**Comment by DraqueT** [comment]
@Keniko Heyo, I'm sorry but I think this one slipped through the cracks! If this is still an issue for you, please toss the language file over to my email at draquemail@gmail.com.

**Comment by Keniko** [comment]
I think I have it worked out, thanks anyway!

**Comment by DraqueT** [comment]
Sounds good closing the issue, then. ^^
