### ISSUE TITLE
Clicking Add/Remove word while filtering in lexicon freezes application

### ISSUE THREAD

**Issue by RoryStawart** [DraqueT/PolyGlot#542]
I'm not sure if it's just how I'm going about it, but if I've filtered the list of words in the lexicon to words that are a certain part of speech and click add word or remove word, the application stops responding.

I've also tested doing it by searching by word and it causes the same issue.

My only option seems to be terminating the java process running PolyGlot. ☹️

**Comment by DraqueT** [comment]
Thank you for the heads up here! That's absolutely a bug. If it's something that's messing up your process, I can let you have a beta version once I correct it.

**Comment by RoryStawart** [comment]
It can be worked around easily enough by clearing the filters before I add/remove a word, so I'm sure I can hold out until it's ready. Or compile the source myself if needed.
