### ISSUE TITLE
Allow Non-Dimensional Conjugation Form

### ISSUE THREAD

**Issue by cpalmer19** [DraqueT/PolyGlot#543]
Create an option which makes conjugations for a word type act independently, rather than as a dimension which is combined with all other dimensions.

USER COMMENTS BELOW:
Hi, I just started using PolyGlot, and I have to say I am quite impressed! It will be very useful for documenting my conlangs.

I was wondering though if you could make it possible to have a conjugation/declension type that doesn't combine with the dimensions of other conjugation types?

For example, in my language, a verb can be conjugated with a combination of person and aspect. However, each verb also has a single imperative form, which does not combine with person. It would be nice to have an option to make it a single conjugation, to avoid combining it with the other dimensions.

I don't see a way to currently do this, at least not an intuitive one.

Thanks!

**Comment by DraqueT** [comment]
Heyo! I'm so glad you like the program! It makes me really happy whenever someone lets me know that it's helping them. :3 

Anyhow, your idea is a really good one! I think that I'm going to implement this for the next release of PolyGlot! The conjugation system is one that's pretty complex, and adding something which allows users to reduce its functional complexity is a valuable thing.

Currently you could work around this by disabling the wordforms for all but three of the conjugations... but their labels would still be off in the menu. So you're correct, there's no good stand in for the functionality as of now.

If you have any other suggestions, please feel free to open new tickets! I'm always looking to improve PolyGlot. ^^
