### ISSUE TITLE
Error publishing to pdf

### ISSUE THREAD

**Issue by etothepi16** [DraqueT/PolyGlot#544]
"Unable to print to file: fromIndex(0) > toIndex(-1)" Weird thing is I was able to publish to pdf once, then I made some changes and broke it apparently!

**Comment by etothepi16** [comment]
It's also being very weird about opening the associated .pgd I had to move it to another location, open it from inside the app, and then save it in the right directory. Opening worked after that but something is definitely wrong

**Comment by DraqueT** [comment]
Heyo! Thanks for tossing me a line, I'll definitely give you a hand here! Could you please email me the .pgd file you're working with? That will let me take a closer look at whatever might be causing the problems for you.

draquemail@gmail.com is the address I use :3

**Comment by etothepi16** [comment]
Hi! I think it might have been a problem on my end... I ended up deleting and recreating the .pgd. Works great so far, but I'll reopen if I run into problems again!
