### ISSUE TITLE
Etymology Tooltip?

### ISSUE THREAD

**Issue by mackerelshark** [DraqueT/PolyGlot#545]
Hi, DraqueT!

I'm a long-time hobby conlanger (just for fun, nothing serious) and I just started using PolyGlot.  In my opinion? It's the best tool for conlangers since pen and paper were invented!

Anyway, my favorite way to build lexicons is to come up with a handful of root words from my own head and from a few real-life languages and then play with the etymologies.  Your etymology engine is perfect for that.  However, would it be possible to build tooltip functionality into it?  IE, when you hover over a root word, it shows you the English definition?  I love the engine, but right now, if I'm not 100% familiar with a word, I have to close the engine and hunt down the root in the lexicon to get the exact definition of it.  

Even if this functionality never makes it onboard, PolyGlot is still the coolest tool in my arsenal.  Thanks, man!  If you ever wanted to do a paid version with more features, I'd be in line so fast my shoes would catch fire.

**Comment by DraqueT** [comment]
Hey, this is a fantastic idea! I'm definitely going to implement this in the next version. ^^

**Comment by mackerelshark** [comment]
Cool!  I'll be all over that next version, then.

Hey, PolyGlot actually makes lexicon building enjoyable.  It's usually the worst part of lang-building.

**Comment by DraqueT** [comment]
This has been implemented... I think a duplicate ticket was created. X|
