### ISSUE TITLE
4K Scaling

### ISSUE THREAD

**Issue by sective** [DraqueT/PolyGlot#547]
It's almost impossible to use on a 4K screen because the program is scaled for 1080p.

edit: just saw another issue concerning this, ignore me

**Comment by DraqueT** [comment]
Thanks for dropping a note anyhow! Always good to know when people are having problems with things. Anyhow, the good news is that a fix to this is coming! Apparently JDK 9 will support DPI specifications, so it will scale when monitors are higher resolution.

In fact... if you're interested, I can send a beta copy once I've addressed this and recompiles in JDK 9 to make sure it's working properly on your system. Let me know. ^^
