### ISSUE TITLE
Tool Tip Text for Conjugated Forms/Right Click Functionality

### ISSUE THREAD

**Issue by scottgit** [DraqueT/PolyGlot#550]
In the conjugation screen:
- tool tip text for any given conjugation should include pronunciation and romanization values.
- right click should give copy, copy romanization, copy pronunciation options

ORIGINAL USER MESSAGE:
Hi, I just came across and downloaded this software today. It looks like it will do wonders in helping construct the language for my fictional book. However, since that book is in English, generally the conlang words put into the text will be transliterated forms, so essentially Romanized forms. Yet as best I can tell, Romanization is only done for the lexical from, not all the conjugations (unless I'm missing something in the documentation). Some ability to access a copy of the Romanized form of _any_ version of the word would be _extremely_ helpful in that endeavor.

**Comment by DraqueT** [comment]
This is a great idea! I'm going to add en enhancement ticket to get this into the next version. On hovering over the conjugations, the tooltip will display information including the proninciation and romanization of the conjugation in question.

**Comment by scottgit** [comment]
A tool tip would be fine, as long as I can right click and copy the text from that (this is my main point for copying it into a written text like a book one is working on)
