### ISSUE TITLE
Allow reordering of other dialogs

### ISSUE THREAD

**Issue by scottgit** [DraqueT/PolyGlot#551]
Some of the dialogs have up/down arrows to reorder items (e.g. Phonemic Orthology), yet I would like the ability to reorder the Parts of Speech (since the order there is the order the dialog gives it in for the lexical entry selection), Conjugations (and their dimensions), etc. (Basically, if I can add/remove to a list, I want to be able to reorder it ... with the possible exception of the Lexicon itself, since it will be ordered by the alphabetizing.

**Comment by DraqueT** [comment]
Unfortunately, this is one that might not be implemented for a while. The way data is put together, it's stored as an unordered list, then pulled back alphabetically. It's something I'll definitely keep in mind moving forward though. Thank you for the suggestion, I really do appreciate it when users take the time to give their thoughts!
