### ISSUE TITLE
Allow for local language lexical display order when working with word entry

### ISSUE THREAD

**Issue by scottgit** [DraqueT/PolyGlot#552]
In the lexical display, the conlang words are displayed at the left, then at the top, with the local language word below. The request here is a check box/radio button to _flip_ the left display to the local language words. The benefit here is that one can more easily go through the list (in English alphabetical order for example) and see which words have been defined (i.e. have I defined words for life, death, injury?; or color adjectives?, etc.). This ability to "scan" the local language list would be much easier than having to search for each local word individually through the search feature to see if that concept has had a word created yet or not in the conlang.

**Comment by DraqueT** [comment]
Huh, that is a really good idea! It might need to wait for when I rework the Lexicon screen (some of the code there is from back in PolyGlot 0.5), but that's something I've been meaning to do since forever.

**Comment by DraqueT** [comment]
Taken care of in another commit... jeez, cannot believe I let this ticket molder for so long.
