### ISSUE TITLE
Print Lexical Family to PDF

### ISSUE THREAD

**Issue by pennamechris** [DraqueT/PolyGlot#555]
First off. Love the features of this program. And I'm so pleased you keep building on this. Its been a huge help for me. Thank you.
I have a minor suggestion. The ability to print to pdf the lexical family.
Also one minor thing, when printing conjugations and trees, pdf really doesn't like it much and branches go off the page in weird ways leaving tons of empty pages and cramped space near the beginning.
If the tree printing can be fixed, I wouldn't need the lexical family as much, or vise-versa.
Anyway, thanks again. Have a great day.

**Comment by DraqueT** [comment]
The lexical family thing will def be in the next release! We'll see about the conjugation trees. Gonna try to tackle that one, but it's a big problem how they're visually encoded before I drop them in, unfortunately. X|
