### ISSUE TITLE
Copy conjugation with dimensions to new part of speech

### ISSUE THREAD

**Issue by scottgit** [DraqueT/PolyGlot#556]
Various parts of speech often have the same or very similar types of conjugations. For instance, nouns and pronouns may, or participles share aspects of verbs and nouns. 

Yet it does not appear that PolyGlot allows one to make a noun conjugation and a verb conjugation, and then copy aspects of those to another part of speech like a participle. This would save much setup time when forming the parts of speech to be able to copy the name of an aspect of conjugation (e.g. _tense_ from a verb) and paste that into another part (such as a participle), carrying all the _dimensions_ that were defined for tense with it.

Ideally, this would be on a per named aspect of a conjugation basis. If for some reason that is not possible or extremely difficult, then maybe at least being able to copy a part of speech over to a new one would be doable (e.g. build the verb conjugation, copy that whole "verb" part of speech to a new "participle" part, and then add/delete aspects to the participle).

**Comment by scottgit** [comment]
When I am in the Conjugations/Declension setup, I can "select" multiple defined conjugations, but nothing happens if I right click (no dialog comes up). I'm on Windows 10, if that matters.

**Comment by DraqueT** [comment]
Hrm. I just took a screenshot, are you in the same window as I am here? If so, I'll have to take some time to spin up a W10 box and check this out.

Screen: https://imgur.com/a/npImiuE

**Comment by scottgit** [comment]
No, we are not quite talking about the same area. I _do_ have a right click copy/paste for the "Rules" section of the Conjugations/Declensions in the _Autogeneration_ area.* What I am referring to is in the _Setup_ area, where you would have initially defined the Tense, Certainty, and Positivity with their various dimensions (yielding your 12 declension categories in your auto generation example). 

Right now, as best I can tell, you would have to redefine those three conjugations and each of their dimensions if you produced another part of speech like a participle category (or in your Lodenkur case, maybe your noun category might have a lot of overlap with the pronoun and/or adjectival category for something like gender, number, case, etc.).

So I'm talking about a copy of one or more of the Tense, Certainty, and Positivity with each of their defined dimensions in your verb to a new part of speech; or (less desirably) copying the verb part of speech itself and renaming it to a participle so it carries over all its properties (but then any noun like properties would still have to be redefined in the participle if I could not directly copy the conjugation aspects from the noun to the participle).

* As a side note, when I went to the Autogeneration dialog with my language, the string of conjugation options was long enough from what I setup for dimensions that I would not have known the right side of that dialog (the "rules" section) existed without your screen shot, as it just showed me the list of possible conjugations. I had to stretch my dialog wider to see the right side area. So you may want to not set that dialog up to a fixed width, but some width flexible to the longest conjugated string plus the "rules" area.

**Comment by DraqueT** [comment]
Thanks for the clarification! Yes, making something like this shouldn't be too difficult. Thank you for the suggestion, and you'll definitely see it in the next release!
