### ISSUE TITLE
Window title remains the default in the Phonology & Text section

### ISSUE THREAD

**Issue by snorepion** [DraqueT/PolyGlot#557]
When in the Phonology & Text section, the title bar just says "PolyGlot," in contrast with the other sections, where it would say "PolyGlot-Lexicon : [name]," for example (in the Lexicon section). 
Adding `<Property name="title" type="java.lang.String" value="Phonology"/>` to `/src/PolyGlot/Screens/ScrPhonology.form` may fix it (I can't test it myself because Eclipse is acting up).

**Comment by DraqueT** [comment]
Thank you for the heads up there! This one should a be a quick fix.

Also, I use Netbeans for PolyGlot dev. If you do a clone of this repository into that, there should be 0 setup if you want to run it as it runs normally.
