### ISSUE TITLE
Set new language name to window title on opening of new file

### ISSUE THREAD

**Issue by scottgit** [DraqueT/PolyGlot#558]
NOTE: I am on Windows 10, if that makes a difference. 

If I switch between two PolyGlot files (in my case I noticed this switching between the Lodenkur example file and my own language file), the language _name_ in the _window title_ does _not_ update to the newly loaded language _until_ I click on any of the left hand navigation links (Lexicon, etc.). Apparently right now, the window title reloads on a click to update the title to show the new section one is in, such as Lexicon, but it should also reload on the opening of a new file with a new language name.

**Comment by DraqueT** [comment]
Taken care of! Thanks for the writeup. :3
