### ISSUE TITLE
Default font doesn't display some characters properly

### ISSUE THREAD

**Issue by snorepion** [DraqueT/PolyGlot#567]
The default font used for non-conlang characters (which IIRC is Doulos SIL) makes it impossible to view the etymology of certain words in-program without having to resort to Latin transliteration. Example (the Armenian source should say անունը): 
![A screenshot of Armenian անունը displaying improperly in Doulos SIL](https://user-images.githubusercontent.com/24462989/40516488-1080326c-5f6e-11e8-92c2-e6a922d15ff6.png)
There is also a lack of support for other relatively common source scripts, including Greek, Hebrew, and Arabic, so this could affect quite a few other conlangs.  
Obviously you can't change Doulos SIL to fix this, but perhaps you could change the default font to something that has better support like Times New Roman or allow users to change the UI font.

**Comment by DraqueT** [comment]
Heyo! Thank you for taking the time to write up a request here! Currently there is an enhancement ticket that I'm looking to have complete before the next release (#528 if you're curious), which will accomplish this. Essentially, it will allow users to define the font that they would prefer to use for their general display. At the end of the day, there's no one font that will be able to accomplish all needs, so it seems like the best solution is to give people the freedom to use whichever one they find to be most useful.

I hope that you're finding PolyGlot generally helpful, despite this issue. ^^
