### ISSUE TITLE
getting "required decl/conj must be filled in" even when it is

### ISSUE THREAD

**Issue by ed588** [DraqueT/PolyGlot#570]
creating a word in the lexicon screen. have already set up 1 conj for adjective, which is "intensity", which has two dimensions, "normal" (mandatory) and "very" (not). When creating word, conword field highlights in red and i get the message "required decl/conj normal must be filled in". **clicking on "conjugations" and filling it in, however, does not dismiss the error message, meaning i can't enter the word.**

**Comment by ed588** [comment]
some images:
![image](https://user-images.githubusercontent.com/19167629/41433283-4a6bdd52-7010-11e8-9b01-e711b729dec7.png)
![image](https://user-images.githubusercontent.com/19167629/41433246-35501492-7010-11e8-855c-48acc6d712cf.png)
![image](https://user-images.githubusercontent.com/19167629/41433260-3bbba04e-7010-11e8-9f70-10b3fb3c9689.png)

**Comment by DraqueT** [comment]
Thanks for the heads up! This is definitely a bug that I was unaware of.

**Comment by DraqueT** [comment]
This will definitely be included in the next release! If it's giving you a lot of grief right now, toss me an email a draquemail@gmail.com and I can give you access to a beta build that has the fix in.

**Comment by ed588** [comment]
I can work without it being mandatory till the next release - thanks for the response!

**Comment by DraqueT** [comment]
@ed588 Please toss me an email at draquemail@gmail.com or drop an email here. I don't want to publicly link to it yet.

Also as a heads up, I have heavily modified some really basic stuff. Approach this one with care, as I have not thoroughly tested it yet. Don't overwrite your existing pgt files is what I'm saying.
