### ISSUE TITLE
Nested Declension/Conjugation Dimensions

### ISSUE THREAD

**Issue by skiptothelew** [DraqueT/PolyGlot#572]
Apologies if this is already possible, but I don't believe it is. I know I can deal with some workarounds for now. It ties in somewhat with another suggestion for non-dimensional conjugations.

I am trying to use PolyGlot for a triconsonatal root-based system. I would like my dictionary to be only roots (and functions words), and handle forms via conjugation/declension. Roots are used for both noun and verbs, so if I put in all dimensions, there will be nonsensical categories of noun declensions with tense, or the like.

Ideally I would be able to have just the root part of speech (plus various function ones), and within the conjugations/declensions setup have two "higher level dimensions" of nouns and verbs with mutually exclusive dimensions used for each.

**Comment by DraqueT** [comment]
Conjugations/declensions are handled by part of speech, so when you define those for verbs and nouns, they should be separate from the get go. If you have rules that span both, you'll be able to copy/paste from one to the other to save time, too.

Let me know if this helps!

**Comment by DraqueT** [comment]
Closing for now. Reply to reopen if you're still experiencing problems!
