### ISSUE TITLE
Bug with Grammar section

### ISSUE THREAD

**Issue by Owlblocks** [DraqueT/PolyGlot#573]
This is an amazing tool, and I hope to help give ideas and feedback to improve it! One thing I noticed is that the grammar editor REALLY didn't like it when I tried to use the Tab key. It wouldn't properly display the screen, and I ended up having to cut the entire page into notepad, delete the tab character, and then paste it back.

**Comment by DraqueT** [comment]
Thanks for the heads up here! I was just able to reproduce it, and I was 100% unaware. It'll be corrected for the next release. ^^

**Comment by DraqueT** [comment]
I just completed a fix for this. If it's something still giving you trouble, toss an email to draquemail@gmail.com and I'll give you access to a beta in which it is corrected. ^^
