### ISSUE TITLE
More Readable Declension/Conjugation Interface

### ISSUE THREAD

**Issue by Khja** [DraqueT/PolyGlot#574]
New window design:
- Top of Screen: Two dropdowns each containing a list of all dimensions for conjugating/declining word's part of speech
- Bottom of Screen: Checkbox controlling user override of autogenerated word forms
- Middle of Screen: Tabs, each containing a table of word form entries (plus non dimensional tab)

Once the two dropdowns are populated with differing values (cannot be the same), the tabs can be created and populated.

Each tab contains a table with the X/Y axes representing all the dimensional values of the dimensions fit to them. This gives every combination of the two. Disabled word forms should be greyed out/unpopulated.

There is 1 tab created for every word form outside the dimensional boundaries of the two dimensions selected by the user. Users should be encouraged to select the dimensions with the greatest number of values to minimize the number of tabs created and maximize the table usefulness.

1 additional tab will be created for nondimensional forms (if any exist). These cannot be represented in a grid and will be represented in a simple list as they are currently.

Open question: Do I show deprecated forms any longer? Are those simply discarded now?

ORIGINAL TEXT BELOW:
Hey, DraqueT!

Thanks again for fixing the bug I had months ago. Now I finally tried to download PolyGlot, and it WORKED!

So, I've been using it for a couple of days and I find it very useful to organise all the different aspects of my conlang. But I find the conjugation/declension system/interface* a little chaotic (*I mean in the Lexicon -> conjugations and also in the Parts of Speech). I would like to have tables instead of just lines of every single case. Just to make it easier to navigate and read the various declensions/conjugations.
Maybe instead of one great table, smaller tables depending on the settings the user has set (every mood its own table: indicative, conjunctive, ect.) and different ones for conjugations such as infinitve(s) or gerund(s) as cpalmer19 says in #543.

Thanks! ;D

**Comment by DraqueT** [comment]
Thanks for the input, I always appreciate new ideas from users!

I really like that idea, but I'm having trouble visualizing a good way to do it for languages that have over three conjugational dimensions. For example, if you have only tense and gender encoded in a verb conjugation, you can make a 2D grid representing all combinations. If you have tense, gender, and positivity encoded though, there is a third dimension that's tough to represent in a grid (and even more complex for additional dimensions).

I'm curious, how would you represent that kind of complexity if you were looking to show it in grids? If you have a system that already exists for organizing it, I could try my hand at modeling something after that.

**Comment by Khja** [comment]
I have this idea that's hard for me to explain, but I'll do my best. 
Visualize this system as folders in a main folder (the conjugation system), which contain or other folders or files (which are just 2D grids with dimensions you can customize; so you solve the problem of infinitives and gerunds; the folders are the dimensions). So for example, you could have  two super-dimensions: infinite forms and finite forms. In the infinite forms you could have one grid with all the possible endings/beginnings/... of the infinite form of a verb. In the finite forms you could have two smaller dimensions: passive forms and active forms. In these you could have other dimensions such as the moods and in those you could have the tenses, and finally in the tenses you could have grids for positive and negative forms.

Something like this:


I hope this helps.

Il giorno 27 giu 2018, alle ore 16:55, Draque Thompson <notifications@github.com> ha scritto:

**Comment by Khja** [comment]
Maybe you could do something that consists in having multiple folders and subfolders that contain grids. For example:

Verbs
>Infinite
  -a
  -e
  -o
>Finite Forms
  -Present
     -I conj.*
       -a
       -ai
       -i
       -in
       -ida
       -am
     -II conj.*
       -a
       -ei
       -i
       -ien
       -eda
       -em
  -Past
     -I conj.*
       -ade
       -aide
       -ide
       -inde
       -ided
       -amde
     -II conj.*
       -o
       -oi
       -od
       -ion
       -oda
       -omde
...

For instance you could have two other folders for the positive and negative forms in the folders with an asterisk (*)
