### ISSUE TITLE
Pronunciation duplicating to other words, not autogenerating

### ISSUE THREAD

**Issue by DeltAuthor** [DraqueT/PolyGlot#576]
I created a large portion of my vocabulary before setting a phonemic orthography, but now that I have set it the pronunciations are acting quite wonky.
First, after making the orthography it didn't autogenerate all of the pronunciations, only doing so after I edit the word itself:
![screenshot_8](https://user-images.githubusercontent.com/28660741/42053737-601c8f72-7ae0-11e8-8957-f95ecc4cb5a7.png)
![screenshot_9](https://user-images.githubusercontent.com/28660741/42053739-603bc130-7ae0-11e8-8560-25fe91f8fa16.png)
But even then, it copies it over to other words (This also happens if I enter a pronunciation manually):
![screenshot_10](https://user-images.githubusercontent.com/28660741/42053784-8bcdb150-7ae0-11e8-93ff-b6ae98b34828.png)

**Comment by DeltAuthor** [comment]
Nevermind, the issue appears to have fixed itself.

**Comment by DraqueT** [comment]
Glad that's no longer an issue! ^^
