### ISSUE TITLE
When a word has been searched for and the "New Word" button is hit, PolyGlot crashes.

### ISSUE THREAD

**Issue by aydenvis** [DraqueT/PolyGlot#579]
Not hard closes, but you can no longer interact with anything other than the upper bar, with the Minimize, Maximize and Close buttons. Have to end the task in Task Manager to get it to close.

**Comment by DraqueT** [comment]
Thanks for taking the time to write this up! This bug has already been fixed in the current build, so when the next release is dropped, it will be corrected.

**Comment by aydenvis** [comment]
Awesome, thanks!
