### ISSUE TITLE
Syllable and/or Word Generation

### ISSUE THREAD

**Issue by DraqueT** [DraqueT/PolyGlot#582]
The word generation system might sit on top of the syllables? Gotta work all the rules out here. Base this whole mess on whatever is created by Xeger.

ORIGINAL TICKET TEXT:
Create a section in orthography that allows users to define syllables. 

- It should both have a list of defined syllables (in the order in which they are to be searched), and provide examples of character combinations which do not allow for syllable generation. 
- The list should include single characters
- There should be an option to make illegal any words which cannot be parsed into syllables.

**Comment by jhartley1977** [comment]
would be nice if you could set a "frequency of occurrence" for the selected Phonemes ie… sound "ae" appears x% of the time.  This would allow for sound usage demographics from real world languages to be used... in other words "my "Celtic" language would still LOOK Celtic, through sound distribution, or my "Arabic" language would still SOUND Arabic, even though its not.

**Comment by player-354764547** [comment]
I suggest a tool similar to this page:
[http://www.zompist.com/gen.html](url)

**Comment by lrruiz** [comment]
I use Awkwords to get a feel for sounds that work good together. I like that it allows me to edit frequency of sounds, as well as clusters. It is buggy in the filtering, but having a wall of text running behind Polyglot gives me inspiration. Is a word generator still being considered?
![polyglotscreenshot](https://user-images.githubusercontent.com/59398032/111940412-e874fb80-8a8b-11eb-99a6-e9b356e0abdd.jpg)

**Comment by DraqueT** [comment]
Integrated Zompist tool: closing ticket
