### ISSUE TITLE
Etymology window not displaying

### ISSUE THREAD

**Issue by scottgit** [DraqueT/PolyGlot#602]
I'm on a Windows 10 machine, using the new 2.3 release of PolyGlot, and when I click on "Etymology" (in Lexicon entry), a "blank" window appears. If I hover my mouse over the window, some elements show up (like a + sign), but the window is not usable. Here is a screen shot having hovered over part of it:

![image](https://user-images.githubusercontent.com/2047892/43408425-3459e592-93d6-11e8-837f-e0a3a827f65d.png)

**Comment by DraqueT** [comment]
Thanks for the heads up! Just confirmed this is happening across the board and will need to be fixed. I can toss an email to you once it's corrected if you like (since I know you use the etymology feature a good bit with Ang-Yultz).
