### ISSUE TITLE
Error when saving

### ISSUE THREAD

**Issue by efhughes** [DraqueT/PolyGlot#604]
Whenever you try to save a dictionary an error pops up:

> Unable to save to file: C\Users\...
>
>Problems saving file C:\Users\...
>Unable to write font to archive: duplicate entry: conLangFont

However a file is still written and appears to save?

[PolyGlot 2.3 Win10 v10.0.17134]

**Comment by DraqueT** [comment]
There are a couple of things that can cause that, but the most common one
is running PolyGlot from within the zip archive (rather than extracting it
to its own folder), or running it from a folder where it does not have
write access. PolyGlot does try to write an ini file at times, and if it is
prevented from doing so, it can cause apparent errors in processes running
at the same time it tried to write.

Let me know if either of those things are what you're experiencing and if
this helps clear things up for you! ^^

- Draque

**Comment by efhughes** [comment]
@DraqueT 

It is fully extracted to its own folder on the desktop and I'm not seeing why it would not have write-access to the desktop, all the permissions for the files seem to have full permissions/write access. Upon further review however, it seems that saving works as expected the first time I save, but then trying to save *again* gives the error message, even if changes have been made or not.

**Comment by DraqueT** [comment]
Huh, alright... what version of Windows are you using currently (as in 7, 8, 10, etc)? I will spin up a copy of that on my end and see if I can't reproduce the error. Could you also let me take a look at a copy of the language file in case that is somehow involved? You can email it to me at draquemail@gmail.com.

Thanks for taking the time to write up the error report, it helps with the process of refining the program more than anything else when users participate like this! ^^

**Comment by efhughes** [comment]
I'm currently running Windows 10 Pro Version 10.0.17134 Build 17134

And just sent you the email! Hopefully it helps!

**Comment by yatenari** [comment]
I have the same issue - the first time after starting PolyGlot, saving works normally. The second time I get the same error message as above (Unable to save to file ..., Problems saving file ..., Unable to write font to archive: duplicate entry: conLangFont). This crops up with every file I load, the first save works, the second gives an error message. I looked at what fonts were selected, but it happens regardless of if it is the default one or another one chosen.
System is Windows 7 Professional 64-bit, if that helps.

**Comment by DraqueT** [comment]
@yatenari Would you mind sending a copy of your language to me at draquemail@gmail.com? I haven't been able to reproduce this error, and seeing it in action would help a lot.

**Comment by DraqueT** [comment]
As a heads up to everyone in this thread, I am working on a solution to this at the moment, but this bug will not affect saved data. It is trying to save the font twice and failing the second time (but continuing to write the rest of the language file).

Anyone who would like the beta version with a solution to this issue, please toss me an email.
