### ISSUE TITLE
Can't display the font properly

### ISSUE THREAD

**Issue by leo3065** [DraqueT/PolyGlot#605]
The machine was running Windows 10, and I'm using the new release of PolyGlot 2.3. After I imported my font and try to add some words, the font isn't displayed properly (which works both in Notepad and Office). Here is the Screenshot: 
![image](https://user-images.githubusercontent.com/31105200/43436452-28839a1a-94b7-11e8-9162-86514e9fd272.png)

**Comment by DraqueT** [comment]
Hrm, it looks like you're using ligatures in your font there, am I correct?
The latest version of PolyGlot does support them, but it's a newly
implemented feature, so this might be a bug.

Could you please send me your font so that I can take a look and see what's
going on? I'll definitely try and get this working for you. ^^

 - Draque

**Comment by leo3065** [comment]
Currently I didn't use ligatures but instead many zero-width characters so the different parts of the glyph stack together, but I might use ligatures to improve my font in the future. 
The zipped font is attached below. Because this is my first time trying to make a font so the input method might be weird. My conlang have a syllable structure of (C)V(C), where V can also be a diphthong. The characters in the font falls in one of the following categories: 
- Uppercase consonants: Onset
- Lowercase consonants: Coda
- Uppercase vowels: Non-final vowel in nucleus
- Lowercase vowels: Final vowel in nucleus
- \- : Block connector
- []: Zero consonant indicator
- <>: Consonant cluster connector (currently only for transliteration)

Consonants: p b t d k g f v s z c j m n q r l y h 
IPA: p b t d k g f v s z ʃ ʒ m n ŋ ɹ l j h 
Vowels: i a u e o w 
IPA: i a u e o ə 

So for example, the word **zinlun** the input would be **Zin-Lun** , **saed** would be **SAed** , **onsi** would be **[on-Si]** and **trens** would be **T>-Ren-<s** . 

[ConScriptnormal.zip](https://github.com/DraqueT/PolyGlot/files/2246098/ConScriptnormal.zip)

**Comment by DraqueT** [comment]
I am having some trouble reproducing this, but have a few ideas to help you. What I'm seeing below for the strings "qwerty" and "Draque" are here:
![image](https://user-images.githubusercontent.com/8284425/43487078-7e7a397a-94e3-11e8-88a1-83aa6d606b5c.png)

Try manually importing the font, which can be done by hitting tools->Import Font, then selecting your font file. Sometimes an OS will store multiple versions of a font in a way that confuses Java, and just selecting the font manually like this will correct the issue.

Let me know if this clears it up for you!

**Comment by leo3065** [comment]
Import font from the Tools menu and restart the program fix the problem. Thanks for your help!

**Comment by DraqueT** [comment]
👍 👍 👍
