### ISSUE TITLE
Unable to save to file

### ISSUE THREAD

**Issue by Pancakeddd** [DraqueT/PolyGlot#612]
Hey. I'm having problems using Polyglot. When i try to save my progress i get this error.
https://i.imgur.com/z0cY2Uu.png
Please tell me if you know how to fix this error or if you will fix it. Thanks!

**Comment by aozasori** [comment]
I encountered this problem, as well.
**Workaround**: When you want to save, go to "Lang Properties", and change "Conlang Font" to a different font than what it is currently set to. Now you should be able to save. You will have to do this every time, unfortunately. Hopefully this is fixed soon.

**Comment by DraqueT** [comment]
@aozasori Thank you for providing a workaround! I really appreciate this level of user interaction! This has actually been solved already in the newest beta (see below for how to get if you need it)

@Pancakeddd I actually have a beta version that I am sending out to users who are experiencing this problem. Please email me at draquemail@gmail.com and I'll give you access to it. Depending on how testing goes, it will be released officially within a few days.
