### ISSUE TITLE
Lexical Classes won't be deleted

### ISSUE THREAD

**Issue by yatenari** [DraqueT/PolyGlot#613]
Since Lexical Classes can be used as simplified filters for the declension setup, I am using them to determine which declension should be used. However, since I was still looking a bit at which ones to use and which words to put into what lexical class value, I was creating a few that I didn't need in the end. Since I have quite a bit of data in the declension setup entered depending on the lexical class, I can't remove the whole lexical class - however, the values themselves somehow can't be deleted.

In the values section for the given lexical class, the removal - apparently - works just fine using the minus button, but going back to the lexicon (or the declension setup), the values are still part of the list. And returning to lexical class, they are all back in the list, despite being removed. This results in a crowded list, especially if the plus/add button is clicked once too often - it results in empty parts in the list (which is strangely sorted at that).
The declension setup works just fine, but the list easily gets cluttered and if there is need for a multitude of different values for a given lexical class, it gets easier to accidentally select the wrong one.

**Comment by DraqueT** [comment]
Thanks for the heads up! Looking into it currently.

**Comment by DraqueT** [comment]
@yatenari Fixed this one. If it's giving you a lot of trouble, let me know and I'll hook you up with a beta of the latest build.
