### ISSUE TITLE
Cannot save more than one time

### ISSUE THREAD

**Issue by RainbowKaito** [DraqueT/PolyGlot#617]
It's easier to explain with an example: I open the program, open the language X and then save. When I try to save again, it gives me an error (image). If I close the program and open the language again, I can save again; the same thing if I open language Y and then go back to language X. 
![screenshot_1](https://user-images.githubusercontent.com/39446877/44303076-c207e600-a30d-11e8-88e9-68ef6c31f8eb.png)

**Comment by DraqueT** [comment]
Heyo! This bug is fixed at this point and I'm looking to get a release out
later this evening. If I'm not able to get it out in time though I'll link
you to a beta with this problem corrected! :3

- Draque

**Comment by DraqueT** [comment]
Didn't forget about you. Just realized I don't have your email address! If you would like a beta with this corrected, please send an email to draquemail@gmail.com
