### ISSUE TITLE
Version 2.3.3 Release

### ISSUE THREAD

**Issue by DraqueT** [DraqueT/PolyGlot#619]
- [x] Update manual with new features
- [x] Clean/Build + make new downloadable package
- [x] Write update text
- [x] Make release
- [x] Update update.xml with new information
- [x] Update index.html with new version num & link
- [x] Announce on conlangs sub
- [x] Announce on conlangs discord

**Comment by Ghost4Man** [comment]
I noticed the 2.3.3 release has the wrong version number in the title ("PolyGlot: Language Construction Toolkit 2.3.2") – "2.3.2" instead of "2.3.3". See [the release page](https://github.com/DraqueT/PolyGlot/releases/tag/2.3.3).

**Comment by DraqueT** [comment]
@Ghost4Man Thanks for the heads up! Corrected this.
