### ISSUE TITLE
Oversized INI file leads to "JVM not installed" message from frontend

### ISSUE THREAD

**Issue by snorepion** [DraqueT/PolyGlot#620]
Under certain circumstances (yet to be seen in debugger/analyzed), the INI file can grow to enormous sizes. When this happens, it prevents PolyGlot from opening properly, and the frontend reports that the JVM is not installed.

- [x] Figure out how to prevent the INI file from growing
- [x] Detect corrupted ini files
- [x] On detection of corrupted ini file, delete the file and inform the user that the problem has been encountered/corrected (but that their program settings will be missing)

ORIGINAL TEXT:
If I try to run `PolyGlot Frontend.exe`, it says the JVM isn't installed, even though it is. Then, if `PolyGlot.jar` is run directly, it just stays on the loading screen forever. The same thing happens regardless of the folder the program is run from. I tried updating Java, and that didn't work either. Any idea what could be causing this?

**Comment by snorepion** [comment]
I managed to fix this by deleting PolyGlot.ini, which had somehow managed to get bloated to 282 MB. The program regenerated the INI file to a normal size after I ran it again and closed it.

**Comment by DraqueT** [comment]
Thank you for both the heads up and including how you fixed this! Would it be possible retrieve the supersized ini file, zip it up and send it to me? I am really curious to analyze it and figure out how to prevent this from happening to other folks. If it zips small enough, you can send it to draquemail@gmail.com, and if not, maybe sharing via google or something?

**Comment by snorepion** [comment]
Thankfully, I backed it up before deleting it, so I'll send it over.

**Comment by DraqueT** [comment]
Got the file and isolated the issue! If this keeps coming up for you please let me know and I will be sure to get you a beta in which it is corrected.
