### ISSUE TITLE
Clarify to users all fields which consume/expect regex values & warn when users use regex characters in their scripts

### ISSUE THREAD

**Issue by scottgit** [DraqueT/PolyGlot#623]
1) Make sure the menu/tooltips alert users to any field that consumed regex values.
2) On save of the alphabetical order, alert the user if their script uses any characters that are reserved for regex

ORIGINAL MESSAGE:
Do an inventory of all places this applies and prepend tooltip text that alerts users meaningfully.

Some fields within PolyGlot consume and expect regex patterns. Most strings entered by users who do not care to use regex will act as exact-match fields, **however**, if the user includes characters in their character set including those which are consumed by regex, it will cause problems.

Clarify this to users in an appropriate and meaningful way.
-[ ] Catelogue every UI element which consumes regex
-[ ] Decide whether a label should be used to indicate regex requirements or some sort of field color change. (how would color change be reflected in upcoming night mode feature?)
-[ ] Implement

ORIGINAL USER TEXT:
This is a bug. I was attempting to define a romanization of my font's + sign character, but imputing the + character in the left column of the romanization dialog caused an error that disabled romanization and stated as well that the reason was:

> ... Dangling meta character '+' near index 2 
>^(+).*
>^

So since the + is a meta character for regex, it is not properly handling that symbol (and possibly other meta characters?) for romanization if a conlang font has another character defined for a standard metacharacter.

**Comment by DraqueT** [comment]
Heyo! Because it is a special character, you will need to escape it in your regex expression with a "\". Your regex expression shoul look like this: ^(\+).*

Hope this helps! :3

**Comment by scottgit** [comment]
In the romanization definition, there is no regex expression that I put (I'm just supposed to enter the character on the left from my font and then the romanized character(s) on the left. So the regex must be happening behind the scenes in the code.

**Comment by DraqueT** [comment]
Regex is always enabled for those fields, which I should probably give a better warning/explanation of in the program, yeah.

Oh shoot, I just realized that characters got eaten in my response there. If there's a + sign in character(s) or anything else that's a special character used by regex (such as a +), you'll need to have a backslash in front of it like this: ^(\\+).*

**Comment by scottgit** [comment]
Hmm. Okay. From a user perspective, it would be better if that was all handled behind the scenes invisibly, since the way those particular columns are laid out, the user is basically expecting to just enter characters, not regex code. So if you are using regex for the switching behind the scenes, then it would be nice if you did a check for special characters and add the appropriate regex code to make that character actual switch as the user expects.

But if at the moment I need to do that, then I still have the issue that at emailed you separately about That is, with my font using some of the keys used for regex, I do not have access to all the characters I need for regex entry; so how do I work around that? Maybe I need to make that a separate issue, but it seems like I need the ability, for any fields where I have to (or may be able to) enter regex, to switch between a standard font and my font so that I _can_ enter a regex expression.
