### ISSUE TITLE
App Scaling Support

### ISSUE THREAD

**Issue by ElsaTheHobo** [DraqueT/PolyGlot#625]
I run Windows 10. My screen resolution is 1920*1080, and the size is approx 16 inches diagonally. This can make text really small by default. To counter this, Windows 10 (and maybe 7 and 8? I don't remember) has an option to make apps bigger so that people can see things better. Polyglot does not seem to use this setting, and the text is very tiny as a result. I can change the conlang and local lang fonts to get around this, though the menu text still stays small. Please add app scaling size to polyglot.

Attached is a comparison between Github's font size and Polyglot's font size on my computer (the local and conlang fonts are default)
![image](https://user-images.githubusercontent.com/8405464/45317213-4c0b2f00-b507-11e8-93e5-f6010204a5d7.png)

Thank you for the program!

**Comment by DraqueT** [comment]
Heyo, as a heads up, I', closing this ticket since it's a copy of #531. If you would like to follow its progress, subscribe to that one. ^^

**Comment by DraqueT** [comment]
@ElsaTheHobo I think I have a fix for this, but I don't have access to any systems where the scaling bug appears. Would you be willing to help me test this out? :3

**Comment by ElsaTheHobo** [comment]
Sure, I'm down.

**Comment by DraqueT** [comment]
Just toss me an email at draquemail@gmail.com and I will send you a link to a beta copy to try out. ^^

**Comment by DraqueT** [comment]
Reopening the issue TO CLOSE IT! @ElsaTheHobo I will post a link to the latest build which corrects this issue via a new Windows frontend (included in download) shortly :3
