### ISSUE TITLE
Conjugations for pronouns

### ISSUE THREAD

**Issue by a22brad22** [DraqueT/PolyGlot#626]
So far, it seems (unless I'm using the software incorrectly) that verbs can only be conjugated at the root.
You're not able to include conjugations for different speakers (or at least not without insanely increasing the size of the list).

I would like to suggest using a table of tables format, as is often used on websites used for conjugating verbs. For example, this (extremely complex example) of Turkish verb conjugations. http://www.verbix.com/webverbix/go.php?&D1=31&T1=etmek

For example, users could select overarching categories (past, future, present), sub-categories for each one (continuous, perfect, imperfect, subjunctive), and then final modifiers (affirmative, negative). And finally, each group would have the ability to change the ending depending on the pronoun.

**Comment by DraqueT** [comment]
Heyo, thanks for the input here!

You're actually not the first person to ask for this, and it's something I've been thinking about for quite some time. A system like this is going to be included within the next one or two updates of PolyGlot. ^^

**Comment by a22brad22** [comment]
Haha I had guessed not; but I didn't see any requests for this except for someone asking for better structuring. 
Sweet work and thanks for the amazing software!

**Comment by DraqueT** [comment]
This was implemented quite a while ago with the auto-table generation update for the conjugation menu. Closing.
