### ISSUE TITLE
Allow copying entire sets of autogeneration items

### ISSUE THREAD

**Issue by snorepion** [DraqueT/PolyGlot#627]
In a conlang of mine, I'd like to have adjectives agree with nouns for case and plurality, but to do this, it seems like you have to manually copy every rule over. If you make it so the full list of autogeneration rules can be copied over, this makes it much easier.

**Comment by DraqueT** [comment]
This is actually possible in PolyGlot currently! If you highlight all the rules you wish to copy and right click, a popup menu should allow you to copy whatever you would like between parts of speech.

Let me know if this helps! :)

**Comment by DraqueT** [comment]
Closing this one. Let me know if it's still an issue.

**Comment by snorepion** [comment]
Oh, sorry. I had intended to comment on this, but I was busy and then forgot about it. 
You can copy multiple rules, but not multiple sets of rules, which is the problem. I.e., you should be able to copy multiple selections from this column:
![image](https://user-images.githubusercontent.com/24462989/46388039-33fe7980-c687-11e8-8cd8-ed32c63da25a.png)
