### ISSUE TITLE
Allow spaces in automatically generated pronunciations

### ISSUE THREAD

**Issue by miacomet** [DraqueT/PolyGlot#630]
Right now any word I enter that contains a space doesn't produce an auto-generated pronunciation. I'm unable to enter spaces in the Phonology window, so they don't render.

**Comment by DraqueT** [comment]
If I had the pronunciation generated for each element of the word, then added a space between the two halves of the pronunciation, would that work for you? For technical reasons I am not able to add spaces into the phonology section, but I could pretty easily modify the engine to account for words split by spaces.
