### ISSUE TITLE
Multiple Pronunciations

### ISSUE THREAD

**Issue by MC31415926535897** [DraqueT/PolyGlot#632]
Can we have a supported function where words can have multiple pronunciations based off of dialect? For example, there is f i sk and f i çk, both written as fisk and have the same meaning.

**Comment by DraqueT** [comment]
Heyo! Thank you for the suggestion here! What you're asking for is actually something that I have on my plate to implement already, although in a more complete way! Pronunciation for dialect is something that a number of people have expressed interest in, but a dialect can ultimately change *anything* about a language. It can change rules, it can change pronunciations, etc.

I'm working on a system that allows for the base language to have layers set on top of it that will modify specific elements of that language for a specific dialect, which can be created on top of the base language.

So. It will be a bit of time before this is implemented, but when it is, it will be a good bit more robust than just what you're requesting here! :3
