### ISSUE TITLE
"Java not installed" error when attempting to open a .pgd or frontend.exe

### ISSUE THREAD

**Issue by Soupcandle** [DraqueT/PolyGlot#644]
When I try to open a .pgd file directly, or run the frontend.exe, I get an error telling me to install java, despite it being already installed. If I open polyglot through the .jar file, it runs without issue. I have reinstalled both java and polyglot several times, and deleted the .ini file as suggested [here](https://github.com/DraqueT/PolyGlot/issues/620) but neither methods have had successful results. Is there any other fix for this issue?

**Comment by DraqueT** [comment]
Thank you for the heads up and for all the details given there! Can I additionally get the version of Windows you are running?

When I get back home from the weekend, I’ll look into this and see if I can’t get a fix out to you. ^^

**Comment by Soupcandle** [comment]
I'm running Windows 10. Thanks!

**Comment by DraqueT** [comment]
Consider this code:

ProcessStartInfo psi = new ProcessStartInfo();
psi.FileName = "java";
psi.UseShellExecute = true;
psi.RedirectStandardError = true;

psi.Arguments = "-version";
Process p = Process.Start(psi);
string strOutput = p.StandardError.ReadToEnd();
p.WaitForExit();

Then you should parse the string of output. This output normally looks like:

javac 1.6.0_27

**Comment by DraqueT** [comment]
@Soupcandle 
The bug should be corrected now! Toss me a message if you'd like the new frontend, although the new version of PolyGlot will be dropping very soon!
