### ISSUE TITLE
Pasting in text fields such as 'Definition' not working.

### ISSUE THREAD

**Issue by MDAMilroy** [DraqueT/PolyGlot#655]
PolyGlot Version 2.3.3
Macbook Pro 2011 Late, High Sierra (v 10.13.6 (17G4015))

I have been having issues when pasting into certain text boxes in the programme such as the 'Definition' box on the Word Quickentry and Lexicon.

**Comment by DraqueT** [comment]
Heyo! This is a bug that was found and corrected very recently. If you are still experiencing the trouble and would like a beta copy, please let me know!
