### ISSUE TITLE
Conjugations/Declensions Autogeneration Rule Order Reverts

### ISSUE THREAD

**Issue by KuroMaboroshi** [DraqueT/PolyGlot#660]
Hello DraqueT. I think I encountered a bug in the autogeneration rule dialogue in version 2.3.3.

The rule order reverts to an unwanted order upon re-entering the autogeneration rule dialogue. As a result, certain transformations are applied in the wrong order upon confirming any changes.

Setting them all to the intended order while in the dialogue before confirming the changes seems to work, but every minor edit to any part of the rules forces such a reordering, as upon reopening the window, the rules will be in the wrong order again.

**Comment by DraqueT** [comment]
Thank you for bringing this to my attention! I just confirmed that this bug exists. I'm gearing up for the next release and am glad to know about it before then. :)

**Comment by DraqueT** [comment]
Heyo! As a heads up, this issue is fixed now. If you need a beta version of that includes this fix for your work, please toss me an email at draquemail@gmail.com and I can hook you up! :3
