### ISSUE TITLE
Lexicon "Conjugations" call changes Conjugation/Declension Autogeneration Rule Order

### ISSUE THREAD

**Issue by KuroMaboroshi** [DraqueT/PolyGlot#670]
Hey DraqueT, thanks for the 2.4 update. :)

Just had a look over the newest version and have to report that I found a new bug regarding the Autogeneration Rule Order.

While the autogeneration rule window now seems to retain the changes between confirming and re-opening the window as I reported in #660 , the actual order of the rules as applied in the Lexicon still goes awry after a short amount of time.

The issue occurs when a word from the Lexicon is opened in the "Conjugations" view. Upon doing so, the order of rules as specified in the Autogeneration dialog changes. So far in my own tests it was always the rules applied to the word just viewed in this manner that were pushed to the top (but not necessarily retaining the assigned order amongst themselves either).

Minimum steps that reliably reproduce bug in my project:
-set up autoconjugation rules with multiple class values and have the rules matched by said values
-confirm rules and order via "Ok"
-switch to Lexicon view and open word conjugation of a word in the respective Type of Speech via "Conjugations" button
-return to Autogeneration window in Parts of Speech view

Let me know if you need any more details or perhaps files to reproduce the issue. :)

**Comment by DraqueT** [comment]
Thanks for the heads up! I will definitely look into this and add additional testing to make sure the issue stays tamped down... gotta figure out what makes them revert like that. X|

**Comment by DraqueT** [comment]
@KuroMaboroshi It's been a bit since you posted this, but if you are still available to help me reproduce, it would be much appreciated! I have not been able to recreate this issue, and I'm not certain whether it's due to me missing a step, or whether work that I've done on the declension system in the mean time has corrected the problem.

**Comment by TheLordOfAllMuffins** [comment]
Not the original poster, but I have also experienced this happening, and have recorded a video here: https://youtu.be/5Hk4f1HYGHI of how it occurs for me. First, I look a the declensions for a class IV noun, and that declension gets pushed to the second place in the list, then I look at a class V noun, and that declension is pushed up to above the class IV.

**Comment by DraqueT** [comment]
Thank you for making a video of this! I know this might sound odd, but
would you be free to talk over the phone about this? A number of people
have reported this bug and it only appears in very intermittent, seemingly
random times. If we could just take 5 or 10 minutes of higher bandwidth
communication time it might help track down this issue so I can finally
squash it.

Hope that PolyGlot is being helpful to you despite frustrating bugs like
this!

- Draque Thompson

**Comment by TheLordOfAllMuffins** [comment]
Sure, I could do something like that

**Comment by DraqueT** [comment]
Heyo. While I wasn't able to see this particular bug in action (although I watched your video, so I know it was happening sometimes), I recently fixed something very closely related to it. If you want to check out the latest beta build of PolyGlot (always available at: http://draquet.github.io/PolyGlot/ for the the Win/Linux/OSX) and check it out, please feel free to do so!

If I don't hear back in a week or so, I'll probably close the ticket at least temporarily. Hope the program is still working for you!

**Comment by TheLordOfAllMuffins** [comment]
The issue still unfortunately persists. Everything else isgreat, though!

**Comment by DraqueT** [comment]
Thank you for replying again! Reproducing this bug was making me grind my teeth until I had a breakthrough just now and found the exact code causing it. I'm whipping up a fix now and will let you know once the new beta build is up.

**Comment by TheLordOfAllMuffins** [comment]
Sweet!

**Comment by DraqueT** [comment]
All the builds are done/uploaded. Check out the latest beta build here!  http://draquet.github.io/PolyGlot/
