### ISSUE TITLE
Null pointer on save (need to recreate locally...)

### ISSUE THREAD

**Issue by DraqueT** [DraqueT/PolyGlot#671]
This one seems strange. Haven't yet been able to reproduce. Might need to get a before/after file from the user to try and track this one better.

FROM USER (serransk) ON REDDIT:
Hi Sedu, sorry for writing you but I'm creating a conlang in the new polyglot and when I am about to save I get a NullPointerException, so I can't save it D: Please help

Hi! I think I found "were" is the problem: I started again, imported the words from the excel and just after I saved it, and it saved. After each thing I was doing I saved it, and it saved normally. But then the custom conjugations came. I set the autoconjugator to verbs and it worked normally. The verbs conugated well and so. Then, I changed the conjugation of one verb (which is irregular) and just then I saved and the error appeared. For the sake of testing I returned the conjugation to the auto and then saved, and it saved normally.

So I guess the bug is somewhere around that.

I hope I helped

**Comment by SergioMejia2** [comment]
Hi! Here is the file without the custom conjugations and then you can try changing a conjugation to see if the same error appears to you.

Btw, I am u/Serransk

[Shala.zip](https://github.com/DraqueT/PolyGlot/files/2923622/Shala.zip)

**Comment by DraqueT** [comment]
Thanks for the test file! I'm still not able to get the null error to pop up. I want to make sure that I'm doing the exact same thing as you are t make it appear.

1) I open your file
2) I select a verb in the lexicon
3) I open the Conjugations grid for that particular word by clicking the button below
4) I click the Autogen Override checkbox
5) I change one of the entries
6) I click OK
7) I save the file.

Please let me know if you're following a different pattern there and if so, what I need to do so that I'm matching yours exactly. Thanks for the patience helping me to track this one down!

**Comment by DraqueT** [comment]
Scratch that! Just got it to reproduce. Not sure what I was doing wrong before, but it's happening now. Hot on the trail! :3

**Comment by SergioMejia2** [comment]
Oh! I was just going to send you a video of me doing the process and getting the error. But I'm glad you got to reproduce the bug. I'll hope you could fix it. I'll still use it because this custom conjugation is only in two verbs, so I can use it in the meantime without a problem. I'll tell you if I find other errors or new ideas

**Comment by DraqueT** [comment]
I'll be able to fix this for sure. I'm trying to find the optimum solution atm, but I already have a hackey way to correct it if all else fails.

**Comment by DraqueT** [comment]
Heyo! Solved the issue! Here's a link to the new jar (just replace the old one with this):

https://drive.google.com/file/d/1oJRvZXb84IlqRqjhd8thMRrIFVaflq8G/view?usp=sharing

The problem was really subtle... Your verbs have both dimensional and nondimensional forms. In this particular case, when you override the autogenerated forms and save with custom labels, the labels for the nondimensional forms will be saved (in a way that PolyGlot doesn't even need any more) as null values.

Thanks for the help tracking this one down!

**Comment by SergioMejia2** [comment]
Yes! Just worked more than fine!

Thanks!
