### ISSUE TITLE
Put an IPA translator

### ISSUE THREAD

**Issue by SergioMejia2** [DraqueT/PolyGlot#674]
Hi! I thought about this.
You already have a Pronunciation field in a word that fills automatically if Phonology was already put. So what about a new menu option where you type something (or copy, like a somewhat large text) and it outputs an IPA translation according to the Phonology given. It would be useful when somene wants to make the IPA of a text.

**Comment by DraqueT** [comment]
Solid idea! Absolutely going to implement that for the next version. Thank you for the suggestion! :)
