### ISSUE TITLE
How do I move chapters in grammar?

### ISSUE THREAD

**Issue by brunoczim** [DraqueT/PolyGlot#677]
Suppose I have this: a grammar chapter named Introduction and another, created later, named Overview. 
![image](https://user-images.githubusercontent.com/18701450/53822933-79351900-3f4f-11e9-99c3-024497643958.png)
Suppose I regret this order and I want to move Overview over Introduction. How do I do? 

I tried Ctrl+Arrows, Shift+Arrows and Alt+Arrows. Using on Linux.

**Comment by DraqueT** [comment]
Huh! That is not something that currently exists in PolyGlot. I definitely
need to add the feature in. Unfortunately, the way you currently would need
to do that is via copy/pasting the text. I'll include a new feature to
handle it in the next version, though. :3

Thanks for the interest in PolyGlot, and let me know if you have any other
good ideas or run into issues!

- Draque

**Comment by brunoczim** [comment]
Thank you for the attention! I do run into a few troubles sometimes, but it is possible to workaround. In this case, I believe the only possibility is to accept this order hahaha.
