### ISSUE TITLE
Add Font Refresh Option to Language Properties Screen

### ISSUE THREAD

**Issue by S0ZDATEL** [DraqueT/PolyGlot#678]
DEV COMMENTS:
PolyGlot retains and embeds fonts in its files. For this reason, automatically refreshing fonts to the newest version that an OS has access to is not expected behavior. HOWEVER. When PolyGlot searches for the font to embed, it returns the first match, rather than the most recent. To correct this:

1) When selecting the physical font file to embed, search ALL fonts within relevant folders, and make a list of those which match the font family. Of those, select the most recently modified.
2) Add a button below font selection which will refresh all fonts per the latest installed in the OS.

ORIGINAL USER TEXT:
Hello! This program is really great, even if there is some things that should be added. But I found a bug. I created a font for my conlang, installed it and used to create a language in this program. Then I changed my font, reinstalled it, and... program still uses old version of font. I tried different ways... I deleted font and installed it again. I used "Import font" button. It all didn't help. Even when I deleted my font, rebooted a system and started this program... it still have this font in fonts list. Even when it don't exist anymore. I solved it by using another name for font. I guess program somehow saves fonts by name and don't update it when it changed or even deleted.

**Comment by DraqueT** [comment]
Heyo, thank you for taking the time to write this up! Do you use Windows 10 by chance? If so, then I think I've found the source of this problem and can correct it...

**Comment by DraqueT** [comment]
In the mean time, try using the "Import Font" feature under the Tools menu. This will let you import the font file directly, and without relying on your OS to select the correct version.

**Comment by S0ZDATEL** [comment]
Yes, I'm using Windows 10.
I already tried to import fonts. It don't help.
