### ISSUE TITLE
Request the support of the Cyrillic alphabet.

### ISSUE THREAD

**Issue by S0ZDATEL** [DraqueT/PolyGlot#679]
I am Russian and I'm using Russian as my conlang's local language. But when I type definitions in Russian and then put mouse over words in lexicon, when it shows it like "[word] : [part of speech] : [definition]", it shows "тест : тест : &#1090;&#1077;&#1089;&#1090" instead of "тест : тест : тест". Definitions in Cyrillic shows incorrectly in popup string in lexicon.

**Comment by DraqueT** [comment]
Heyo! The font that is default for PolyGlot does not support all characters, so you'll need to switch to one that supports Cyrillic. If you go to the Language Properties menu, you'll be able to change that. Let me know if this helps!

**Comment by S0ZDATEL** [comment]
I tried and it don't help.

**Comment by DraqueT** [comment]
How are you entering the characters into PolyGlot? I have copy/pasted from Russian pages with just the base font and had success. I am not certain whether there's another way to enter them that makes this bug more apparent.

Let me know how you're entering the text and I'll see whether there's anything I can find on my end to help.

**Comment by S0ZDATEL** [comment]
I'm just typing it.

**Comment by DraqueT** [comment]
Are you using A Windows system? If so, what version, and are you using the default Russian keyboard? I will definitely try to track this one down and squash it if I can reproduce the bug.

**Comment by S0ZDATEL** [comment]
Yes, I'm using Windows 10 and standard Cyrillic keyboard.

**Comment by DraqueT** [comment]
Hello, sorry to have taken so long to get back to you. 

I have tested this extensively with all of the available Russian keyboards that are available by default in Windows 10 (beginning with the top choice, which has no region listed in parentheses). I was unfortunately not able to reproduce this bug. 

Are there any other special settings you are using when you type in Cryllic characters?

**Comment by S0ZDATEL** [comment]
No special settings...
Here is an examle of what it looks like.
![image](https://user-images.githubusercontent.com/32978558/59831737-107d7b00-934b-11e9-9c52-d31f56fd6e5a.png)
As you can see, instead of description there is characters` codes.

**Comment by DraqueT** [comment]
Thank you for the screenshot! That shows me exactly where the problem is. 

NOTE: This appears to only happen on Windows, not OSX or any Linux I tested for.

**Comment by DraqueT** [comment]
As a heads up, this is complete! If you want to check out a beta version, you can get the latest builds of PolyGlot here: https://drive.google.com/uc?export=download&id=1o9Htb31I8Flfgh8zNMKe7X4dEoE9YZuL
