### ISSUE TITLE
Add color fonts.

### ISSUE THREAD

**Issue by S0ZDATEL** [DraqueT/PolyGlot#680]
PROCESS:
- OpenType-SVG is the type I will be using (see https://www.colorfonts.wtf/)
- require new dev computer. Minimum of mac OS 10.14 or above for compatibility with the format.
- Test with Playbox font (https://colorfontweek.fontself.com/2018#playbox)

ORIGINAL USER TEXT:
I wish this program could display symbols in color if color is in a custom font. It will be very useful for my Colorcode.

**Comment by DraqueT** [comment]
What font format are you using for your colored fonts? This is a feature that has been on my mind for some time, but I have been waiting for a good industry standard to emerge before I implement compatibility in PolyGlot. 

I also need to make sure that the font standard that I choose in compatible with the Java Virtual Machine before I take the time to put it together. 

Thanks for your comments, by the way! :3

**Comment by S0ZDATEL** [comment]
I'm using Opentype font format.

**Comment by DraqueT** [comment]
I didn’t know that opentype could encode for characters with color information yet! Could you please send me your color font? I will start experimenting with support as soon as I get back to the US next week. :3

**Comment by DraqueT** [comment]
Closing this for now. Java will support color fonts once its font renderers are updated to do so, but my code will not affect it. Probably J15 or higher.
