### ISSUE TITLE
Conjugation Infixes: Add example dictionary and update manual to better illustrate how this is done

### ISSUE THREAD

**Issue by Bubtottle** [DraqueT/PolyGlot#681]
The Conjugations/Declensions Autogeneration regexes don't respect capture groups (so far as I can see). Having capture group support would really streamline the creation of infixes.

e.g. Word forms might be [a-z]*-[infix]-[a-z]*. This could be specified by replacing ([a-z]*)-([A-Z]*)-([a-z]*) with \1-\2[new infix added]-\3

**Comment by DraqueT** [comment]
Heyo! I am going to be out of the US until next week, but I haven’t forgotten you here. I suspect that this has to do with idiosyncrasies of how Java interprets regex, so you might have some success looking those up and seeing if there are variation on the patterns you have there. 

I’ll take a look when I’m back though and see if there is a deeper issue at play here.

**Comment by DraqueT** [comment]
Heyo! If you are still around/working on this, could you send a copy of the language file where an example is set up for me to look at? At this point I am 95% sure this is just an issue of Java's regex interpretation, but I want to take a last look at it to make sure. My email is draquemail@gmail.com 

Thanks, and I hope PolyGlot is still helping you with your work!

**Comment by DraqueT** [comment]
Heyo! Sorry to take so long to get back to you, but this should currently be supported in PolyGlot! It is non-obvious, as the notation that is accepted by Java's regex system is a bit nonstandard, so I have put together an example dictionary, which you can find here:

https://drive.google.com/uc?export=download&id=1QjzKDgRA9qxU-RDULsI-PiG6y3unpHWS

I'm closing the ticket now, but feel free to post with any additional questions or comments!
