### ISSUE TITLE
A need for autogen clearing/erasing in bulk a rule

### ISSUE THREAD

**Issue by scottgit** [DraqueT/PolyGlot#683]
Plan:
Add two additional menu items to the right click dropdown for rules.
1) Delete from dimension. This deletes all instances of a given rule from a dimensional value in the same manner as they were added initially.*
2) Bulk delete rule. This deletes all instances of the rule found in all dimensions.

* Match on all properties within the rule, including label, regex, number of transformations, and equality of all transformations. Override isEqual on the rule object to do this.

ORIGINAL USER TEXT:
There needs to be a way to reliably "clear" rules from an autogen. That is, I had a rule that I created for "plural" forms (one dimension). I propagated that to all forms of the plural (you may recall my language has over 11,000 word forms in a single conjugation [very regularly produced, so it is really not that many "forms" a speaker would need to memorize], and 1/3 of those are related to a plural form). 

The copy did not occur properly, so I need to clear those. I thought that if I went and "erased" the "plural" dimension from a word on the Conj/Decl Setup, and then had it "Clear Deprecated Values" that it would "remove" those rules (actually, I thought just erasing the dimension would do the trick, but I tried the clear deprecated also). But instead, after saving (even exiting) and then remaking the "plural" dimension in the Setup, when I go back into the Autogen rules, the old "plural" rules are still _attached_.

Now I suppose that part of the issue is that once the rule is copied, the system does not have a way to know that _that_ rule is specifically tied to the "plural" dimension. So it may be that being able to associate a "rule name" to a specific dimension(s) could help control that, so that if a dimension is deleted, the rule goes away in all forms (permanently), as it must be taking up "space" in the language file to store rules that are meaningless with the dimension gone.

But really, what I need is a way to mass clear a rule by the _rule name_. So if I could tell Autogen to "erase" all rules named "Add Plural Mark" then I would be "set" for clearing any inaccurate copies of a rule (without even having to try and mess with removing the "plural" from the setup of a word, which is best left untouched in this case). This could be added to the right-click menu where the copy options are, only create a "delete all instances of this rule" or some such language.

**Related to this** is an ability to _overwrite_ a prior rule. I found that if I try to "recopy" the same rule name with new values, it creates two rules _of the same name_ in the copied instances, when I would expect a rewrite of the rule (both in selection RegEx and transformations).

**Comment by DraqueT** [comment]
Are you free to do a phone call for this one at some point? There's some complexity to this one that I absolutely want to get right the first time. Like with other issues, I'll obviously let you have a beta with the fixes prior to the next release.

**Comment by scottgit** [comment]
Yep. Sent phone number to your email.
