### ISSUE TITLE
Exit and "save" not saving or exiting (intermittently)

### ISSUE THREAD

**Issue by scottgit** [DraqueT/PolyGlot#684]
ISSUE TEXT:
The issue first described by the user seems to be highly intermittent. Unable to reproduce on phone call. Possibly corrected by another ticket that has been committed since the last release?

Leaving open in case others run into the issue. Close if unable to find/reproduce before next release and no other reports crop up.

ORIGINAL USER TEXT:
I've noticed an inconsistent case of going to the file menu and click "Exit" and then choosing the "save" option does not have the program "save" (and does not exit). It "hangs" (sort of) on the save command, showing a busy icon for the cursor, but not ever putting up the dialog saying that it completed the save, and so never exiting. 

Yet it is not totally "hung," either, as I can still do program functions; so I can go to "Exit" again and click "No" on the save option and it will exit me (without having saved of course), or select other program functions.

I have not been able to track what circumstances cause it. Some possible culprits:

1. It may be switching to another program and then back to PolyGlot.
2. It may be working with the conjugations in some way (whether in setup or autogen) since those two areas were what I was exclusively working on when it occurred.

**Comment by DraqueT** [comment]
Could you please send the language file to me that makes this happen? I have done significant modification of the saving mechanisms specifically to speed things up and prevent hanging like this in v 2.4, but I might have overlooked something.

As always, thank you for taking the time to write up bug reports!

**Comment by scottgit** [comment]
Sent file to your email.
