### ISSUE TITLE
NullPointerException Trying to Save Project After Specific Actions

### ISSUE THREAD

**Issue by brunoczim** [DraqueT/PolyGlot#686]
Reproducible steps:

1. Create a new project
2. Create a new part of speech (say "Verb")
3. Add two dimensional conjugation categories (say "Tense" and "Voice")
4. Add some dimensions to those categories (say "Present", "Past" ; "Active", "Passive")
5. Add two non-dimensional conjugation categories (say "Infinitive" and "Participle")
6. Add a word and assign it to the created part of speech (say "Walk" belonging to "Verb")
7. Open conjugations of the word
8. Mark the conjugations as "Autogen Override" (I think this is the way of introducing irregularities)
9. Try to save the project in whatever file.

You will get a NullPointerException trying to save it.

I believe having one dimensional category, one non-dimensional category, and then trying to have an irregular word is enough to replicate, but I haven't tested.

**Comment by DraqueT** [comment]
Heyo! Thank you for taking the time to write up all of these steps! I really appreciate it when people do that to let me know that something is wrong.

I have a solution to this right now. If you would like a beta of the next version f PolyGlot where this is corrected, toss me an email at draquemail@gmail.com and I can get the to you. ^^

**Comment by DraqueT** [comment]
Closing issue due to being addressed in alternate ticket.
