### ISSUE TITLE
What is the auto conjugation regex for the beginning of the word?

### ISSUE THREAD

**Issue by basilstein** [DraqueT/PolyGlot#687]
Hey sorry this isn't really an issue more of a question which I couldn't find on the help page.

I'm making autoconjugations on verbs and such, and as '$' is the symbol for finding and replacing something at the end of the word, or just putting something at the end of the word; what is the symbol/character to symbolize when what you're asking for or the location you're putting something is at the beginning of the word?

**Comment by TheLordOfAllMuffins** [comment]
The ^ character represents the beginning of a string (or in this case, word) in regular expressions.

**Comment by DraqueT** [comment]
@Lordofallmuffins is correct! Thanks for fielding this one for me. :3

**Comment by DraqueT** [comment]
Closing this due to answered question.

**Comment by S0ZDATEL** [comment]
But it don't works correctly...

**Comment by DraqueT** [comment]
The regex for the transformation should simply be the character ^. Nothing else should be there. The replacement can be whatever you are looking to prefix. If you’re still having trouble after you take a look there, you can send me the language file you’re working with to draquemail@gmail.com and I would be happy to check it out for you. ^^
