### ISSUE TITLE
Blank word classes populating list

### ISSUE THREAD

**Issue by bayden-woodland** [DraqueT/PolyGlot#694]
When creating a list of values for a lexical class, sometimes blank values will be added to the list and cannot be removed. It seems that the blank values are created when a value is created, nothing is typed in it, and then it is removed.

Here is the list with the blank values in their favourite spots:
<img width="307" alt="Screen Shot 2019-04-17 at 7 23 53 AM" src="https://user-images.githubusercontent.com/12058957/56295682-ff618500-60e1-11e9-9323-5f83cc087056.png">

Here the blank values have been removed using the minus button:
<img width="308" alt="Screen Shot 2019-04-17 at 7 24 10 AM" src="https://user-images.githubusercontent.com/12058957/56295722-0d170a80-60e2-11e9-8834-a07b6220daa2.png">

Here we go to a different tab, then come back:
<img width="138" alt="Screen Shot 2019-04-17 at 7 24 16 AM" src="https://user-images.githubusercontent.com/12058957/56295766-1acc9000-60e2-11e9-908a-49742fe4f046.png">
<img width="140" alt="Screen Shot 2019-04-17 at 7 24 20 AM" src="https://user-images.githubusercontent.com/12058957/56295770-1c965380-60e2-11e9-9576-55b182be857a.png">

And when we return, the blank values have returned as well:
<img width="300" alt="Screen Shot 2019-04-17 at 7 24 25 AM" src="https://user-images.githubusercontent.com/12058957/56295807-29b34280-60e2-11e9-861d-6dc4ac1aea53.png">

**Comment by DraqueT** [comment]
Thanks for taking the time to write this bug up! I have just confirmed that it's an issue. I'll get a fix in place and hopefully a beta version that can clean up your language file properly.

**Comment by DraqueT** [comment]
I have a corrected beta where this is no longer an issue. Toss me an email at draquemail@gmail.com and I'll be able to get you a copy.
