### ISSUE TITLE
Disabled wordforms show up in published pdfs

### ISSUE THREAD

**Issue by jliese** [DraqueT/PolyGlot#700]
When disabling a wordform in the autogeneration feature, the conjugation still shows up in the published pdf. The corresponing fields are empty in PolyGlot.

**Comment by DraqueT** [comment]
Thanks for the heads up! Just confirmed this bug and will address it. Send an email to draquemail@gmail.com if you’d like a copy of a beta in which this is corrected. :3

**Comment by DraqueT** [comment]
I have attempted to recreate this bug and not had success. Could you send me a copy of the language file you're printing to PDF from so I can see this bug the same way you are? Thanks again for taking the time to report the bug! This is the only way I am able to know that there's something wrong with PolyGlot.

**Comment by jliese** [comment]
I've attached a reduced PolyGlot file and the output pdf.
![Screencap](https://user-images.githubusercontent.com/4267128/59292622-b65f2480-8c7d-11e9-90be-e632f33c6ac6.JPG)
[.pdf and .pgd file](https://github.com/DraqueT/PolyGlot/files/3277711/example.zip)

I noticed that for some word, it *does* omit the form, but not for others.

**Comment by DraqueT** [comment]
Thanks for posting that! It’s much easier to track down bugs when they’re right in front of you. ^^

**Comment by DraqueT** [comment]
Just finished this one! Let me know if you're interested in a beta version in which this is corrected! But if you decide to go that route, be aware that it's still a beta, so there might be stability issues that still remain in it. This next version has a bunch of under the hood upgrades.
