### ISSUE TITLE
Unable to Load JavaFX on Windows

### ISSUE THREAD

**Issue by elaitha** [DraqueT/PolyGlot#720]
I just downloaded PolyGlot 2.4 and when I run the .jar file it has a popup saying that it is unable to load JavaFX. I have Java 8u211 installed as well as the JDK 12.0.1 in case that was also necessary. I am on a Windows 10 computer and Java seems to work for other programs. I don't know why this isn't working; do I need to manually install JavaFX?

**Comment by DraqueT** [comment]
Thanks for making a ticket! This actually makes me realize that I should have a custom message that pops when windows users open PolyGlot without the frontend. Starting in v 2.5, it addresses high resolution issues that occur in windows (making it super tiny).
