### ISSUE TITLE
Problem with Windows frontend in 2.5

### ISSUE THREAD

**Issue by babelfish** [DraqueT/PolyGlot#740]
I downloaded 2.5 today. I have the AdoptOpenJDK runtime installed. The current method of detecting java by looking up a registry key doesn't work with it. I'm assuming that's a key that's set when installing the Oracle JRE.

Although, I also tried manually creating a value at the appropriate location in the registry and I still get the error message that java isn't installed. To make it even weirder, I created a project in visual studio and copy and pasted that java check in like so:

```cs
        static void Main(string[] args)
        {
            if (!testJavaInstalled())
            {
                Console.WriteLine("Java is not installed. Please download/install the JVM (https://java.com/download) to use PolyGlot.");
            } else
            {
                Console.WriteLine("Java found.");
            }
        }

        private static Boolean testJavaInstalled()
        {
            RegistryKey rk = Registry.LocalMachine;
            RegistryKey subKey = rk.OpenSubKey("SOFTWARE\\JavaSoft\\Java Runtime Environment");

            string currentVerion = subKey == null ? "" : subKey.GetValue("CurrentVersion").ToString();

            return !(subKey == null || subKey.Equals(""));
        }
```

When I run that I get "Java Found." This is madness. Is it possible the 2.5 release archive has an older version of the frontend?

**Comment by babelfish** [comment]
Well, I figured out why the registry key was found in my project but not the frontend. I'm on 64 bit windows and apparently there are separate 32 bit and 64 bit registries, and the default for me is 64 bit, but the frontend project is configured to build a 32 bit application which can't read from the 64 bit registry.

Now I just need to figure out how to get it to detect jfx...

**Comment by babelfish** [comment]
If anyone else is a masochist and ends up trying to run this on Windows with OpenJDK and OpenJFX, you'll need to open the 32 bit registry editor (C:\Windows\SysWOW64\regedit32.exe) and create CurrentVersion="anything" at "HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment". You'll also need the OpenJFX 11 SDK. Then set the following environment variable:

JAVA_TOOL_OPTIONS=--module-path=%PATH_TO_JFX_SDK%\lib --add-modules=ALL-MODULE-PATH --add-exports=java.desktop/sun.awt=javafx.swing

I still get one load error when it starts up, but it appears to be working.

**Comment by DraqueT** [comment]
Thanks for all the legwork you did here! I am super torn on whether to correct this and release a minor update to correct the bug or just wait for v 2.6... I am moving to Java 12, and am hoping to get it packaged in a way that will just pack everything needed into a single platform dependant file (so you won't even need to have Java installed at all to use it).

**Comment by DraqueT** [comment]
The Windows frontend is deprecated as of the upcoming PolyGlot 3.0. It now uses platform dependent images, eliminating the source of this problem. @babelfish If this is still a problem for you, let me know and I can hook you up with a beta.

**Comment by babelfish** [comment]
Nah, I can wait for the actual release. Thanks, though.
