### ISSUE TITLE
The Logographs are completely broken

### ISSUE THREAD

**Issue by Conallia** [DraqueT/PolyGlot#741]
**(I only got github to report this so I have no idea what I'm doing)**

Every time I add a new reading for a logograph, the first logograph in the lists's reading gets deleted.

I tried deleting a reading for a logograph, but everything disappeared and I was left with a useless blank polyglot.

Also, saving times have been increased, and I think it might be because of the large-ish image files i'm putting in for the logographs. But I already have too many to replace them with lower quality versions, so maybe it could reduce the file sizes to make saving faster.

**Comment by DraqueT** [comment]
Heyo, thanks for contacting! 

Could you lay out the exact steps you're taking when you see the reading vanish? I have not been able to reproduce it so far, but there might be a particular sequence which makes it happen. Here are the exact steps I am taking:

1) Open PolyGlot/go to logographs
2) Click the + button beneath the logoraphs list
3) Enter a name for the logograph
4) enter an image for the logograph
5) click the + button beneath the readings list
6) enter new reading

If I navigate away from the logographs and back again, it seems to work.

NOTE: I *have* found some weird behavior surrounding deletion/recreation of readings and I'm wondering whether that's related to the troubles you're experiencing. Will be working to correct this and I'll get you a fixed build once we get this working. :)

**Comment by DraqueT** [comment]
Check out the beta here: https://drive.google.com/uc?export=download&id=1o9Htb31I8Flfgh8zNMKe7X4dEoE9YZuL

Let me know if this addresses your issues!

The logographs section is the one most in need of a rehaul, and some of the last original menu that remains from way back when. It's something I should really take the time to revamp once I've gotten through some of the architectural stuff that needs to be addressed.

**Comment by Conallia** [comment]
Hi, I've been playing around with the beta a bit and found out that it only fixed 1 glitch. Which is good, however the glitch where it removes the reading of the first logograph in the list still occurs. 

> (The glitch where it goes blank is  fixed!!)

 Here are my steps when it deletes the reading:

1. copy and past the word into the lexicon
2. click plus on in the logograph tab
3. past the word into the name
4. click plus in reading
5. paste in the reading
6. copy a photo
7. click the clipboard button.
 Then I have to paste in the reading of the first logograph.
If you need it, I could attach a video.

**Comment by DraqueT** [comment]
@Conallia It turned out this was the symptom of something completely unrelated that was corrected in another bugfix. Please let me know if you're still having these problems and I can link you to a beta in which this has been orrected! :)
