### ISSUE TITLE
PolyGlot doesn't save my custom font

### ISSUE THREAD

**Issue by CactusBack** [DraqueT/PolyGlot#743]
Hey, first of all, thank you for the amazing tool! I discovered it only a couple of days ago but I'm really having a blast using it to organize data on my conlang.

However, I'm having a problem with making PolyGlot save my custom conlang font. PolyGlot doesn't see it in my installed fonts, so I have to import it through the 'Tools' tab. After I import it, it works great but if I close the program and launch it again, the conlang font is set to the default Charis SIL.

Is there a way to fix this, so that every time I load my conlang file the font would load as well?

I'm using PolyGlot ver. 2.5 on Windows 10.

Here's a link to an archive with my font and conlang file - [download](https://drive.google.com/file/d/1leKkbsRPdpCT57rxAWaAgpvHDBIEJp8V/view?usp=sharing).

**Comment by DraqueT** [comment]
Thank you for the heads up on this bug! It's one that will definitely be a high priority for me soon. I am currently upgrading from Java 8 to Java 12, which is a huge ordeal, but once that is over with, I will get back to quashing bugs regularly.

Thank you for providing both the font and the conlang file for me to experiment with, though! That will help me enormously when I'm able to correct this for you.

**Comment by CactusBack** [comment]
Thanks for the reply! Looking forward to the fix.

**Comment by DraqueT** [comment]
I've just completed the fix for this! @CactusBack your script looks fantastic, by the way! If you're still using PolyGlot and would like a preview beta copy of 3.0, let me know and I'll get you in on it!

**Comment by CactusBack** [comment]
@DraqueT thanks man! Sure, would love to test the beta.

**Comment by DraqueT** [comment]
@CactusBack Check out the newest version here: https://send.firefox.com/download/3740b6a03b816d63/#-LfrRSXK9D6LJDyf_wmVlw

Got its own fancy installer and everything!

**Comment by CactusBack** [comment]
@DraqueT just tested the new version - the bug is indeed fixed and so far no other problems for me. Thank you!
