### ISSUE TITLE
Conjugations/Declensions autogeneration reverts to older version still.

### ISSUE THREAD

**Issue by chricker05** [DraqueT/PolyGlot#745]
Hey DraqueT, I know back in February this was supposed to be fixed, but in my current(I've checked, it's current.) version of PolyGlot, this bug still takes place. My nice regex codes will almost always revert to what they were before if I do not save the .pgd file directly after editing the rules.

**Comment by DraqueT** [comment]
Thanks for the heads up! This is a super persistent bug that I have been trying to squash for quite some time. If you ever notice a particular pattern to what makes it happen, please let me know. I have not been able to reproduce it to my satisfaction in the past, despite extensive testing and refactors.

**Comment by DraqueT** [comment]
To reproduce this: 

1) Create a conjugation/go to the autogeneration setup
2) Create at least two rules and save them.
3) Close the autogeneration setup
4) reopen the autogeneration window
5) Modigy the regex or replacement of a rule
6) Select the other rule
7) Close the window (X or OK) WITHOUT switching anything else

This will revert the rule to its prior state.

**Comment by DraqueT** [comment]
I've found a solution to eliminate the specific bug that is outlined here. Please let me know if you're interested in a beta version of PolyGlot to make sure that this is corrected for you as well. This particular bug is one that has been a thorn for quite some time, and I'm really looking to quash it once and for all.
