### ISSUE TITLE
Maintain filtering after window loses focus

### ISSUE THREAD

**Issue by TheLordOfAllMuffins** [DraqueT/PolyGlot#748]
Currently, when I use the search/filter dropdown to search for some words and then defocus the window, e.g. to copy them over to a document, the filtering disappears and all words are shown again, which is rather inconvenient with even a moderate dictionary size. It would be very nice if the search filtering remained regardless of window focus.

**Comment by DraqueT** [comment]
Thanks for bringing this to my attention! Once it’s addressed I’ll give you a link to an updated beta build.

**Comment by DraqueT** [comment]
This bug was tied up with another one that got fixed elsewhere. @TheLordOfAllMuffins if this is still a problem for you, let me know and I can get you access to an early beta copy in which it is corrected!
