### ISSUE TITLE
You have to click the wrong button to remove from the Grammar menu

### ISSUE THREAD

**Issue by Tripazzy** [DraqueT/PolyGlot#749]
As the title says, when you click the "-" at the bottom of the screen and then PolyGlot asks "Really delete? This cannot be done" you have to click No to delete, instead of Yes.

**Comment by DraqueT** [comment]
Thank you for the heads up! I really hope this didn’t cause anyone to lose work. X|

**Comment by DraqueT** [comment]
Also, I love your icon! Three good things put into a good shape. ^^
