### ISSUE TITLE
Logography feature glitch

### ISSUE THREAD

**Issue by AutumnOstrich** [DraqueT/PolyGlot#755]
I have a language that uses a logography and the feature has been failing continuously. Frequently when introducing new logographs to the library, it will change the meaning of another, either bumping all definitions down in the list or duplicating the definitions of one to another. Sometimes it deletes the meaning altogether.

**Comment by DraqueT** [comment]
Yikes, that is really bad. I will take a look at this bug asap and get back to you. In the mean time, are there any particular steps that seem to make this pop up frequently?

-Draque

**Comment by AutumnOstrich** [comment]
The glitch that bumps the meanings of the logographs down happens whenever I try to delete a logograph and the meanings deleting themselves and duplicating happens while adding new entries into the library. A error that I forgot to mention is that the program will permanently freeze if I try to delete a reading.

**Comment by DraqueT** [comment]
Thanks for the details! I've just completed a huge chunk of work, and I'll drop some cycles into this tomorrow. If I can fix it, I'll toss you a link to a beta of the Java 12 version of PolyGlot that I've been working on!

**Comment by DraqueT** [comment]
Heyo, @AutumnOstrich ! This has been corrected. If you're interested in checking out a beta in which this is working, let me know what OS you are using and I'll link you to a binary.

**Comment by AutumnOstrich** [comment]
Thanks, I am running windows 10.

**Comment by DraqueT** [comment]
Check out the newest beta here: https://send.firefox.com/download/3740b6a03b816d63/#-LfrRSXK9D6LJDyf_wmVlw

Got its own fancy installer and everything this time! ^^

**Comment by AutumnOstrich** [comment]
Thank you so much for the quick fix and reply.

Tyler Nazarko
________________________________
