### ISSUE TITLE
Pasting a tab into the grammar breaks rendering

### ISSUE THREAD

**Issue by chiligy** [DraqueT/PolyGlot#783]
when a tab character is pasted into the text editor of the grammar section the text does not render incorrectly the rendering seems to stop for things that are not forced to being rendered (for example the buttons and other things that when hovered over update the rendering)

**Comment by DraqueT** [comment]
Thank you for bringing this to my attention! I've corrected this bug now. If you would like to check out the latest beta build that includes this fix snag it from the link here: http://draquet.github.io/PolyGlot/
