### ISSUE TITLE
"Java is not installed" when launching with the Frontend executable

### ISSUE THREAD

**Issue by TheLonelyAdventurer** [DraqueT/PolyGlot#785]
When trying to open PolyGlot Frontend.exe I get a "Java is not installed" error, even though I actually have two versions of Java installed, 12 and 8 both Oracle JDK.

I tried changing the JAVA_HOME to version 8 but didn't work.

It works if I launch the jar manually from the cmd with java -jar.

I saw there is a similar issue here #644 I'm not sure if it's related, because this is a new plain installation (just replaced anything in the folder and removed also the .ini).

Is there any fix for this?

**Comment by DraqueT** [comment]
Heyo! Honestly, I think your best bet might be to move to the beta which is available now. Java 8 (what all prior versions have run on) is starting to truly show its age, so all future versions will be Java 12+. You can snag the beta build at any given time here: http://draquet.github.io/PolyGlot/

Just make sure that you download the one for your OS. From here on out, there will be separate installers. Please let me know if you run into any other problems!

**Comment by TheLonelyAdventurer** [comment]
The beta build works just perfectly out of the box. I also noticed that font scaling now behaves just fine.

Thank you for developing this software!
