### ISSUE TITLE
Auto Conjug. Bug: Switch of Rule Order smt causes Replacement of Transformations

### ISSUE THREAD

**Issue by Rially** [DraqueT/PolyGlot#789]
Good day!
_I've experienced a re-occurring phenomenon within the auto-conjugation setup that I believe to be a bug. It's been very long since I've written a bug report, therefore, I ask you to be forgiving if I forgot to include pertinent information._

First, here is the file in which this happened + my last backup in which this hadn't happened. (It's ancient but probably sufficient to see the issue.)
[Link to Files](https://gofile.io/?c=loK4km) (Pw: Polyglot)

The N file is the file with the issue. You will find the issue in the **future** forms of the **verb** auto-conjugation. Everywhere one of the rules after the mo- rule has had all of its transformations replaced with the mo- transformation. The transformations that should be there can be found in the present or the backup file.
I wouldn't bother you with this except it happened again, and I know have a clue when it happens.
When trying to fix the issue by simply **copying over** the rules from the present, it once more happened when I tried **up-ing the newly pasted rule**. I had done this twice before successfully, but this time when I pressed the "up" button, the rule didn't go all the way to the top, and another rule was replaced by its transformations. When I checked the other tabs, it had happened everywhere (this time even in the present).
_Unfortunately, panic overcame me, and instead of saving it as a new file, I closed the file without saving and to my great joy, everything was still fine in the old file. I will now start fixing this once more and if this should happen again, I will save the file with a new name and upload it as well._

If you could tell me if perhaps I am using the program wrong and should follow a particular order of steps to prevent this, I would be very grateful for the information. Thank you very much for this great program!

**Comment by DraqueT** [comment]
Heyo, just wanted to give you the heads up that this bug was recently found/fixed! If you want to check out the newest Beta build in which it's corrected, you can do so over here: http://draquet.github.io/PolyGlot/

Just be sure to snag the appropriate one for your OS. With 3.0 and above, PolyGlot is platform dependent. The downloads are below the link to ver 2.5 on the page linked.

**Comment by Rially** [comment]
Thank you very much, I'll be doing that before next changing conjugation rules.
Please excuse my ignorance, does platform-dependent mean that I will be unable to use my saved files across platforms? And if that were the case, will there be a platform-independent version in the future?
