### ISSUE TITLE
Change license to a software license

### ISSUE THREAD

**Issue by alexandercrypto** [DraqueT/PolyGlot#808]
The current license isn't a software license and also isn't libre. Creative commons licenses are heavily discouraged for use in software (https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software), since they are incompatible with many use cases which make open source so amazing.

The CC-BY-NC also isn't libre, since people cannot sell it in any regard, not even physical copies for educational use. This specifically makes it incompatible with many software licenses, meaning PolyGlot couldn't be integrated into other open source software.

I suggest moving to the GNU GPL, reasoning:

- the GNU GPL is widely used and understood
- GPL software is accepted for integration into Debian (Ubuntu), Arch, and other package repositories
- GPL software can be used as a library in other GPL licensed projects 
- the GPL is copyleft, meaning any derivatives must be licensed under the GPL, so the code will remain open source forever
- any modifications to GPL software must distribute the source code on request
- GPL licensed code can be shared no matter what

The last two points give a sort of non commercial effect, because if anyone tried to sell the software someone would buy it and request the source then provide it for free for everyone else, making the sale impractical. The copyleft also prevents any meaningful attempts to sell the program since any modifications must be under the GPL, meaning that the source code must be given on request. This is not to mention the existence of the PolyGlot website or repository.

The GNU LGPL would also be a great choice that provides all the same benefits, but people could also link to PolyGlot as a library without needing to license their code under the GPL.

Changing the license to a libre software license for the next release (2.6) which reintroduces Linux support could be an appropriate and nice bonus for the update.

**Comment by DraqueT** [comment]
Thanks for pointing this out to me, licensing isn't something that's really my specialty. I'll have to update this. I'm curious though, is there a GPL license that prohibits sale? I realize that prevents PolyGlot from being packaged with retail software packages, but that is more of a feature to me than a bug. While PolyGlot is free for noncommercial use, it's not something I'm ok with people selling.

**Comment by alexandercrypto** [comment]
To my knowledge there are no noncommercial software licenses which are considered legally strong. Even if there were, noncommercial software is considered to go against the tenets of freedom which are upheld by the free and open source community. This means that even if a legally strong noncommercial license did exist it would go against the core ideals of open source and would thus not be accepted into a wide range of software repositories.

I fully understand your desire for a noncommercial license and the desire to protect your work from being obscured or tainted by evil actors, I faced those fears myself quite a number of times. However, a noncommercial license does little to protect a work from these actors for a number of reasons. In the end, the most useful and powerful thing which deters bad actors from stealing works or selling works is community.

Let's go through an example of things which would probably come up in a legal case
- StealSoft is the defendant, accused of violating copyright and terms of licensing by selling the software
- The software is noncommercial, so they legally cannot sell it in any regard
- Assuming a good enough lawyer is used, the plantiff (you) wins

Now, the GPL
- StealSoft is the defendant, accused of violating copyright and terms of licensing by selling the software
- The software is GPL, meaning they can sell it
- Plantiff loses since they grant selling rights

In this purely legal thought experiment noncommercial looks like a better option for protecting against the sale of the software. However, the thought experiment doesn't take into account a few extremely important factors.

Suing someone is expensive. Consultancy, lawyers, attorneys, etc. all cost money prior to the case even being made. In the US this cost must be paid for by the party who requested it. Even in a country where the legal fees are paid for by the losing party, like in the UK, the risk of loss must factor into the equation somewhere.

The purely legal experiment also doesn't factor in the most important part of the case, finding out about the infringement. It's impossible to sue someone if you don't even know they exist. In the thought experiment periodic investigations either performed by you or a hired assistant would be done before the case to find the infringing party, but this is in no way guaranteed to actually find anything, meaning it could easily be a waste of time and money.

All of this is not to mention that a lot of infringing work doesn't simply sell the software, they completely debrand and rebrand it, meaning that all of the names and credits are completely rearranged and changed. This is a smart move by the infringing party, since it means that granny won't accidentally stumble on the real homepage of the program, and also won't be curious as to why it costs $30 on one site and $0 on the site which actually has its name on it. This rebranding is what you'll probably face in actuality, which transcends the infringing party simply selling it, rather challenging the very well tested attribution system.

But even then, rebrands and attempts to commercialize software are usually going to happen in countries like the People's Republic of China, which doesn't respect international copyright law. The PRC is known for favoring local's limited rights over foreigners'. In the case of copyright it means that unless you have extensive connections to truly honest locals with your best interest in mind you'll simply be unable to go through the courts because your claim will be regarded as irrelevant.

**Legal is expensive, can't find the infringing parties, probably won't use the noncommercial clause, and will likely not even be possible.** So how can you actually protect against such infringement?

Community is the most reasonable solution to actually protect against such attempts. So, as a small party without much ability to do advertise and forcefully expand your community, what can you do?

An easy way to create a large community is to pull in the vocal and interested open source community. One of the best ways of pulling in this community is using a license which respects all of the tenets of freedom, and the GPL was specifically tooled to respect these freedoms. The open source community is known for researching the software they use, as well as any forks and similar software. This research is great at uncovering the hidden infringers of the software. Further, the vocal community is known for speaking out against the infringers by speaking with targets of the dupes about how its a scam, cutting into their margins.

An example of GPL licensed software which is attacked by infringing parties is Blender, one of the most popular 3D modelling and animating suites. Blender has had several rebranded knockoffs pop up which don't respect the copyright of Blender or various completely unrelated 3D studios. In all of the cases of rebranded Blender the fakes were found by the invested community, and were found to violate core features of the GPL license. When confronted with the idea of suing the infringing parties the founder of Blender wrote;

"But what can we do? Not much really… lawyers will be a waste of money on this. Best is as usual to just publicize this well. “Sunlight is the best disinfectant” as a U.S. Supreme Court judge once said."

The GPL is simply a better option for your use case, as well as the use case of many open source projects. It provides a better community, which is the only realistic way of finding those who wish to undercut you, and is also the only realistic defense against the undercutting. But there are some ways to maximize the usefulness of the community. Grow it! As much as possible, give tips and insight into the software and how to use on open source and linguistic forums and groups around the internet. Create community outlets for users to contact you and contact each other so that you can be notified about wrongdoings and so people can help each other out about the software. Going GPL opens up many options with this route, like Freenode which provides free IRC channels to open source projects.

I should also mention that if you switch to the GPL it will be much easier to explain and justify a pay-what-you-want style download for PolyGlot if you choose to add such a thing.

Thanks for the software and considering the move to an open source license. Open minded and smart people like you are amazing for furthering education and society. I truly want to see this software succeed, and I think that the GPL is the best way for it to succeed and not fall by the wayside to be swept up by people who rebrand, debrand, and sell it.
