### ISSUE TITLE
Dimensions Field Not Deleting

### ISSUE THREAD

**Issue by mseb10** [DraqueT/PolyGlot#809]
Hello

I'm having trouble deleting unwanted dimensions from the conjugations/declensions setup tab. I'm new to this program, so maybe I'm doing something wrong, but the most I can do is delete the name of the dimension, but I cannot actually delete its box from the list.

**Comment by DraqueT** [comment]
Sorry to hear you’re having trouble! That might be a known bug that you’re running into. Please click help->about in PolyGlot and let me know what version you are using (and whether you are using a beta). That’ll help me know where to look.

**Comment by mseb10** [comment]
I'm currently on version 2.5, not a beta version

**Comment by DraqueT** [comment]
Thanks for all the details! You’re actually in luck. This is a bug that was found and quashed, and I am working on pushing the release of PolyGlot 3.0 out tonight!

**Comment by DraqueT** [comment]
Heyo! 3.0 is now released, which should take care of your problems! Please check it out and give it a try! 

https://github.com/DraqueT/PolyGlot/releases
