### ISSUE TITLE
Package naming conflict on Linux

### ISSUE THREAD

**Issue by rhotacizer** [DraqueT/PolyGlot#815]
When I install PolyGlot on Ubuntu using the .deb file, it works for a while and then suddenly disappears from the system. I eventually figured out that this is because the package is installed as `polyglot`, and Ubuntu has a [different package with the same name](https://packages.ubuntu.com/bionic/polyglot) in its package repositories. Since that package has a higher version number, the system update manager helpfully "upgrades" PolyGlot by replacing it with this unrelated software.

Steps to reproduce in Ubuntu 18.04:
```bash
$ sudo apt install PolyGlot-Ins-Lin.deb
...
Note, selecting 'polyglot' instead of '.../PolyGlot-Ins-Lin.deb'
...
Setting up polyglot (1.0-1) ...
...
$ /opt/polyglot/bin/PolyGlot  # program runs normally
$ sudo apt update && sudo apt upgrade
...
The following packages will be upgraded:
  polyglot
...
Removing shortcut
Unpacking polyglot (2.0.4-1) over (1.0-1) ...
Setting up polyglot (2.0.4-1) ...
...
$ /opt/polyglot/bin/PolyGlot
bash: /opt/polyglot/bin/PolyGlot: No such file or directory
```

(I don't know enough about Ubuntu/Debian development to know what the right solution is. Maybe there's a way to mark the package as locally installed for the package manager so it doesn't get overwritten with things from universe?)

**Comment by DraqueT** [comment]
Thank you for the heads up here! I think that the solution will probably just be to change the name that it registers. This is the first time that I'm releasing with an actual installer for Linux, so it didn't occur to me to check for something like this. Probably going to be releasing v. 3.0.1 pretty soon to tidy up some of the newly introduced bugs that came from such a fundamental rewrite.

**Comment by tylerhollman** [comment]
rhotcizer, you might want to search for 'a package ignore list', or 'a package lock' to find a way to keep your system from auto updating the program. I had the same issue on Arch and added this package to the 'pacman ignore list', however I am not familiar enough with Ubuntu to give any more help.
