### ISSUE TITLE
Phonemic Orthography no longer applied recursively

### ISSUE THREAD

**Issue by Rially** [DraqueT/PolyGlot#816]
Hello!
After the update, whenever I change the phonemic orthography, it is only applied to new words.
[Image](https://i.imgur.com/zdKnk7s.png)
[Image](https://i.imgur.com/SmdUeNb.png)
[Image](https://i.imgur.com/XggBEmm.png)
Are there settings elsewhere that I missed?
Thank you!

**Comment by DraqueT** [comment]
Thank you for the heads up! This is a system that went through some heavy rewrites in the upgrade. I'm looking into this now, and it will be addressed for the 3.0.1 release.
