### ISSUE TITLE
Folders or Groups for Words

### ISSUE THREAD

**Issue by Aronurr64** [DraqueT/PolyGlot#819]
It would be helpful to be able to organize the words into folders or groups, so you could create language families with linked etymology.

**Comment by DraqueT** [comment]
Heyo! There are two tools that you can use there. 

1) The etymology engine (which it sounds like you might have already found). In case you have’t you can open the Etymology tool by clicking the Etymology below a word’s definition in the Lexicon

2) The lexical families tool. To access this, click Tools->Lexical Families. It’s not as advanced as some other elements of PolyGlot, but has the exact functionality you’re describing here. 

Let me know if these tools help you! ^^

**Comment by DraqueT** [comment]
Closing ticket.
