### ISSUE TITLE
Ability to view a conjugation table in the definition box

### ISSUE THREAD

**Issue by detectiveroboryan** [DraqueT/PolyGlot#820]
DEV THOUGHTS: 
Consider this one carefully. Moving forward this might be something to consider, but possibly in a separate field? Consider.

ORIGINAL TEXT:
<none>

**Comment by DraqueT** [comment]
Heyo, could I get some additional details here? I have tried to reproduce an error here and not had success. 

If you could send me the pgt file that would help me track it down as well. Thanks for taking the time to create a ticket!
