### ISSUE TITLE
PDF Printing problems : Etymology trees

### ISSUE THREAD

**Issue by Speykious** [DraqueT/PolyGlot#821]
There is a problem in the printing of etymology trees in the published PDF of conlangs.
They appear blurred and offset as to superpose onto other writings.
Here are some screenshots.
![Capture d’écran de 2019-12-07 01-16-55](https://user-images.githubusercontent.com/13885008/70365165-62ca3e00-1890-11ea-9757-c879291f86b6.png)
![Capture d’écran de 2019-12-07 01-17-02](https://user-images.githubusercontent.com/13885008/70365170-6d84d300-1890-11ea-8f28-2d6bba9050ec.png)
As we can observe on the left of this screenshot below, it seems like there is nothing wrong without etymology trees.
![Capture d’écran de 2019-12-07 01-17-11](https://user-images.githubusercontent.com/13885008/70365171-6fe72d00-1890-11ea-910f-236ed094cad2.png)

**Comment by DraqueT** [comment]
Thanks for pointing this one out, I'll definitely look to correct it in the 3.0.1 release.

**Comment by Speykious** [comment]
Thanks for your response!

**Comment by DraqueT** [comment]
Just completed the fix! If you head over to the homepage (http://draquet.github.io/PolyGlot/) and download the newest build, you'll find that the problem is solved!
