### ISSUE TITLE
Add a "New Language" on the opening screen

### ISSUE THREAD

**Issue by benjaminapetersen** [DraqueT/PolyGlot#828]
For context, the first time opening the app I see the following options:

<img width="1064" alt="Screen Shot 2020-01-05 at 11 11 06 PM" src="https://user-images.githubusercontent.com/280512/71794716-cd49d780-3010-11ea-9a08-72bb70e5657a.png">

I go with "Open Language" as this seems to be the most logical, however the modal implies I already have a language file started:

<img width="1045" alt="Screen Shot 2020-01-05 at 11 11 14 PM" src="https://user-images.githubusercontent.com/280512/71794738-e488c500-3010-11ea-9154-68c7132345c5.png">

I have never used the app before, so I try typing in a file name and I get this message:

<img width="522" alt="Screen Shot 2020-01-05 at 11 13 47 PM" src="https://user-images.githubusercontent.com/280512/71794787-1306a000-3011-11ea-8341-d36fa13dbca5.png">

It may be good for the first screen to have an option for "new", at least on the first opening, or until the user has created one file.

**Comment by DraqueT** [comment]
Thank you for the suggestion! I'll put some thought into making this more user friendly.
