### ISSUE TITLE
Cannot navigate app without fixing an error that is difficult to understand

### ISSUE THREAD

**Issue by benjaminapetersen** [DraqueT/PolyGlot#829]
Hello!  Really intrigued by what this app has to offer.  So I'm a new user and obviously don't know what I'm doing.  I'm attempting to browse around and get a feel for the application.  I get the sense that I simply clicked in the text box and now the application wants further input from me.  The following message pops up and will not let me navigate elsewhere without fixing the problem, however I didn't actually intend to start something.  In addition, the `con word`, `pronunciation`, and other main text boxes are disabled.  I am not sure what to do:

<img width="1016" alt="Screen Shot 2020-01-05 at 11 17 51 PM" src="https://user-images.githubusercontent.com/280512/71794955-dd15eb80-3011-11ea-8274-a4bb7afb93c0.png">

Tinkering around a bit to make progress, I get to the following state: 

<img width="1018" alt="Screen Shot 2020-01-05 at 11 18 06 PM" src="https://user-images.githubusercontent.com/280512/71794943-d12a2980-3011-11ea-8afb-6f64158034f0.png">

Then I attempt to quite the application but get several popup messages indicating I must fix my mistake before I can quit the application:

<img width="747" alt="Screen Shot 2020-01-05 at 11 22 05 PM" src="https://user-images.githubusercontent.com/280512/71795061-4bf34480-3012-11ea-819a-f30d42463410.png">

In the end I had to force quit the application.  I imagine there could be some usability polish here to give new users some direction.

Thanks!

**Comment by DraqueT** [comment]
Heyo, sorry to take a few days to get back to you here, I was traveling a bit!

Anyhoo. What probably happened was that you hit the new word button then did not fill anything in. I need to think about how this is handled in PolyGlot generally, as it can be bothersome to users. Thank you for giving me feedback, that's how PolyGlot gets better with time!

**Comment by benjaminapetersen** [comment]
Thanks for the response!

**Comment by benjaminapetersen** [comment]
😄 👍
