### ISSUE TITLE
add better reporting from Java 8 bridge when JVM fails to start from console command

### ISSUE THREAD

**Issue by skeetcha** [DraqueT/PolyGlot#836]
The Java8 Bridge fails to return an error message if the Java Virtual Machine does not start up at the console. Research this and how to address the issue.

ORIGINAL TEXT:
I'm having some trouble exporting my language to a PDF. Whenever I try to export to PDF, I get a popup dialogue that says "Unable to print file:". If there's anything I can do like uploading a log (I do not know where I would find that), let me know.

**Comment by DraqueT** [comment]
Thank you for taking the time to write up a bug report! PolyGlot does make logs. There should be a PolyGlot folder in your Documents (or in your home directory on a mac) inside that will be a log file. Could you please email me that and the language file you’re trying to print?

If I can correct the bug, I’ll send you the latest beta in which it has been fixed. ^^

**Comment by skeetcha** [comment]
I don't believe that I have that folder. However, I can send you the [language file](https://www.dropbox.com/s/3mao5xcmcoigeio/ProtoToran.pgd?dl=1).

**Comment by DraqueT** [comment]
Thank you for sharing your language file here! I've unfortunately not been able to reproduce the error that you're experiencing. Are you embedding an image in the file? The only thing I can think of is if an image had some weird encoding that caused.

I think at this point that finding the log file would be the best way to track this down if you're still willing to give a hand. If you're running on Windows, there should be a PolyGlot folder in your Documents folder. If you're on OSX or Linux, the PolyGlot folder will be under ~/. Inside the PolyGlot folder, you'll see the file PolyGlot_error.log.

If you could try to print to PDF, then after the error pops, send the error log to be via an email attachment (draquemail@gmail.com, the same one from before), it would help me track it down. In the mean time, I could also just print out the newest file you've got and send you a copy of the PDF.

**Comment by skeetcha** [comment]
Hi Draque! I was wondering if you received my email from last week that has the error log in it.

**Comment by DraqueT** [comment]
Fixed as part of another bug.
