### ISSUE TITLE
Add option to update or ignore words already present when importing from CSV

### ISSUE THREAD

**Issue by TheLordOfAllMuffins** [DraqueT/PolyGlot#850]
Currently if you import from a CSV file to add to your lexicon, if a conword is in both the polyglot lexicon and the file being imported, it simply is added as a duplicate. What I would like is the option to either ignore incoming duplicates, replace lexicon entries with incoming duplicates, or have some sort of dialogue pop up to handle duplicate cases, so that I don't have to worry about deleting a bunch of unwanted duplicate entries from my lexicon if I forget to trim my CSV file before importing it.

**Comment by DraqueT** [comment]
This is a great idea! I think I’ll implement this tonight.
