### ISSUE TITLE
Populate pronunciation fields after creation

### ISSUE THREAD

**Issue by TheLordOfAllMuffins** [DraqueT/PolyGlot#851]
Some way to have pronunciation be filled in for words where it's blank without having to edit each word individually would be incredibly convenient, especially when importing from a decently sized CSV file that doesn't have pronunciation in it.

**Comment by DraqueT** [comment]
Thanks for submitting this! This feature has already been implemented, but isn’t released yet. If you’d like a beta with the functionality, reply here with the OS you’re using and I’ll try to get a fresh build put together for you this evening.

**Comment by TheLordOfAllMuffins** [comment]
my current project I'm using windows

**Comment by DraqueT** [comment]
Finally Windows builds working again. You can snag the latest build where this is fixed here: https://draquet.github.io/PolyGlot/
