### ISSUE TITLE
Ligatures working inconsistently

### ISSUE THREAD

**Issue by IEpig** [DraqueT/PolyGlot#856]
Hi there, 
First off I would like to say a huge thank you for the tool. It's been amazing and has saved me a lot of time and hassle.

I've just created a ligature based font, and have noted that it seems to work inconsistently in PolyGlot. When I import the language, ligatures don't work at all in the lexicon section, however work perfectly in the quiz generator section of the program. I know ligatures have been a problem in the past so I'm not sure if I'm doubling up on an issue. 

Thanks a lot!
Ben.

**Comment by DraqueT** [comment]
Thank you for making me aware of this and for including the detail that they work properly in the quiz section! 

When you are loading the font, are you loading it from the Language Properties screen or from clicking Tools-> Import Font?

Also, could you link me to the font/email me a copy for testing with? 

I’ll get you a beta build with the bug corrected as soon as I get it fixed! :)

**Comment by IEpig** [comment]
I import it through the tools --> import font method, as I read that had fixed some ligature issues in the past (and I also struggle to get PolyGlot to recognise the font through the language properties screen). 
I certainly can send through the font, what email address do you use.

Thanks very much for the prompt response!
Ben.

**Comment by DraqueT** [comment]
Thanks! My email is draquemail@gmail.com.

And yeah, I am going to be heavily reworking the language properties font section. Java's handling of ligatures actually depends on whether you load a font from a binary or not... which is really weird.

**Comment by DraqueT** [comment]
Ok, this one was a trip. I was not able to recreate your exact bug you say (even when I used your font), but I HAVE cleaned up a good bit of font handling in PolyGlot that should give users a more smooth and explanatory experience. I need to fix my Windows and Linux build images, but I'll try to roll a build out for you soon.

**Comment by IEpig** [comment]
Thanks very much for that! I seem to have a few strange and inconsistent bugs so it might be my java installation (planning on getting a new system soon). I really appreciate all the help. 
Ben.

**Comment by DraqueT** [comment]
As a heads up, the newest beta includes fixes that I believe should address your issues (link below). I'm going to close this ticket now, but if the problems persist with the new build, please feel free to reopen!

https://draquet.github.io/PolyGlot/
