### ISSUE TITLE
"Delete selected dimension" not working

### ISSUE THREAD

**Issue by Desalambrade** [DraqueT/PolyGlot#871]
Hi! When editing the dimensions of a conjugation, I can't delete a dimension once I've added it by selecting the "Delete selected dimension" option. Thus I get a bunch of useless conjugations in the conjugation autogeneration window.

**Comment by DraqueT** [comment]
Thanks for the bug report! I will check this out as soon as I’m back at my place. ^^

**Comment by DraqueT** [comment]
Thank you for catching this one! I just corrected it. If you post your email address here with the OS you use, I will give you a link to a review build. I will be releasing v 3.1.2 very shortly, but since you have a particular need for it, I'll let you check it out early. :3

**Comment by Desalambrade** [comment]
Hey! Sorry I didn't check your last response earlier. I'll be downloading the new version now that it's out. Thank you very much for taking care of the issue. :)
