### ISSUE TITLE
Read and save file error

### ISSUE THREAD

**Issue by Leomelio** [DraqueT/PolyGlot#873]
Hello!

I have just downloaded and installed the latest version of Polyglot (3.1.1) and I have problems to save and open my files.

I have two Polyglot files :
- I can open one but when I try to save it, a message appear :
 "Unable to save to file : C:\Users\Maxime Léger\PolyGlot\Maastrohite.pgd
LÃ©ger\PolyGlot\Maastrohite.pgd\xxTEMPPGTFILExx (The system cannot find the file specified)"
- When I try to open the other one, a another message appear:
"Could not read file: C\Users\Maxime
File C:\Users\Maxime is not a valid PolyGlot archive" and PolyGlot starts with a empty template.
When I close the message and PolyGlot, a another error appear:
"C:\Users\Maxime Léger\PolyGlot\LÃ©ger\PolyGlot\Xexois.pgd\PolyGlot.ini (The system cannot find the file specified)"

It seems to come from the fact that my "Users" folder has the special character "é" but I didn't have these errors before the last update and there is maybe other reasons.

Please let me know if you need any more information.

Thanks,

Maxime

**Comment by DraqueT** [comment]
Thank you for the detailed writeup! I think you found the problem exactly. I am going to be releasing 3.1.2 very soon (hopefully tonight if I can squeeze in some coding after I'm done with work) which includes some bugfixes. I will try to get this fix in as well, and will make sure to post here when a corrected version is available for you to download.

**Comment by DraqueT** [comment]
So this is 90% addressed btw. The one aspect of this that can't be corrected right now is double click to open. That is unfortunately a bug in Java itself. Putting in a more user friendly dialogue for when this pops up, and have filed bug reports with Oracle regarding file association issues.

**Comment by Leomelio** [comment]
I tried the version 3.1.2. (By the way, thank you for your reactivity!)
My first save (the one I couldn't save) now works perfectly, but the other one (the one I couldn't open) still doesn’t open. I no longer have any error messages, but when I try to open it from the homepage, the app closes.

**Comment by Leomelio** [comment]
It's when I try to open it through the menu.

**Comment by DraqueT** [comment]
Could you please send me the language file? That is behavior that I have not been able to reproduce. Thanks for your help in tracking this down, by the way! My email address is draquemail@gmail.com

**Comment by DraqueT** [comment]
Heyo! I just wanted to give you the heads up that the error you were experiencing here was most likely related to alphabetic order, and has been corrected in the latest beta build, available here:
https://draquet.github.io/PolyGlot/

**Comment by Leomelio** [comment]
Hello!
I've downloaded the beta build and corrected my alphabetical order and it now works perfectly !
Thank you very much for your time and your efforts !
