### ISSUE TITLE
Can't generate PDF file?

### ISSUE THREAD

**Issue by satoruhlc** [DraqueT/PolyGlot#874]
Everytime I try to generate a PDF file, a dialogue box appears saying "Unable to print to file".

**Comment by DraqueT** [comment]
Thank you for the bug report! I am going to be releasing an incremental upgrade to PolyGlot very shortly (today or tomorrow) that should hopefully address this for you.

**Comment by DraqueT** [comment]
I have released a new version of PolyGlot which corrects the majority of people's PDF problems. I'm closing this ticket, but please respond here if the new version does not address your issues!
