### ISSUE TITLE
[Request] Support for Vertical Scripts

### ISSUE THREAD

**Issue by satoruhlc** [DraqueT/PolyGlot#875]
The script I'm building is vertical based, and I fear I'll face issues when I create a font and import it to the software

**Comment by DraqueT** [comment]
Support for vertical writing is unfortunately a weakness of PolyGlot. If you have a font that is vertical, could you send it to me? I don't believe I've seen one before so I'm not sure how it would actually act in the program.

**Comment by satoruhlc** [comment]
Of course, once the font's done I'll send it to you.

**Comment by DraqueT** [comment]
This is unfortunately not technically feasible right now. Vertical scripts are something that I would like to make possible in the future, but for now, they are not something which I am able to include in PolyGLot.
