### ISSUE TITLE
Language Evolution/Mutation option.

### ISSUE THREAD

**Issue by DraqueT** [DraqueT/PolyGlot#878]
Create an option that allows users to mutate the language based on regex patterns. Allow users to apply this with filters for part of speech. Allow users to define what percentage of words to apply the transformations to (randomly).

**Comment by TheLordOfAllMuffins** [comment]
One thing I'd like along with this feature (or a similar sound change feature) would be the option to create a new language and put all of the changed words in there, as a sort of history documentation or for if I want to apply multiple different sets of changes to the same language (e.g. a proto-lang for a language family).

**Comment by DraqueT** [comment]
So we will see what happens, but my plan is ultimately to allow entire families of languages to exist within a single file. You can create new ones via mutation based on prior languages, and all etymologies will be automatically generated. 

Gotta work out the details, but for people looking to base languages on existing natlangs, it will make things loads easier!

**Comment by TheLordOfAllMuffins** [comment]
Ah, I see! Yes, that would be super useful!
