### ISSUE TITLE
Unable to print to fileː

### ISSUE THREAD

**Issue by Nerdling-S** [DraqueT/PolyGlot#879]
Thank you so much for creating this fantastic tool. I'm on 3.1.2, but sadly I haven't been able to publish to pdf, whenever I attempt to do so, a message pops up and reads: "Unable to print to file:". I've included the PolyGlot_error.log file if you need it.
[PolyGlot_error.log](https://github.com/DraqueT/PolyGlot/files/4409687/PolyGlot_error.log)

**Comment by DraqueT** [comment]
I'm glad you're finding PolyGlot helpful, but sorry that it's giving you an
error. Could you please send the language file to draquemail@gmail.com so I
can check it out? The error log file showed me the general area where the
problem is, but I'll need to take a look at that in particular to see
what's causing the problem.

- Draque

**Comment by Nerdling-S** [comment]
I have two language files that I'm working on at the moment, and it occurs in both. I have sent you the main one.

**Comment by DraqueT** [comment]
Thank you for reporting this error and sending the file! I have found the problem.

The font you are using is unfortunately incompatible with the library which creates PDF images. The next version of PolyGlot will be more helpful and tell this to the user, but until iText (the library I use to build PDFs) updates, you will have to select  another font to print with.

Sometimes the fonts included with operating systems are not compatible with typical open standards like TTF.

**Comment by Nerdling-S** [comment]
The error persists, even when I use Charis SIL that you included by default.

**Comment by DraqueT** [comment]
Well shoot. If that's the case, it's absolutely an issue that needs to be addressed. What OS are you using?

**Comment by Pyrocake** [comment]
I have the same issue, I am on Windows 10. I have similarly attempted to use the included Charis SIL font

**Comment by DraqueT** [comment]
@Pyrocake Thanks for contributing here. Could you please send your language file to me at draquemail@gmail.com? This is one I'm still trying to really nail down the cause of.

**Comment by DraqueT** [comment]
@Pyrocake @Nerdling-S This bug has been corrected! If you download the newest beta build (https://draquet.github.io/PolyGlot/), you should see it cleared up! :3
