### ISSUE TITLE
Several typos in code

### ISSUE THREAD

**Issue by Huy-Ngo** [DraqueT/PolyGlot#881]
I found several typos in the code:
https://github.com/DraqueT/PolyGlot/blob/10417ac1c1685ecca6c5ac69457ad71ce9705847/src/main/java/org/darisadesigns/polyglotlina/PGTUtil.java#L175

(should be `DEC_GEN_TRANS_XID`)

https://github.com/DraqueT/PolyGlot/blob/10417ac1c1685ecca6c5ac69457ad71ce9705847/src/main/java/org/darisadesigns/polyglotlina/PGTUtil.java#L80

(`OVERRIDE`)

Not too important, but it may make it harder for you to maintain.

**Comment by DraqueT** [comment]
Thanks for the heads up! Corrected these.
