### ISSUE TITLE
Simplified Setup Won't Scroll

### ISSUE THREAD

**Issue by brunoczim** [DraqueT/PolyGlot#882]
If the list of possible inflections overflows the screen size, there is no scroll bar and it is not possible to scroll:

![image](https://user-images.githubusercontent.com/18701450/79346302-92591900-7f08-11ea-9653-9027c333aca8.png)

Using polyglot 3.1.3 on Arch Linux.

**Comment by DraqueT** [comment]
Thanks for reporting this bug! I’ll let you know once it’s fixed in the latest beta build.

**Comment by DraqueT** [comment]
This is corrected now! If you would like to snag the latest beta builds that include the fix, you can snag here: https://draquet.github.io/PolyGlot/
