### ISSUE TITLE
[Improvement] Add an 'open recent' button or similar to start screen

### ISSUE THREAD

**Issue by le-birb** [DraqueT/PolyGlot#883]
Pretty simple, it would be quite convenient to have an "open recent" button or list on the start screen, so one could quickly go back to recently worked-on projects (especially since the default directory of the "open language" button is not typically close to where the language files are kept).

**Comment by DraqueT** [comment]
This is a good idea, thanks for posting it! I will definitely include this in the next version. :3

**Comment by DraqueT** [comment]
This has been completed in a prior ticket & will be included in the next release.
