### ISSUE TITLE
Alphabet check not properly updating until navigating away from Language Properties

### ISSUE THREAD

**Issue by TheLordOfAllMuffins** [DraqueT/PolyGlot#884]
Confused and frustrated me a bit just now, I think walking through a reproduction would be the best way to illustrate it.
![image](https://user-images.githubusercontent.com/17369466/79685071-b0659880-81ea-11ea-9a66-d779b3d49996.png)
This is the language properties screen with the full alphabet I'm using for this language.

![image](https://user-images.githubusercontent.com/17369466/79685107-f6226100-81ea-11ea-9039-1d5a87994993.png)
I remove the letter h, and do a "check lexicon," which comes up clean (it should not).

![image](https://user-images.githubusercontent.com/17369466/79685191-8f517780-81eb-11ea-9c8f-f7f485aa1c2a.png)
I navigate to another section and return. The alphabetical order bar is now red and the language check properly identifies the unrepresented words.

![image](https://user-images.githubusercontent.com/17369466/79685222-cde73200-81eb-11ea-8f8b-ee21635757f8.png)
Not navigating away, I fix the missing letter (re-add the h). The alphabetical order bar is still red, and when I run another language check, it has the same result as before.

Navigating away and back will cause the alphabetical order bar and language check to behave as expected.

While perhaps not the biggest of issues, it was frustrating and confusing when I fixed the issues it had and still said things were wrong.

**Comment by DraqueT** [comment]
Thanks for taking the time to make screenshots of exactly what you're experiencing. This is a use case I hadn't considered.

**Comment by DraqueT** [comment]
This should now be resolved! The latest beta builds are always available at the link below. It will have the fix for this problem included (although is not a finalized release).

https://draquet.github.io/PolyGlot/
