### ISSUE TITLE
Import Grammar

### ISSUE THREAD

**Issue by danielnewell** [DraqueT/PolyGlot#888]
It would be nice to import the grammar section from something like Word or Markdown files.

**Comment by danielnewell** [comment]
@DraqueT comments?

**Comment by DraqueT** [comment]
I'm sorry. Given our interactions in the past, no.

**Comment by danielnewell** [comment]
So, @DraqueT, there's nothing wrong with the idea, you just don't like the "interactions in the past?"

If I did something that offended you, I'd like to apologize, I would have apologized before if I had known. I understand that you may not like me as a person, but this is an open source project. You shouldn't reject ideas based on the person who suggested them. I'd understand if you didn't like the idea, but, you stated it's due to how we've interacted before.
