### ISSUE TITLE
"New language" button is offseted when hovered

### ISSUE THREAD

**Issue by u-ndefine** [DraqueT/PolyGlot#899]
Windows 7, v3.1.3

**Before hovering:**
![image](https://user-images.githubusercontent.com/41176671/81893826-07d80800-95e1-11ea-8dd5-6a61b082d633.png)

**When hovering:**
![image](https://user-images.githubusercontent.com/41176671/81894127-a2d0e200-95e1-11ea-96c7-f3df072e2f8d.png)

Minimizing and clicking the PolyGlot tab fixes it, but now the "New language" button is in a different position:
![image](https://user-images.githubusercontent.com/41176671/81894213-d3b11700-95e1-11ea-847f-dcada64ce21c.png)

**Comment by DraqueT** [comment]
Huh! I didn't notice this because it only seems to happen on Windows... thanks for the heads up!
