### ISSUE TITLE
Publish to PDF Location Error

### ISSUE THREAD

**Issue by Rodrigodoo** [DraqueT/PolyGlot#900]
- When publishing to PDF and Selecting Location it forces to chose a file.

- Using version 3.1.3 || Windows 10

![Capture](https://user-images.githubusercontent.com/26281264/81970674-30332700-9620-11ea-800f-2bf3b1717776.PNG)

**Comment by DraqueT** [comment]
Huh! Does it not allow you to just type in a filename and save it as whatever you like? I will check this out on Windows next time I get a chance to work on PolyGlot

**Comment by Rodrigodoo** [comment]
[SOLVED]

This stupid guy, read your manual diagonally and didn't have Java 8 installed...

Everything working. 

Excellent tool!! This is being very useful to organize my language!

Cheers and sorry for the troubles.
