### ISSUE TITLE
Ligatures not displaying correctly

### ISSUE THREAD

**Issue by Sandafluffoid** [DraqueT/PolyGlot#901]
Hello, I recently finished up a font for my conlang, which makes extensive use of ligatures. I can't seem to persuade Polyglot to display the ligatures correctly. I've tried importing the font from the original OTF file but the problem still remains.

I see the ligatures issue was addressed some time ago so I assume I am doing something wrong in implementing it, but for the life of me I can't figure out what it is.

I am on Windows 10, and am using the most recent version of Polyglot and Java. 

Thanks you!

**Comment by DraqueT** [comment]
Heyo, thanks for reaching out! Could you send me the font so I could take a look at it? My email is draquemail@gmail.com

-Draque

**Comment by DraqueT** [comment]
Heyo! If you check out the newest beta installer (linked below), it should take care of this problem for you! :3

https://draquet.github.io/PolyGlot/

**Comment by Sandafluffoid** [comment]
Hiya, thanks for such a quick response again, I'm really astonished at how dedicated you seem to be - it's no wonder Polyglot is such a great tool.
I can confirm that this fixes the ligature problem, and I've not encountered any other issues yet so all seems to be good

Thanks once again!
________________________________
