### ISSUE TITLE
Grammar Folders Cannot be Deleted

### ISSUE THREAD

**Issue by Rodrigodoo** [DraqueT/PolyGlot#902]
Hello,

I am having an issue where I cannot delete folders in the Grammar section, and the overall Ui is misbehaving.

![Pressing Delete](https://user-images.githubusercontent.com/26281264/82846748-ac641f00-9eea-11ea-8e66-35422ff6dbe8.png)
![After Pressing Delete](https://user-images.githubusercontent.com/26281264/82846751-acfcb580-9eea-11ea-8bca-4d79697d7f1e.png)

Also, and sorry for adding up on the issue, I am having troubles with PolyGlot freezing when trying to print Etymology Trees. I saw the previous post on the issue but it did not help me that much

Thanks, everything else keeps working great, and it has been a blessing for making my first language :)

**Comment by DraqueT** [comment]
Thanks for the heads up both on this and for printing etymology trees! I am looking into both!

Could you please email me the error log from when PolyGlot freezes? You can find it in your userfolder under the PolyGlot folder. My email address is draquemail@gmail.com.

Also... do you happen to be running Linux? Someone else is having a very similar PDF printing problem and I'm still trying to track down exactly where it is coming from.

**Comment by Rodrigodoo** [comment]
Ok big update. Part[1/2]

I read the error file and apparently I was running a loop of doom :)

> Parent/Child relation creates illegal loop. A word may never have itself in its own etymological lineage.-org.darisadesigns.polyglotlina.ManagersCollections.EtymologyManager$IllegalLoopException
> org.darisadesigns.polyglotlina.ManagersCollections.EtymologyManager$IllegalLoopException: Parent/Child relation creates illegal loop. A word may never have itself in its own etymological lineage.

So I went on and found my issue. I have a word that can be used as either a noun and adjective. therefore I created two entries for that word. One as an adjective the other as a noun, because the same word can't have two parts of speech.

Now this word has 3 children that can also be used as noun or adjective. So I created a duplicate of each and connected them to their respective parents - Noun|Adjective,  and this was the straw that broke the camel's back :)

Suggestion: I don't know the feasibility of this request but maybe use checkboxes instead of a list to choose the Parts of Speech of the word. This way there is no need to duplicate word or create extra Parts of Speech. But this would mean that the conjugation window would have to give the option to see the Declination/Conjugation of each Part of Speech. So I get it that it's not an easy fix.

Final Suggestion: Try to add an error window to tell the use these loops are happening or block them all together when creating the etymological tree.

**Comment by Rodrigodoo** [comment]
Big update. Part[2/2]

As for the Grammar part I manage to delete the Files by deleting their names first then deleting the files. I can't really pinpoint what was happening but there is something clunky happening in that menu. Therefore I have no real suggestions there :(

**Comment by Rodrigodoo** [comment]
I am using Windows. Sorry, forgot to mention, though I thought it wasn't that important :)

**Comment by DraqueT** [comment]
Fixed with this commit: https://github.com/DraqueT/PolyGlot/commit/507ea7a3ea9b7c7c356efc4c869db721e881ee0d
