### ISSUE TITLE
Version Checking problems in Java8 module

### ISSUE THREAD

**Issue by glenbanyard** [DraqueT/PolyGlot#908]
DEV TEXT:
Version checks are using the newer "--version" argument to get Java version. This does not work properly in Java 8 and below. Check using both. Additionally, not all Java8 operations are checking at all. Add checks in here to give users a better idea why a J8 reliant operation is failing and how to correct it.

ORIGINAL TEXT:
When Export to Excel error that Java required, already has Java Runtime Environment 8 u 212 installed in both 32 and 64bit editions.

**Comment by DraqueT** [comment]
Line 253 in PGTUtil.java

`public static final String JAVA8_VERSION_ARG = "--version";`

This must check with both the double dash and the single dash before "version" due to differences in JVMs across different releases.
