### ISSUE TITLE
File Path Error after updating

### ISSUE THREAD

**Issue by Rially** [DraqueT/PolyGlot#909]
After the last update, I am experiencing "File Path Error: Please retry opening this file by clicking File->Open from the menu." for all my files. 

This is the same whether or not I created them before/after the update. 
The files can be opened from the menu without problem but it's a bit bothersome.
Can I do anything to be able to open my files directly as before?

**Comment by DraqueT** [comment]
Thanks for reporting this, I'll definitely give you a hand! What OS are you using right now? Also, are you using one of the beta versions?

**Comment by Rially** [comment]
Hello, 
I am using Windows 10 and PolyGlot ver. 3.1.3 Build 2020-04-12 17:36.
Thank you for the help.

**Comment by DraqueT** [comment]
Please look in your user folder (it should have the same name as your username) and find the PolyGlot folder inside of that. There should be an error log in this folder. If you attach that to an email to me (draquemail@gmail.com), I'll be able to take a look at exactly what was going on when it failed for you.

**Comment by DraqueT** [comment]
I have recreated this bug. It'll be corrected before the next release. Thanks for reporting it!

**Comment by DraqueT** [comment]
This is fixed now! If you check out the beta version on the page linked below, your problem should be solved. ^^

https://draquet.github.io/PolyGlot/
