### ISSUE TITLE
Export to Excel tool has error "Java Runtime is required for this feature"

### ISSUE THREAD

**Issue by chricker05** [DraqueT/PolyGlot#911]
When I use the export to excel feature, it says Java Runtime is missing. I have installed both the latest Java as well as the latest PolyGlot release, but it still seems PolyGlot can't find Java.
I'm running a 64 bit Windows 10 computer.

**Comment by DraqueT** [comment]
Heyo! Thank you for reporting this! 

The good news is that the bug has already been fixed! You can snag a corrected beta version below if it’s causing you problems, but the next release is going to he this weekend if you wan to wait for the official release. :3


https://draquet.github.io/PolyGlot/
