### ISSUE TITLE
Still Unable to Print Etymology Trees - 3.2

### ISSUE THREAD

**Issue by Rodrigodoo** [DraqueT/PolyGlot#914]
Hi Draque,

Love the new update! Though, my etymology trees still freeze my printing to PDF.

Do you want me to send you the Error Report?

Thanks for the great release though :)

**Comment by DraqueT** [comment]
That would be good, yeah! I appreciate you following up on this to let me know it's still an issue. Additionally, try running Tools->Check Language. There are new features in that which should check for recursion within it (the issue which causes freezes). Would you be willing to send the language file which causes the freezing as well? I want to make certain that I'm seeing the same issue that you are there. My email address is draquemail@gmail.com.

**Comment by DraqueT** [comment]
This is potentially no longer a problem... if no recurrence a month or two after 3.3 release, close ticket.

**Comment by DraqueT** [comment]
Issue resolved in latest beta.
