### ISSUE TITLE
Windows Defender

### ISSUE THREAD

**Issue by Rially** [DraqueT/PolyGlot#919]
Thank you for the great update.
I think this happened the last time I updated as well: Windows Defender pops up and displays some blue warning. I, of course, ignore this since I know this project and it doesn't bother me whatsoever to make two extra clicks to update Polyglot.
Unfortunately, it seems after ignoring it, the blue warning won't pop up again. I'll try to remember screenshotting it for the next update.

**Comment by DraqueT** [comment]
Heyo, thank you for taking the time to report this! The blue screen basically just says "Windows doesn't recognize what this program is, and it could potentially be dangerous." It's something that I might eventually take care of, but it's not core functionality, so it's one of those things that I will get to eventually. ^^

Thank you for the kind words about PolyGlot, and I hope that it's continuing to be helpful to you!
