### ISSUE TITLE
Special unicode character not correctly displayed in lexicon description [BUG/ENHACEMENT]

### ISSUE THREAD

**Issue by 0nyr** [DraqueT/PolyGlot#921]
Hello,
I'm very satisfied with your program. However special characters like "ɛ" are not displayed properly in the word description of the lexicon. This is not a problem in the title of the work so I guess it is a simple thing o fix.

![Screenshot from 2020-07-08 19-45-32](https://user-images.githubusercontent.com/47721040/86952795-cdf42f80-c153-11ea-9431-971a69854d98.png)

If I can do it, just tell me. I have some knowledge with Java.

Best regards

**Comment by 0nyr** [comment]
Actually I have this problem everywhere with some special characters... I would really appreciate a way to fix this issue.
![Screenshot from 2020-07-08 21-23-29](https://user-images.githubusercontent.com/47721040/86961386-6f35b280-c161-11ea-988f-11442a6cd690.png)

![Screenshot from 2020-07-08 21-25-10](https://user-images.githubusercontent.com/47721040/86961506-9f7d5100-c161-11ea-948d-d0ff7fde0b8f.png)

**Comment by 0nyr** [comment]
Actually, I found that changing the font solves the issue. So it's not from the software. Problem solved.

**Comment by DraqueT** [comment]
You closed this literally as I was typing up that response. XD

Anyhoo, glad that PolyGlot is working well for you and thanks for taking the time to post a ticket here! User feedback is the biggest part of how I improve it. :3

**Comment by 0nyr** [comment]
Thanks for the response ;)
I just what to really thank you for all the work you put in this project for free. I wish you the best.
