### ISSUE TITLE
One Issue, One Request.

### ISSUE THREAD

**Issue by SgtMorocco** [DraqueT/PolyGlot#922]
Hi, 

I'm having an issue with the Conjugations/Declensions Autogeneration. 
The thing is that my language has a standarised vowel change to indicate pluralisation. 
The issue I've found is that if I input É as RegEx and A as Replacement in one entry as well as having A as RegEx and É as replacement in another entry it will only use one of them (The higher in the order). I will attempt to clarify this with screenshots. Issues outlined in red.

The thing I'd like to request (Maybe this is already supported, but I couldn't find it.) is to have a system that would add a Prefix or suffix to the end of the word, without having a replacement. In my language tense is notified by a Prefix, and it would be useful to be able to just add these prefixes without having to use a bogus character.

![PolyBugReport 2](https://user-images.githubusercontent.com/68058056/87061079-36e6b080-c203-11ea-9b0f-66a19a6fb441.png)
![PolyBugReport 1](https://user-images.githubusercontent.com/68058056/87061103-3d752800-c203-11ea-8958-debbf896be88.png)

**Comment by DraqueT** [comment]
Heyo! The prefix and suffix thing is very easy. In the regex, simply put the character ^ for a prefix and the character $ for a suffix. In regex expressions, those characters represent the beginning and end of a string. 

The issue with É and A is one that I'm having more trouble understanding. In your screenshot, you show the 2nd rule for the They Plu Present form of words. The conjugation example you give for your particular word has the They Plu Present form given without either of those characters.

Are you looking to swap them in this conjugation? If so, I can absolutely show you how to do that. Let me know what you're looking to accomplish and I'll def help to get it done. :)

**Comment by DraqueT** [comment]
I am closing this ticket for now, but if you are still having trouble, please feel free to reopen it and I'll help out however I can. ^^

**Comment by SgtMorocco** [comment]
Sorry about taking so long! I'm new to github and hadn't recieved an Email notif til today.

The problem with the É and A is that one word was like this: Éþanst and after the vowel change it would become: Aþénst. The program seemed to be able to swap the A to an É but didn't swap the É to an A.

Also if it helps the infinitve form of the verb is one column to the left of the highlighted box in the first image.
