### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by SindarinLord** [DraqueT/PolyGlot#926]
How do install the thing? What file do I have to open? I'm new to this kind of stuff and would appreciate it if you could help.

**Comment by DraqueT** [comment]
Heyo! Just click the link below and you'll be taken to the homepage. In the middle of the screen to the left you'll see download options depending on what operating system your computer uses. Just download the appropriate installer and open that up. It will take care of the rest for you and get it installed! :)

**Comment by SindarinLord** [comment]
Thank you so much!
