### ISSUE TITLE
Import Grammar

### ISSUE THREAD

**Issue by danielnewell** [DraqueT/PolyGlot#931]
Repost of #888 which was wrongfully closed.

As the current editor for grammar is limited, I'd recommend being able to add markdown (.md) or office suite files (.doc, .docx, .rtf)

While I understand @DraqueT does not like interactions I may have had with them, I expect Draque to be able to take the idea at face value instead of rejecting it in spite of the author, as this would benefit more people than just myself.

**Comment by danielnewell** [comment]
@DraqueT bump

**Comment by bobby-bolton** [comment]
@DraqueT bump

**Comment by bobby-bolton** [comment]
@DraqueT bump

**Comment by danielnewell** [comment]
@DraqueT bump

**Comment by Sinfaen** [comment]
Closing in favor of #1041. I agree with the idea of markdown. Office suite files are likely to be a lot of work to integrate, and markdown would provide a better experience than what is there now
