### ISSUE TITLE
Add community standards

### ISSUE THREAD

**Issue by jwodicka** [DraqueT/PolyGlot#933]
While browsing the repo, I noticed that there are two fairly straightforward things that aren't present on this repo, which might help in shaping collaboration:

https://github.com/DraqueT/PolyGlot/community recommends that we add:
* A code of conduct
* Contributing guidelines

(They also recommend some templates, but those feel less fundamental to me. Small steps!)

If there's interest, I'm happy to put together a draft PR, based on some recommended standards. I want to make sure the maintainers are willing to enforce them before I do, since a code of conduct that isn't enforced is worse than not having one.

**Comment by DraqueT** [comment]
Done and done. Excellent suggestion.
