### ISSUE TITLE
Transformations help

### ISSUE THREAD

**Issue by skribe** [DraqueT/PolyGlot#938]
I'm trying to work out a way to use the autogen system to cater for conjugations where the vowels change mid-word. Eg sing, sang, sung.

Has anyone managed to come up with a regex transformation that can do this?

Is there a better place to post questions like this?  I've posted on reddit in the small questions discussion but feel its unlikely to be seen.  Do we need a forum or other community site for stuff like this?

**Comment by DraqueT** [comment]
This is absolutely doable. It's definitely a bit more complex than many systems (most conlangs just have a stem/suffix system), but regex is powerful.

The regex pattern "a|i|e|o|u" (without the quotations) is the simplest form that will address this. If you are looking to have vowels only replaced under certain circumstances, I would recommend experimenting with sites like https://regex101.com/. That's what I use any time I'm looking to design/test more complex regex patterns.
