### ISSUE TITLE
Non-BMP plane characters mess with alphabetical order

### ISSUE THREAD

**Issue by FD5GD** [DraqueT/PolyGlot#944]
I'm new to the program. I placed my characters way over at the 1st Supplementary PUA plane, starting at U+F8000. When pasting these into the Alphabetical Order field, I get countless "duplicate entry: �" errors.
The explanation is simple: these characters (all non-BMP characters for that matter) are encoded as pairs of so-called surrogate characters. The program considers each one surrogate as an individual character, instead of each pair, and since they tend to repeat (especially high surrogates), this bug occurs. Should be easy enough to fix.

**Comment by DraqueT** [comment]
Heyo, sorry for the long response time, things have been wild! Anyhow, here's how to address the issue! 

1) You'll need to find a font that supports the characters you're using. The font that I have PolyGlot default to is pretty good, but none have all characters. 
2) In the alphabetic order field, separate your characters by commas. This will let PolyGlot know that some of them are composite characters.

Let me know if this helps!

**Comment by DraqueT** [comment]
Closing ticket.
