### ISSUE TITLE
Import from file function does not work

### ISSUE THREAD

**Issue by TessilnTheMaskMaker** [DraqueT/PolyGlot#945]
On Windows, if an excel file is currently open, it cannot be imported. 

To fix:
 Detect if file is open like this:

`boolean isFileUnlocked = false;
try {
    org.apache.commons.io.FileUtils.touch(yourFile);
    isFileUnlocked = true;
} catch (IOException e) {
    isFileUnlocked = false;
}

if(isFileUnlocked){
    // Do stuff you need to do with a file that is NOT locked.
} else {
    // Do stuff you need to do with a file that IS locked
}`

If open, return user message asking user to first close it.

ORIGINAL TEXT:
I have a dictionary for my conlang in Excel, but when I try to import the file it gives me the following error:

> Could not import from C:\Documents\Dictionary.xlsx.
> Check to make sure that column mappings are correct (nothing above max cell value) and that the file is not corrupt.
> Index 0 out of bounds for length 0

I tried converting it to CSV, but it instead gives me this error:

> Could not import from C:\Documents\Dictionary.xlsx. 
> The text encoding is not supported. Please open the import file in a text editor and save with encoding: windows-1252

I tried re-saving it using Notepad++, but it did nothing. Using windows-1252 would destroy my dictionary anyway. Am I doing this wrong or does it just not work?

**Comment by DraqueT** [comment]
Heyo! Could you toss the excel file over to me at draquemail@gmail.com? I have have some issues with the idiosyncrasies of how the excel parsing library I use consumes them in the past, and being able to see it would help me clear it up.
