### ISSUE TITLE
"Delete From Dimension" does not work

### ISSUE THREAD

**Issue by bobby-bolton** [DraqueT/PolyGlot#950]
When attempting to delete a rule from a dimension in conjugation autogeneration, it neither removes the rule from the current rule nor from the dimension that it ought to be deleted from.

**Comment by DraqueT** [comment]
Thank you for taking the time to send in bug reports! I can't know about novel bugs unless folks send these in. : )

Could you please email me the language file that this issue appears with? I have not been able to reproduce the problem, so there must be some particular case in your language that I have not thought of.

**Comment by bobby-bolton** [comment]
> Thank you for taking the time to send in bug reports! I can't know about novel bugs unless folks send these in. : )
> 
> Could you please email me the language file that this issue appears with? I have not been able to reproduce the problem, so there must be some particular case in your language that I have not thought of.

Sure, but unfortunately I don't know what your email is or where to find it. I just joined Github a few days ago, so I'm not that familiar with the layout.

**Comment by DraqueT** [comment]
Heyo, sorry for leaving this one hanging for a bit. My email is draquemail@gmail.com and you can send the file over that way. Might unfortunately be a bit before I can get to these bugs. My bread and butter job has gotten pretty crazy lately and reduced my spare coding time.

**Comment by DraqueT** [comment]
Fixed in prior code push. Closing.
