### ISSUE TITLE
Selecting multiple items and deleting them does not work in Conjugations Setup

### ISSUE THREAD

**Issue by bobby-bolton** [DraqueT/PolyGlot#951]
In Conjugations Autogeneration, if you selected multiple rules or transformations and clicked the delete button, they would all get deleted at the same time. This does not work in Conjugations Setup; only one conjugation gets deleted.

**Comment by DraqueT** [comment]
I'm going to close this since your other ticket covers this case. When that's fixed, this will be as well.

**Comment by bobby-bolton** [comment]
> I'm going to close this since your other ticket covers this case. When that's fixed, this will be as well.

I see. Thank you anyways.
