### ISSUE TITLE
Phonemic Orthography

### ISSUE THREAD

**Issue by LatonaD** [DraqueT/PolyGlot#956]
Hi, again.

I have a question about the Character(s) column. Are regex patterns supposed to be included in converting pronunciation? Here's what I mean:

t[aio] -> t
t[u] -> θ
[kt]*a -> e
[lmn]*a -> a

Depending on priority, "ta" will either render as "t" (current priority) or "e" and not "te". The characters in the regex pattern are essentially absorbed in pronunciation. 

So I guess my question is whether regex is supposed to be the rules for how the non-regex character(s) is pronounced and this is a bug or does regex define the entire character cluster. Is the former available and I just haven't figured out how to use it? If not, may I request the former at some point?

The reason why I ask for this is as you can see above, I would have to list all permutations (ta -> te, ti-> ti, to -> to, tu ->θu, ka - > ke, la -> la, etc.) and this makes regex useless

**Comment by bobby-bolton** [comment]
Hello there @LatonaD ,
You can use capture groups in Phonology. For example, t([aeio]) with t$1 as the pronunciation properly lists ta, te, ti, and to. However, if your orthography is different from your IPA pronunciation (e.g. o = ɔ) then you cannot use Regex.

Hope this helps.

**Comment by LatonaD** [comment]
Thank you so much for letting me know about the capture groups, but unfortunately I don't use IPA in my language (easier typing). So I guess the essence of my previous post still applies as a feature request

**Comment by bobby-bolton** [comment]
> Thank you so much for letting me know about the capture groups, but unfortunately I don't use IPA in my language (easier typing). So I guess the essence of my previous post still applies as a feature request

I understand. At least most vowels and basic consonants still work. And if there's only one trouble digraph, you can have it separate from the main Regex with capture groups.

**Comment by bobby-bolton** [comment]
Update: The only way to achieve true case insensitivity is by disabling orthographic Regex. While this is understandable, it's really a bummer to be forced to not use Regex while using non-Latin script letters. @DraqueT @LatonaD

**Comment by DraqueT** [comment]
Upper and lower case is unfortunately a MASSIVE problem when dealing with arbitrary languages, and there is currently no accepted standard. I could have Java do this automatically, but its system has significant problems that would inevitably cause lead to problems down the road.

I'm keeping my eye out for solutions to this one, but this is a fundamental problem that I don't see an easy fix for in the near future. Closing the ticket for now for this reason, but I absolutely understand the desire for something like this which works well.
