### ISSUE TITLE
Reverse word as conjugation rule in conjugation autogen

### ISSUE THREAD

**Issue by bobby-bolton** [DraqueT/PolyGlot#958]
This is my 5th issue/feature request, hopefully it doesn't look like I'm spamming the issues.

It would open up many interesting choices to be able to reverse a word as part of its conjugation in Conjugation Autogeneration. Right now, you can't do so with pure Regex; you need a programming language to do it. That being said, I believe the best way to implement it is to add a toggle to reverse the word when selecting the transformation.

Of course, what I expect to happen is that the conjugation rules before the reverse rule would also be reversed. For example, the word "agi" in a certain conjugation would first have the prefix b- and then be reversed. This would lead to agi -> bagi -> igab. Hopefully, changing the order of rules and/or transformations would lead to agi -> iga -> biga.

Hopefully this could be implemented, and once again thank you for all the hard work you are putting into this.

**Comment by bobby-bolton** [comment]
@DraqueT bump

**Comment by Kemurab** [comment]
This is basically a request to implement metathesis. I have been playing for days trying to figure out how to get metathesis to work, and it seems like there must be a way, but I'm not a coder, so I'll can't figure it out right now.

Like, getting bat>tab, especially if I only want that out of rabat, so rabat>ratab.

I've tried messing around on Regex101, but honestly I don't really know what I'm doing. There's so much information online about regex in different coding languages and different environments, it's hard to know which stuff applies here and which doesn't.

If you can pull off local metathesis, then reversing a whole word should be easy... right?

**Comment by bobby-bolton** [comment]
> This is basically a request to implement metathesis. I have been playing for days trying to figure out how to get metathesis to work, and it seems like there must be a way, but I'm not a coder, so I'll can't figure it out right now.
> 
> Like, getting bat>tab, especially if I only want that out of rabat, so rabat>ratab.
> 
> I've tried messing around on Regex101, but honestly I don't really know what I'm doing. There's so much information online about regex in different coding languages and different environments, it's hard to know which stuff applies here and which doesn't.
> 
> If you can pull off local metathesis, then reversing a whole word should be easy... right?

While I wasn't thinking of metathesis while making this request - I just wanted to implement reversing words in one way, because not a lot of languages use it - I do agree that it is a useful feature.

PS: Whenever I say or even type "metathesis" it ends up having epenthesis as "metasthesis". It's probably because of "metastasize".

**Comment by DraqueT** [comment]
Heyo! So this is unfortunately not something I think I can implement. The reason for this is that many (if not most) languages that make words with alternate forms (conjugation, declension, etc.) do so in ways that are potentially ambiguous. While context might make the particular form clear from the perspective of two folks having a conversation, there would be no way to necessarily reverse the process on its own.

Anyhow, please don't feel like you're putting in too many requests! I am not always able to implement features that people ask for, but I am always very happy to hear them, and the worst I'll say that that I'm not able to make a change. Thanks for taking the time and thought to make all these suggestions!
