### ISSUE TITLE
A mandatory dropdown text box cannot be selected if it is flashing

### ISSUE THREAD

**Issue by bobby-bolton** [DraqueT/PolyGlot#959]
The title says it all.

To replicate it, make a new language, select "part of speech" mandatory, and create a new word. While you're typing, the "part of speech" text box will flash; if you try to select it, it opens and then immediately closes the selection dropdown.

It's a little thing, but it bugs me as I have to select the Part of Speech two or three times because it keeps on closing.

**Comment by DraqueT** [comment]
Thanks for the heads up! The flashing is old functionality that I should really pull anyhow. Just having it shaded red is enough to catch people's attention.

**Comment by TrapinchO** [comment]
bumping this

**Comment by TrapinchO** [comment]
Still happens when selecting the dropdown via tabulator. It skips to the next field

**Comment by DraqueT** [comment]
Ooh, good call. Only fixed it for mouse action.
