### ISSUE TITLE
Ligatures disappear on reload

### ISSUE THREAD

**Issue by Kemurab** [DraqueT/PolyGlot#960]
Hi. I created a custom font, and loaded into Polyglot. Since the font is a syllabary, I had to make use of a large number of ligatures. These worked fine at first, but when I reloaded it, the next day, all ligatures were gone, replaced by separate characters. Re-importing the font fixed the issue, so it's not a huge problem, but it's a minor inconvenience that may be good to deal with at some point.

I'm on Windows 10, if that helps.

**Comment by DraqueT** [comment]
Heyo, thanks for letting me know about this! Could you please send the font you're using to draquemail@gmail.com so I can take a look at it? Java unfortunately is pretty ornery when it comes to ligatures, so I might need to take another look at exactly how they're being loaded once you reload a language.

**Comment by Kemurab** [comment]
Hi,

Thanks for the response. Here's the font.

I created it in Birdfont, and it seems to work perfectly in most programs.
I'm not sure if there's something special with how Birdfont handles
ligatures that may affect Polyglot, but it might be something.

Charlie.

**Comment by DraqueT** [comment]
Thanks for uploading this! Just wanted to let you know I haven't lost sight of this, just become swamped with my bread and butter job.

**Comment by DraqueT** [comment]
Sorry this took me forever, but if you're still using PolyGlot, this one is tackled at this point. ^^
