### ISSUE TITLE
Making it so that you can write individual rules for each dimension in Conjugations/Declensions

### ISSUE THREAD

**Issue by TheStroy** [DraqueT/PolyGlot#961]
Hi there! I just found this software and I must say, it's amazing and sped up the conlang making progress by like 4 times.

However, I've just filled in the lexicon for this conlang I'm making with a few words and I realized an issue, that is making a fusional language I have to make 520 individual rules just for noun autodeclension, which is a lot.

If, for example, I was able to decide first the rules for the owner of the object and each of its dimensions, then for the object/subject etc... I would have to only write 2 rules for object/subject, 5 for ownership etc... I would end up, for the same amount of complexity, writing only 36 rules which I can do in a couple hours.

Otherwise, I have to use export as an excel and then use google sheets for the last bit which doesn't have a lot of Polyglot's useful functions.

**Comment by bobby-bolton** [comment]
You could use "Push to Dimension" - it saves a lot of time. If there are exceptions, you can still modify them.

Hope this helps, and happy holidays!

**Comment by DraqueT** [comment]
Yup! And the pushing/deleting feature is set to receive some updates in the future as well for folks who have highly complex rules.

**Comment by TheStroy** [comment]
> 
> 
> You could use "Push to Dimension" - it saves a lot of time. If there are exceptions, you can still modify them.
> 
> Hope this helps, and happy holidays!

Sorry if I didn't answer before, christmas and all that.

Maybe this is very stupid, but what is "push to dimension"? I can't seem to find it anywhere.

**Comment by DraqueT** [comment]
No worries! Things have been... pretty wild lately.

Anyhow, right click on a rule and you'll see a little drop down menu appear. It should have what you're looking for!

**Comment by TheStroy** [comment]
thanks a lot, that worked!
