### ISSUE TITLE
Deleting internal parent shrinks the parent sidebar

### ISSUE THREAD

**Issue by bobby-bolton** [DraqueT/PolyGlot#963]
Hello, I am back and I've got another mildly infuriating bug.

Whenever you set an internal parent in the Etymology Window, if you then proceed to delete that internal parent, the sidebar for parents shrinks to an absolutely tiny size. You can then of course adjust it back to normal, but the bug persists.

I hope this could be fixed. Thanks!

**Comment by DraqueT** [comment]
Oof, this one is annoying, absolutely. On my to do list once life calms down a bit.
