### ISSUE TITLE
Regex flag is always global

### ISSUE THREAD

**Issue by Conallia** [DraqueT/PolyGlot#964]
There should be a way to change it, or even allow for changing it for every regex by doing /"flag"

**Comment by bobby-bolton** [comment]
Could you please clarify a bit here?

**Comment by DraqueT** [comment]
Also would like some clarification here if you're still looking for this feature.

**Comment by DraqueT** [comment]
Please reopen this issue if it's still causing you grief. Closing for now because I'm not sure how to proceed.
