### ISSUE TITLE
Text is just boxes?

### ISSUE THREAD

**Issue by Juggler64** [DraqueT/PolyGlot#968]
Sorry if this is kinda a noob issue, but everything that I type that isn't the latin alphabet just shows up as little rectangles. Even if I copy and paste them, or use one of the preset fonts, it's all rectangles.

**Comment by DraqueT** [comment]
Heyo, no worries! I would recommend using one of google’s noto fonts (they are free to download and if you search them, they’ll come right up). You’ll need to play around with them to see which contain the characters you need, but that should clear ip the issue you’re seeing!

**Comment by DraqueT** [comment]
Closing the issue for now, but please reopen if this persists! : )
