### ISSUE TITLE
Add search partisl completion bar to dropdowns (for selecting words from complete list in particular)

### ISSUE THREAD

**Issue by ClemCa** [DraqueT/PolyGlot#976]
This applies most specifically to selecting the parent in etymologies.

ORIGINAL TEXT
It just came to me while going through the drag of scrolling through the entire dictionary to find a parent, but wouldn't it be much more practical to be able to search (or at least type for a bit instead of instantly selecting the first word of a letter) in the etymology window?
If it is possible with the current way things work, of course.

**Comment by DraqueT** [comment]
Completed.
