### ISSUE TITLE
Deleting Empty Entry in Phonolgy Deletes All Empty Entries

### ISSUE THREAD

**Issue by le-birb** [DraqueT/PolyGlot#984]
Short version: deleting an empty entry in the phonology section deletes all empty entries, while the expected outcome would be only one empty entry being deleted.

Long version, to walk through when, how, and why this is encountered:
Say you're setting up a file for a new language, and want to define all the cool sounds in your words. It's going well, and you want to add a few more sounds, so you add some empty entries for them.
![image](https://user-images.githubusercontent.com/17369466/118446322-5c0a4200-b6a4-11eb-98cb-e6ff82e9f7f2.png)

Now, you realize that you've added one too many! Maybe you have /pʰ tʰ kʰ p t k b d g/ to add (9 sounds) but you've got 10 empty spots. No biggie, just delete the extra one. But when you do this, they all go away!
![image](https://user-images.githubusercontent.com/17369466/118447163-4d705a80-b6a5-11eb-8f99-32d267f70aa7.png)

It's not a huge setback or anything, but it is a bit unintuitive, unexpected, and possibly frustrating. Possibly of note is that deleting a non-empty entry doesn't delete any empty entries.

**Comment by DraqueT** [comment]
Thanks for the heads up here! This is a pretty particular one that I had never thought to check for!

**Comment by le-birb** [comment]
I took a look thorugh the code for this one too, and the issue stems from [this call](https://github.com/DraqueT/PolyGlot/blob/4a1c98e0c890278ba70841c5f4d0d5d506adbd3a/src/main/java/org/darisadesigns/polyglotlina/Screens/ScrPhonology.java#L554
) in the deleteProc() function, and specifically [this filter](https://github.com/DraqueT/PolyGlot/blob/4a1c98e0c890278ba70841c5f4d0d5d506adbd3a/src/main/java/org/darisadesigns/polyglotlina/ManagersCollections/PronunciationMgr.java#L118), which removes _any_ entries with the same pronunciation as the selected one (I have confirmed this with duplicate non-empty entries).
