### ISSUE TITLE
Conlang quiz bug?

### ISSUE THREAD

**Issue by ERM-TMG** [DraqueT/PolyGlot#987]
Apparently when there's few classes in a word the quiz engine just duplicates them to fill up the four options, but when one marks the second duplicate it counts that as an incorrect answer. I've checked and the duplicate isn't in the lexical classes page itself.
![PolyGlot Quiz 24_06_2021 18_48_08](https://user-images.githubusercontent.com/86428194/123303190-d2108d00-d51d-11eb-9f5a-b0f6f6a27aa3.png)

**Comment by ERM-TMG** [comment]
Update: the correct answer is chosen at random, not the first.
![PolyGlot Quiz 24_06_2021 19_04_32](https://user-images.githubusercontent.com/86428194/123304490-4ac41900-d51f-11eb-8cdb-db12d2fd8a16.png)

**Comment by DraqueT** [comment]
Thanks for reporting this! I've corrected this issue (and a couple of other tiny upgrades for randomized question generatino with classes) in the newest beta. You can snag and install from here:

https://draquet.github.io/PolyGlot/
