### ISSUE TITLE
PolyGlot stops responding(?) on Save

### ISSUE THREAD

**Issue by littleredrat** [DraqueT/PolyGlot#988]
Every time I hit Save, PolyGlot stops registering whatever I want to do in it. I can still scroll through the vocab list for some reason but that's all I can do. I have to kill it through Task Manager if I want to continue working. Anyone knows why this happens, if it's an issue on my end only, or did someone else perhaps run into this problem too? I've also noticed it happens when I work with the Quickentry Window. I have yet to test if it's like that without the window.

Tested more.
When I have the Quickentry Window open and save **without closing it first**, it stops cooperating. That way, I know how to prevent it, but it's still bothersome and I still don't know if it's just me or if it's an internal issue.

**Comment by DraqueT** [comment]
Thank you for making this ticket and for the specificity! If you make a new language file and try to save, do you get the same issue?

Also, could you please check in the PolyGlot folder of your home directory and see if there’s an error log file? If there is, please toss it to me in an email to draquemail@gmail.com. That will help me track down what’s going on for you!

**Comment by littleredrat** [comment]
Thanks for the quick response!
I did not see an error log file.

Also, I tested more and found out this:
1) The same issue happened when I made a new language.
(1.1., it took a while for PolyGlot to notice that there was a new language file, and the testing language only appeared in the language list after several forced restarts, as I was testing the Quickentry problem. Not sure if it just takes time or if that's another thing that needs to be addressed. I could still open it manually via the File dropdown menu though, so it wasn't really an issue.)
2) It doesn't only happen when I try to save, it also happens when I try setting up declensions/conjugations (again, whilst the Quickentry window is open). I then tried to change the font (with Quickentry open), and it happened again.
3) I can still close the Quickentry window after the rest of PolyGlot stops being responsive.
4) Hitting Ctrl + S still works, so in case I encounter this again, I won't lose any data. I can't click anything even after that, though.

It then occurred to me that perhaps PolyGlot doesn't like it when I save while having more than one window open, so I popped two out and saved, but that worked fine. Trying to work on declensions with one or more other windows in the background also does not cause any issues. It seems to me that the Quickentry is the only element that causes this.

**Comment by DraqueT** [comment]
Ok, I think this might actually be a bug that has already been fixed, but hasn't been released yet. Please try downloading the newest beta and see if this corrects the problem for you. If not, I will definitely keep looking here, though. You can snag it here:

https://draquet.github.io/PolyGlot/

**Comment by littleredrat** [comment]
Yes, it works fine now! Thank you!

**Comment by DraqueT** [comment]
Glad to hear it! Closing the bug for now. ^^
