### ISSUE TITLE
Local Language Text Sizing Failing to Function

### ISSUE THREAD

**Issue by chaver1** [DraqueT/PolyGlot#991]
I would say my major issue right now(and I love the software) is the text sizing. While changing Colang Font/Sizing seems to work quite well, and in my case I'm using hebrew script so it's better to have larger sizing. But for Local font, in my case english/latin alphabet, the text size really doesn't seem to change no matter what I do. and it is relatively difficult to read my local lang words and definitions. And I think personally I would also like it if we could modify the size of text in the etymology as well. Is there a bug here in regard to Local lang text sizing?

**Comment by DraqueT** [comment]
Could you please send me a copy of the language that's giving you that trouble? You can just email it to draquemail@gmail.com. That'll let me take a look at the particulars of why it's not letting you resize the local language stuff. Thanks for taking the time to type up a bug report!

**Comment by chaver1** [comment]
sure! when you say a copy of the language, do you mean the database?

**Comment by DraqueT** [comment]
Yup! Just the saved PGD file will do. ^^

**Comment by chaver1** [comment]
all right gotcha, I'll get it to you asap

**Comment by DraqueT** [comment]
Heyo! As a heads up, this one is fixed! You can snag the newest beta over here, which has that and some other still-unreleased features:
https://draquet.github.io/PolyGlot/

**Comment by chaver1** [comment]
excellent, thank you!
