### ISSUE TITLE
Relational word Classes: EX: synonyms/antonyms

### ISSUE THREAD

**Issue by chaver1** [DraqueT/PolyGlot#992]
I would really love if there was an explicit way to do this. It is practically impossible to do this with say lexical classes since you with a synonym-antonym system you are trying to link specific words to each other. 

I.e. I'd love if as part of the definition, there was a synonym and antonym section and designated synonyms/antonyms just appeared as tagged

**Comment by DraqueT** [comment]
This is an absolutely fantastic idea. I'm just going to add it as classes that make relational values between words, which could  be synonyms, antonyms, or anything else.
