### ISSUE TITLE
Accented vowels import as weird text—e.g. ó > Ã³

### ISSUE THREAD

**Issue by emilyrln** [DraqueT/PolyGlot#999]
I use accented characters for my conlang words (specifically, vowels with acute accent or dieresis). When I import my CSV or XLS files, all of the accented characters turn into weird ASCII gibberish. Is there a way to replace characters all at once instead of word by word? I've got over 1500 words I'd need to go through…

![image](https://user-images.githubusercontent.com/89612358/131042411-12505ea7-8eef-4267-bded-4b42837d1824.png)

If there's an existing fix to this issue, I haven't found it in the Help doc or by searching Google. I really want to try using PolyGlot for my conlang, but the character soup is killing me.
Thank you!

**Comment by DraqueT** [comment]
Looks like this was corrected by a prior pull. Works in the beta. Closing.
